- examples/config-provider/demos/others.vue
- src/transfer/components/transfer-list.tsx
- src/transfer/components/transfer-operations.tsx
- src/transfer/components/transfer-search.tsx
- src/transfer/transfer.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/transfer/__snapshots__/demo.test.js.snap
- test/unit/transfer/index.test.js
规范CSS类名。
子仓库修改见：https://github.com/Tencent/tdesign-common/pull/18
Component | old class name | new class name
-- | -- | --
Transfer | t-transfer-list | t-transfer__list
Transfer | t-transfer-list-source | t-transfer__list-source
Transfer | t-transfer-list-target | t-transfer__list-target
Transfer | t-transfer-list__header | t-transfer__list-header
Transfer | t-transfer-list__body | t-transfer__list-body
Transfer | t-transfer-list-with-search | t-transfer__list--with-search
Transfer | t-transfer-list-search-wrapper | t-transfer__search-wrapper
Transfer | t-transfer-list__content | t-transfer__list-content
Transfer | t-transfer-list__item | t-transfer__list-item
Transfer | t-transfer-list__wrapper | t-transfer__list-wrapper
Transfer | t-transfer-list__pagination | …
> refactor(transfer): update css class name

- examples/icon/icon.md
- package.json
升级展示用的icon-view包 规范web component 名称为`td-icon-view` 和其他tdesign的web-component保持一致。
> chore: upgrade icon-view

- examples/drawer/drawer.md
- src/dialog/dialog.tsx
- src/drawer/drawer.tsx
- src/drawer/props.ts
- src/drawer/type.ts
- src/loading/loading.tsx
- src/loading/plugin.tsx
fix issue: https://github.com/Tencent/tdesign-vue/issues/73
sub repository pr: https://github.com/Tencent/tdesign-common/pull/59 (already passed)
> fix: drawer&dialog scroll through

- package.json
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/comment/__snapshots__/demo.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/dialog/__snapshots__/demo.test.js.snap
- test/unit/drawer/__snapshots__/demo.test.js.snap
- test/unit/dropdown/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/input/__snapshots__/demo.test.js.snap
- test/unit/input/__snapshots__/index.test.js.snap
- test/unit/layout/__snapshots__/demo.test.js.snap
- test/unit/menu/__snapshots__/demo.test.js.snap
- test/unit/notification/__snapshots__/demo.test.js.snap
- test/unit/popconfirm/__snapshots__/demo.test.js.snap
- test/unit/progress/__snapshots__/demo.test.js.snap
- test/unit/progress/__snapshots__/index.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
- test/unit/steps/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/tabs/__snapshots__/demo.test.js.snap
- test/unit/tag/__snapshots__/demo.test.js.snap
- test/unit/tag/__snapshots__/index.test.js.snap
- test/unit/tree-select/__snapshots__/demo.test.js.snap
1. 修复props变更不触发重新渲染的问题
- https://github.com/Tencent/tdesign-vue-next/issues/130 
- https://github.com/Tencent/tdesign-vue-next/issues/41
2. 移除此前重复的class (这个变动会影响snapshot, 多余的class会移除）
3. icon版本改完`~` 针对后续一些问题修复 用户可以平滑升级。
> fix(icon): re-render props

- examples/loading/demos/attach.vue
- examples/loading/demos/delay.vue
- src/loading/icon/gradient.tsx
- src/loading/loading.tsx
- src/loading/plugin.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/loading/__snapshots__/demo.test.js.snap
1. 使用vue3 composition API重构Loading组件。
2. loading部分框架无关代码统一使用common中复用代码 方便维护。
3. 去掉attach demo中无效的一行div 此改动同时需要更新snapshot
> refactor(loading): use composition API to refactor loading

- src/textarea/textarea.tsx
fix #387
日常 bug 修复 
https://github.com/Tencent/tdesign-vue/issues/387
- fix(textarea): 解决value未定义时初始长度为9
> fix(textarea): 解决value未定义时初始长度为9

- src/table/index.ts
日常 bug 修复 
#374 
没有导出 Table，按需引用时，直接引用 Table 会报错：
```js
import { Table } from 'tdesign-vue-next' // does not provide an export named 'Table'
```
> fix(table): export table directly

- src/config-provider/useConfig.tsx
- src/hooks/useKeepAnimation.ts
- src/hooks/useRipple.ts
resolve #435
- fix(useRipple): 修复 `useRipple` 导致的告警
> fix(useripple): fix inject warning

- src/pagination/pagination.tsx
- src/pagination/props.ts
- src/pagination/usePaginationClasses.ts
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
resolved #440
- fix(pagination): 修复分页组件 `pageSize` 默认值不正确导致的受控问题
> fix(pagination): pagination pagesize controlled

- src/date-picker/date-picker.tsx
- 日常 bug 修复 修复datepicker打开时间面板重置时间的问题
- 删掉废弃的update逻辑
Before
https://user-images.githubusercontent.com/26377630/158923834-05edc928-18e1-43cd-992e-9cbadb1b5623.mp4
After
https://user-images.githubusercontent.com/26377630/158923842-81646307-18af-436c-859b-dc7a296c5113.mp4
- fix(date-picker): 打开时间面板重置时间
> fix(date-picker): reset time after time panel show

- src/progress/progress.tsx
- test/unit/progress/__snapshots__/index.test.js.snap
- test/unit/progress/index.test.js
- 日常 bug 修复
- 增加plump相关更细分的单测
- fix typo 
- https://github.com/Tencent/tdesign-vue/issues/569
- fix(progress): theme为plump且percentage为10没有展示文案
> fix(progress): display text when percent value=10

- src/checkbox/checkbox.tsx
- src/form/hooks.ts
- src/input-number/input-number.tsx
resolved  #513
#513
- fix(input-number): 修复 input-number 未注册 input 组件
- fix(checkbox): 修复 checkboxGroup disabled 属性无效
> fix: input-number unregistered input and checkgroup disabled fix

- src/upload/upload.tsx
- fix(upload): 修复triggerupload 方法未导出
> fix: upload expose triggerupload

- src/checkbox/checkbox.tsx
- src/checkbox/constants.ts
- src/checkbox/group.tsx
symbol类型的InjectionKey单独存放
- fix(checkbox): 修复组件开发时，热更新导致的provide&inject失效
> fix(checkbox): inject fail when hmr update

- CHANGELOG.md
- package.json
> chore: dump 0.12.1 [WIP] 需要确认日志

- src/transfer/utils.ts
- test/unit/transfer/index.test.js
同步vue2版本的问题修复 https://github.com/Tencent/tdesign-vue/pull/758
- fix(Transfer): 修复设置 `targetSort` 后未按预期展示的问题
> fix(transfer): 修复targetSort展示问题

- examples/date-picker/demos/date-range.vue
- src/date-picker/date-picker.tsx
- src/date-picker/props.ts
- src/date-picker/type.ts
#509 
- fix(data-picker): data-picker 增加 apply 事件
> feat(data-picker): add method onApply

- src/input/index.ts
- src/input/input.tsx
- src/input/useInput.ts
- src/select-input/useSingle.tsx
调整suffixIcon展示逻辑
https://github.com/Tencent/tdesign-vue-next/issues/519
背景： 目前input组件suffixIcon仅在组件初次渲染时进行赋值
方案：将suffixIcon逻辑移至render函数，另外select-input的clear按钮展示根据displayValue，并且，为了防止在选中选项后clearIcon闪烁，根据isHover决定是否className为 ${COMPONENT_NAME.value}__clear 
- fix(input): 修复input组件clearable问题
> fix: 修复input组件clearable问题

- site/plugin-doc/md-to-vue.js
修复在 windows 特定路径下，目录分隔符 `\` 和目录名被识别为转义字符导致的报错，页面无法加载。
> fix(live-demo): compatible with specific path in windows

- src/slider/hooks/useSliderInput.tsx
- src/slider/hooks/useSliderMark.tsx
- src/slider/slider-button.tsx
- src/slider/slider-mark.tsx
- src/slider/slider.tsx
fix #664
[#664 ](https://github.com/Tencent/tdesign-vue-next/issues/664)
关于marks属性在进行compostion Api重构时是以静态属性来设计的，现在改为响应性属性，同时顺带修复marks点击事件无效问题
- fix(Slider): 将marks属性更改为响应性属性，并内部修复marks刻度节点点击事件无效问题
> fix(slider): 修复Slider部分属性丢失响应性问题

- src/form/form-item.tsx
#505 
之前的代码中，因为 form 的 data 是一个对象，form-item 的 computed value 检测不到对象内属性的变化，需要使用 watch deep。
- fix(formItem): 解决有 select 在 form-item 中时，无法检测 value 变化，导致无法及时进行 validate 的问题。
> fix(#505): 修复 form-item 值校验响应问题

- src/message/messageList.tsx
1. 插件式调用onDurationEnd事件报错
1. 因为onDurationEnd事件冲突，导致两个函数合并成了数组，尝试在绑定事件前，先处理掉onDurationEnd，满足之后的回调。
> fix: message组件onDurationEnd冲突

- src/menu/submenu.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/menu/__snapshots__/demo.test.js.snap
https://github.com/Tencent/tdesign-vue-next/issues/510
解决 [t-header-menu]使用t-submenu template #icon无效的问题
- fix(t-head-menu): 使用t-submenu template #icon无效的问题
> fix(t-head-menu): t-submenu template #icon not work

- src/message/messageList.tsx
- src/notification/animate.ts
- src/notification/notification.tsx
- src/notification/notificationList.tsx
- src/notification/plugin.ts
https://github.com/Tencent/tdesign-vue-next/issues/720 完善message组件插件式调用传入事件方法
https://github.com/Tencent/tdesign-vue-next/issues/58 完善notification出现退出动画，替换先前的transitionGroup写法
- fix(message): 修复插件式调用时，用户传入`onCloseBtnClick`事件时，无法触发回调。
- feat(notification): 使用项目中已有的js动画方案，替换先前的`transitionGroup`方案，完善了组件出现和回收动画效果。其中涉及到**common**子仓库的修改，删除之前transition相关的类名，添加了一个`&-list__showt`类名。
相关PR: https://github.com/Tencent/tdesign-common/pull/450。
- feat(notification): 增加`onMouseenter`和`onMouseleave`事件，保证鼠标移入移出组件时，`duration`时间的停止和重新计时。
- fix(notification): 修复插件式调用时，用户传入`onCloseBtnClick` `onDurationEnd`事件时，无法触发回调。
> 完善message组件插件式调用传入事件方法；完善notification出现退出动画，替换先前的transitionGroup写法

- examples/dropdown/demos/custom.vue
- src/dropdown/const.ts
- src/dropdown/dropdown-item.tsx
- src/dropdown/dropdown-menu.tsx
- src/dropdown/dropdown.tsx
https://github.com/Tencent/tdesign-vue-next/issues/58 dropdown组件重构
- feat(dropdown): 使用compositionAPI重构dropdown组件
> feat(dropdown):使用compositionAPI重构dropdown组件

- src/form/form.tsx
- src/hooks/useDefaultValue.ts
- src/hooks/useVModel.ts
`useVModel` 与 `useDefaultValue` 在之前的实现中，通过判断value 是否为undefined来判断组件的非受控与受控，且这个执行时间在组件初始化阶段，当用户传入 value 为 undefined，会进入非受控模式。后续用户从外部对value的变化将不会驱动组件进行innerValue的变化。
```vue
<template>
<div class="tdesign-demo-block-column" style="max-width: 500px">
<t-input v-model="input" @change="onChange" />
<t-input :value="input" placeholder="请输入内容（有默认值）" @enter="onEnter" @change="onChange" />
</div>
</template>
<script setup>
import { ref } from 'vue';
const input = ref(undefined);
const onChange = (val) => {
input.value = val;
};
</script>
```
timePicker 修复
修复前
修复后
- fix(form): 修复当modelValue为外部传入的undefined时，双向绑定失效 ([issue #712](https://github.com/Tencent/tdesign-vue-next/issues/712))
- fix(form): 修复 `attrs` 注入异常 ([issue #671](https://github.com/Tencent/tdesign-vue-next/issues/671))
- fix(timePicker): …
> fix: control hook

- CHANGELOG.md
- package.json
> docs: release 0.14.2

- CHANGELOG.md
- package.json
- script/rollup.config.js
> docs: release 0.15.0

- commitlint.config.js
- package.json
无
Hi 我是 `cz-git` commitizen 适配器的作者，偶尔之间我查看了这个项目，发现他非常适合使用`cz-git`, 来提升你们的日常开发
- github: https://github.com/Zhengqbbb/cz-git
- 文档：https://cz-git.qbenben.com/zh/
1. **交互体验**。支持搜索，和上下选择的交互模式，减少 commit 过程中出现的拼写错误
2. **高度自定义**，cz-git 提供了丰富的自定义功能，让 工具 更契合团队整体习惯
3. **与 commitiint 联动**，可以读取和编写配置在 commitiint 配置文件
4. **轻量化**：只有一个独立依赖，1.8 MB
欢迎尝试使用体验，有任何问题或需求可以告诉我
可以考虑删除 `.husky/prepare-commit-msg` 文件
我在提交的过程中发现了你们使用 强制转换的 git hook `.husky/prepare-commit-msg`。
我个人认为这个是非常不好的。这会改变原有 git commit 命令的行为，并且在每次commit过后会自动打开编辑模式。这**丧失了使用命令行工具提供的便利性**。
BTW： 使用`cz-git` 可以在最终提交确认时输入 `e` 进入编辑模式。直接回车就提交
> chore: use cz-git commitizen adapter

- commitlint.config.js
- fix command throw error
- handle folder path
1. 替换命令 `git status --porcelain`: 
Give the output in an easy-to-parse format for scripts. This is similar to the short output, but will remain stable
across Git versions and regardless of user configuration. See below for details.
2. 修复`grep` 命令返回非成功导致捕获异常报错问题
3. 将获取到暂存区路径转换一层更好处理截取工作
1. 获取暂存区所有文件路径 
2. 进行字符串截取`src`相关路径
> chore: update precomputed scope for cz-git

- src/affix/affix.tsx
- src/button/button.tsx
当前`affix`仅在`unmount`时取消事件绑定，在`<keep-alive/>`场景下会出现页面隐藏后，仍在监听滚动事件的问题，下次回到页面时`affix`会异常展示；
https://github.com/Tencent/tdesign-vue-next-starter/pull/158 
https://preview-pr158-tdesign-vue-next-starter.surge.sh/
以上预览链接能复现出问题；当多个包含滚动列表的页面在`<keep-alive/>`下来回切换时，`affix`异常
分析出问题在于在`<keep-alive/>`下，组件隐藏后不会触发`unmount`，所以`affix`不会取消滚动事件的绑定，导致展示异常
- fix(Affix): 兼容`<keep-alive/>`场景
> affix兼容<keep-alive/>

- examples/input-number/input-number.md
- src/input-number/input-number.tsx
- src/input-number/props.ts
- src/input-number/type.ts
- [✅] 新特性提交
1. 希望在 t-input-number 中能自定义 t-input 的属性
2. 将 props 透传给 t-input
3. { suffix: "元" }
- [✅] 文档已补充或无须补充
- [✅] 代码演示已提供或无须提供
- [✅] TypeScript 定义已补充或无须补充
- [✅] Changelog 已提供或无须提供
> feat(input-number): 透传 Input 组件全部特性，即 inputProps

- src/slider/hooks/useSliderInput.tsx
问题：初版的Slider内部实现只初始化了部分inputNumber属性，导致其余的属性即使外部传入也不会生效
解决方案：inputNumberProps初始化时最终用外部属性覆盖，以开发者传入属性为准
- fix(Slider): 修复inputNumberProps无法支持readonly、tips等api配置问题
> fix(slider): fix inputNumberProps bug

- CHANGELOG.md
- package.json
> docs: release 0.16.0

- src/cascader/cascader.tsx
- src/cascader/components/Item.tsx
- src/cascader/components/Panel.tsx
- src/cascader/core/className.ts
- src/cascader/core/effect.ts
- src/cascader/core/helper.ts
- src/cascader/hooks.ts
- src/cascader/interface.tsx
- src/select-input/useMultiple.tsx
- test/unit/watermark/index.test.jsx
- fix(Cascader): 修复 `loading` 错位问题, 修复 `onBlur`, `onFocus` 事件实现
- chore: 代码优化
> fix: cascader loading icon

- CHANGELOG.md
- package.json
- script/rollup.config.js
- src/style/index.js
> docs: release 0.17.0

- src/radio/group.tsx
closed #1107 
- fix(RadioGroup): 修复 `RadioGroup` 多次赋予不存在的值时文字不能正常显示
> fix(RadioGroup): 修复RadioGroup多次赋予不存在的值时文字不能正常显示

- examples/form/demos/validator.vue
- examples/form/form.md
- src/form/form-model.ts
closed #1098 
- feat(Form): 添加内置校验方法 `whitespace`
> feat(Form): 添加内置校验方法whitespace

- src/date-picker/DatePicker.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/hooks/useSingle.tsx
- #1114
- fix(DatePicker): 修复日期选择器在表单禁用后还能点击的问题
> fix(DatePicker): 修复日期选择器在表单禁用后还能点击的问题

- src/form/form.tsx
#1112 
- fix(Form): 修复不传 `form.onSubmit` 回调函数导致的 `scrollToFirstError` 参数失效的问题
> fix(form): scroll to first error

- src/slider/hooks/useSliderInput.tsx
问题：使用数字输入框的情况下，同时传入range和min或max其中之一的属性，手动输入某个值会导致渲染出NaN
原因：当存在min或max时，进行删减操作会导致inputNumber组件的onChange函数回传undefined值
解决办法：对于传入inputNumber的onChange函数进行一层格式化封装避免非数字回传值更新
- fix(Slider): 使用 `InputNumber` 时在使用 `range` 属性情况下传入 `min` 或 `max` 会导致手动输入显示NaN问题
> fix(slider): fix slider inputNumber decrease value bug

- src/tree/tree-item.tsx
- src/tree/useTree.tsx
- src/tree/util.ts
#1171
https://github.com/Tencent/tdesign-vue-next/issues/1171
1. 问题：控制台报 props （name）类型校验失败的 warn
2. 解决办法：将 name 转换为 string 类型
- fix(Tree): 取消修改 `value` 类型, 将传入 `TCheckBox` 组件的 `name` 转为 `string` 类型
> fix(tree): 取消getRightData, 修改传入TCheckBox组件的name类型

- examples/slider/slider.md
- examples/slider/usage/props.json
- src/slider/hooks/useSliderTooltip.tsx
- src/slider/props.ts
- src/slider/slider-button.tsx
- src/slider/slider.tsx
- src/slider/type.ts
- src/slider/util/common.ts
- test/unit/slider/base.test.jsx
解决问题： 补充原来slider漏开发的label属性逻辑
设计思路：原文档上的label属性说明解释该属性支持`boolean`|`string`|`slot`|`function`四种类型用法，但是开发过程中发现，首先布尔值的支持就是不合理的，因为slider值的文案显示控制权已经交由`tooltipProps`来控制，因此这次去除了`boolean`的支持。另外，label支持`slot`用法也不太符合组件层级直觉，因为slider的首个嵌套子组件是内部的滑块button，如果另外开个`slot`来配置tooltip的显示内容，在层级上会稍显混乱，且过高的内容自定义控制权会影响tooltip本身的内部样式变得难以维护；再者，如果需要高度自定义tooltip的内容，代码中也留了后门可以传入`TNode`来渲染。综合考虑下来，对于slider滑块的tooltip内容显示，更多场景下是使用模版替换功能来定制数值以外的文案提示，因此前期先支持`string` 类型传入和模版替换特性已经可以满足大部分需求，也便于编写单元测试。
- fix(Slider): 修复 `label` 属性不生效 `bug`
- fix(Slider): 修复 `tooltipProps` 为布尔值时丢失响应性问题
> fix(slider): fix slider label prop

- src/tree-select/tree-select.tsx
#1193 
反馈无法在异步加载后展示node的label属性，采用Tree组件的onLoad事件实现加载后重新获取nodeInfo
- fix(TreeSelect): 修复异步加载回显展示问题
> fix(tree-select): fix lazy node exception

- package.json
> docs: release 0.17.4

- src/input/useInput.ts
1. 修复 Input 组件 切换 type 后不生效的问题，官网 Input 中组件示例 选择 type 切换时 Input 中的 type 不会变化。
2. 添加 watch
3. 复现地址：https://tdesign.tencent.com/vue-next/components/input 示例中切换 type 即可复现
- fix(Input): 修复 `Input` 组件切换 `type` 后不生效的问题
> fix(input): 修复 Input 组件 切换 type 后不生效的问题

- src/table/hooks/useRowSelect.tsx
修复可选中行table组件，data为空数据时，默认全选按钮会选中的问题
修复后
原因
对空数据没进行判断
解决方案
对空数据做处理
- fix(Table): 修复可选中行 `table` 组件，`data` 为空数据时，默认全选按钮会选中的问题
> fix(table): 修复可选中行table组件，data为空数据时，默认全选按钮会选中的问题

- src/date-picker/panel/RangePanel.tsx
- fix(`DatePicker`): 修复 `range` 选择器开始时间被禁用问题
> fix: 修复range 选择器开始时间被禁用问题

- src/dialog/dialog.tsx
https://github.com/Tencent/tdesign-vue-next/issues/1221
- fix(Dialog): 修复 `preventScrollThrough` 为 `false` 情况下，`body` 间去了滚动条宽度
> fix(dialog): 修复preventScrollThrough为false情况下，body间去了滚动条宽度

- examples/table/demos/tree.vue
- src/table/hooks/tree-store.ts
- src/table/hooks/useTreeData.tsx
- fix(Table): 树形结构，懒加载节点重置时（即调用 `setData`）没有清空子节点信息问题
- feat(Table): 树形结构，支持 `resetData` 重置整个树形结构数据
重置数据放在这个 PR 时因为，这是个很小的基础特性，不会引入任何升级相关的缺陷
> fix(table): reset lazy load children state in map; resetData support

- examples/slider/demos/min-and-max.vue
- examples/slider/slider.md
- src/slider/props.ts
- src/slider/slider.tsx
- src/slider/type.ts
- test/unit/slider/base.test.jsx
slider内部本身早已实现了showStep的属性及其功能UI，但因为一直没有开放出来，因此内部一直以默认值false运行着。本次pr主要将该属性暴露给用户配置，并且补充对该属性表现层的单元测试及文档说明。
- feat(Slider): Slider新增showStep属性控制步长刻度值显示
> feat(slider): add showStep prop

- CHANGELOG.md
- package.json
由于0.18.2有breakingchange 没有带上，所以补发0.19.0
> docs: release 0.19.0

- examples/table/demos/editable-row.vue
- examples/table/table.en-US.md
- examples/table/table.md
- src/table/editable-cell.tsx
- src/table/hooks/useEditableRow.ts
- src/table/type.ts
- feat(Table): 可编辑行功能，校验函数 `validateRowData` 和 `validateTableData` 返回值支持 `Promise` 对象
- fix(Table): 可编辑单元格，多选和日期选择，点击下拉浮层中的内容会导致退出编辑，[tdesign-vue-next#issue1384](https://github.com/Tencent/tdesign-vue-next/issues/1384)
> feat(table): set return value type of validateRowData  to be a Promise

- examples/menu/demos/multiple.vue
- src/menu/submenu.tsx
t-menu-item 大于8个将会溢出：https://github.com/Tencent/tdesign-vue-next/issues/1249
1. 当 t-menu-item大于 8 个时出现滚动条 
2. 对 exapmle multiple 增加 t-menu-item  用于演示
<div>
</div>
- fix(menu): t-menu-item 大于 8 个将会溢出
> fix(menu): submenu beyond 8 will overflow

- src/menu/submenu.tsx
[Menu]在nuxt3里面鼠标悬浮或者点击子菜单不出现 元素代码里面出现一瞬间就消失了: https://github.com/Tencent/tdesign-vue-next/issues/937
详细的背景和解决方案在 issue 中有详述
- fix(menu): submenu nuxt3 onmouseenter invalid
> fix(menu): submenu nuxt3 onmouseenter invalid

- src/table/hooks/useColumnResize.ts
#1406 
1. 添加注释
- fix(table): 宽度计算函数添加注释
> fix(table): 表格宽度计算函数添加注释

- src/slider/hooks/useSliderInput.tsx
[#1437](https://github.com/Tencent/tdesign-vue-next/issues/1449)
1. inputNumber逻辑中判断输入值时发生了隐式转换，因此输入0时不会出发onChange。目前已特别处理
fix(Slider): 修复 `Slider` 输入框无法输入 `0` 问题 ( [#1437](https://github.com/Tencent/tdesign-vue-next/issues/1449))
> fix(slider): 修复Slider输入框无法输入0问题

- src/cascader/hooks.ts
- fix(Cascader): 修复异步获取 `options` 后的懒加载无效 ([issue #1448](https://github.com/Tencent/tdesign-vue-next/issues/1448)) ([issue #1223](https://github.com/Tencent/tdesign-vue/issues/1223))
- fix(Cascader): 修复 `value` 不是 options 的健值会报错 ([issue #1293](https://github.com/Tencent/tdesign-react/issues/1293))
> fix: cascader lazy load options

- src/table/hooks/useColumnResize.ts
- src/table/thead.tsx
1. 鼠标hover在表头分割线上的时候也是能显示拖拽光标的
1. 新增左侧判定距离，并调整对应列
- fix(Table): 允许在表头分割线一定范围内触发列宽调整逻辑
> fix(table): 允许在表头分割线一定范围内触发列宽调整逻辑

- src/input/input.tsx
fix(input): 修正 `password` 类型输入框切换为预览时 预览图标会被覆盖的问题
> fix(input): 修正 `password` 类型输入框切换为预览时 预览图标会被覆盖的问题

- src/cascader/cascader.tsx
- src/popup/container.tsx
- src/popup/popup.tsx
- fix(Cascader): 修复在输入时 `entry` 键会默认全选第一个选项的全部内容 ([issue #1529](https://github.com/Tencent/tdesign-vue-next/issues/1529))
- fix(Cascader): 修复通过 `SelectInputProps ` 透传方法属性导致传入 `SelectInput` 的数据变成的数组 ([issue #1502](https://github.com/Tencent/tdesign-vue-next/issues/1502))
- fix(Popup): 修复 `overlayInnerStyle ` 未监听变化，增强 `container` 健壮性 ([issue #1442](https://github.com/Tencent/tdesign-vue-next/issues/1442))
> fix: issues 0830

- package.json
BREAKING CHANGE :
因为esm不支持folder as module, 在使用esm时候不再支持以目录作为引用的路径,而要写完整的路径和扩展名
closed #1295
#1295
支持原生的esm，方便使用基于esm的工具
1、exports不支持目录作为入口，基于esm以后引用的时候的时候必须写全路径。
2、影响到`unplugin-vue-components`的tdesign resolver，因为它引用样式的方式是目录引用，需要改成全路径引用。而最新的版本，都已经默认自己去引用组件了，引用样式的sideEffect可以删除。
https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/tdesign.ts
需要删除掉，请你们到`unplugin-vue-components`那里提交一个pr
```typescript
if (importStyle === 'less')
return `tdesign-${library}/esm/${fileName}/style`
return `tdesign-${library}/es/${fileName}/style`
```
> feat: 支持原生的esm exports, 方便运行基于esm的工具运行(例如vitest)

- examples/select/select.en-US.md
- examples/select/select.md
- src/select/_example/multiple.vue
- src/select/helper.ts
- src/select/option-props.ts
- src/select/option.tsx
- src/select/props.ts
- src/select/select.en-US.md
- src/select/select.md
- src/select/select.tsx
- src/select/type.ts
https://github.com/Tencent/tdesign-vue-next/issues/1503
需求背景：
期望实现类似 Checkbox 组件一样的全选功能，支持两种写法。
```html
<t-select v-model="value1" :options="options1" placeholder="请选择云解决方案" multiple />
<t-select v-model="value2" placeholder="请选择云产品" multiple>
<t-option label="全选" :check-all="true" />
<t-option v-for="item in options2" :key="item.value" :value="item.value" :label="item.label"></t-option>
</t-select>
```
```ts
const options1 = [
{ label: '全选', checkAll: true },
{ label: '架构云', value: '1' },
{ label: '大数据', value: '2' },
{ label: '区块链', value: '3' },
{ label: '物联网', value: '4', disabled: true },
{ label: '人工智能', value: '5' },
];
```
解决方案：
参考`checkbox-group`组件，计算全选、半选状态。
- feat(Select): 支持基础功能「全选」([issue #1503](https://github.com/Tencent/tdesign-vue-next/issues/1503))
- feat(Select): …
> feat(select): 支持基础功能「全选」(#1503)

- script/generate-usage/config.js
- src/drawer/_usage/index.vue
generate-usage生成的基础用例文件存在同名属性覆盖了组件props，导致基础用例切换该属性值时不生效
- fix(generate-usage): 修复文档中基础用例与预期不符
> fix: drawer组件基础用例的generate配置有误

- src/form/form-item.tsx
Tencent/tdesign-vue#1435 同样的问题
- fix: 修复 form 组件 labelAlign 为 top 时, form-item lable 为空 lable 还会占据空间的问题
> fix: 修复 form 组件 labelAlign 为 top 时, form-item lable 为空 lable 还会占据空间的问题

- src/form/form-item.tsx
- src/table/hooks/useRowSelect.tsx
#1632 
- fix(Table): 修复 `columns type` 为 `multiple` 时，设置 `className` 无效的问题 ([issue #1632](https://github.com/Tencent/tdesign-vue-next/issues/1632))
> fix(table): 修复 columns type 为 multiple 时，设置 className 无效的问题

- CHANGELOG.md
- package.json
> release: publish 0.21.0

- src/table/hooks/useFixed.ts
1. 延迟更新表头时，表宽被错误更新导致部分列宽度计算有误
1. 监听列属性变化时不更新表宽，仅根据当前表格宽度重新计算各列宽度
- fix(table): 延迟更新表头时使用当前表宽重新计算各列宽度
> fix(table): 延迟更新表头时使用当前表宽重新计算各列宽度

- src/cascader/cascader.tsx
- src/cascader/components/Item.tsx
- fix(Cascader):修复面板 `padding`, 优化多选状态下叶子结点点击交互
> fix: cascader padding

- src/hooks/useDefaultValue.ts
- src/hooks/useVModel.ts
input 组件使用v-model.trim会将内容清空Bug： https://github.com/Tencent/tdesign-vue-next/issues/1699
解决背景见 issue
- fix(Hooks):  修复使用 `v-model.trim` 会将内容清空的问题
> fix(hooks): vm redundant paramters

- src/tree-select/tree-select.tsx
[#229](https://github.com/Tencent/tdesign/issues/229)
与 Select 组件保持一致，popup Content 中的内容应当包裹在  t-select__dropdown-inner t-select__dropdown-inner--size-s  内，同时给 t-select__dropdown-inner--size > t__tree 添加 padding
- fix(TreeSelect):  修复 `popuoContent` 无 `padding`
> fix: tree-select popuoContent 无 padding

- src/table/hooks/useRowExpand.tsx
- [√ ] 日常 bug 修复
- fix(Table): 修复不提供 `expandedRowKeys` 的绑定会报错
> 解决因为没有提供扩展属性导致出现NPE的错误的问题

- src/menu/menu-item.tsx
https://github.com/Tencent/tdesign-vue-next/issues/1671
- feat(Menu): 如果存在链接参数，默认使用标签 `<a>` ([issue #1671](https://github.com/Tencent/tdesign-vue-next/issues/1671))
> feat(menu): render `<a>` tag when href prop

- src/table/hooks/useColumnResize.ts
- src/table/thead.tsx
- src/table/type.ts
https://github.com/Tencent/tdesign-vue/issues/1348
1. 新增 column.resizable 支持自定义任意列是否可拖拽调整宽度
- feat(table): 新增 column.resizable 支持自定义任意列是否可拖拽调整宽度
> feat(table): 新增 column.resizable 支持自定义任意列是否可拖拽调整宽度

- src/date-picker/DatePicker.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/hooks/useSingle.tsx
> fix: 优化 datepicker 输入事件交互

- src/skeleton/__tests__/index.test.jsx
Skeleton: add skeleton test
新增组件单元测试
- test(Skeleton): 增加 `skeleton` 单元测试 
> test(unit): skeleton: add skeleton test

- src/textarea/__tests__/index.test.jsx
textarea: add textarea test
新增组件单元测试
test(Textarea): 补充 `textare` 单元测试
> test(unit): textarea: add textarea test

- src/select-input/useOverlayInnerStyle.ts
- https://github.com/Tencent/tdesign-react/issues/1523
- feat(Select): 调整下拉交互允许输入时，不关闭下拉面板，减少相关交互问题
> feat(SelectInput): keep panel display when allow input

- src/tree-select/_example/base.vue
- src/tree-select/tree-select.tsx
- src/tree/tree-item.tsx
- src/tree/useTree.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/1738
- fix(TreeSelect): 修复多选状态下点击选项直接关闭面板的问题
- fix(Tree): 修复`expandOnClickNode`与`checkable`冲突的问题
- fix(Tree): 修复`disabled`状态下无法展开子选项的错误
> fix(Tree): expand and checkable status conflict

- src/steps/__tests__/index.test.jsx
- src/steps/steps.tsx
新增组件单元测试
- test(Steps): 补充 `steps` 单元测试
> test(unit): steps: add steps test

- CHANGELOG.md
- package.json
> docs: release 0.24.0

- src/tooltip/tooltip.tsx
#1834 
问题：tooltip内部默认传入的popup的属性覆盖了动态的visible
解决方案：所有动态属性后置
- fix(Tooltip): 修复 `tooltip` 无法显示问题([issue #1834](https://github.com/Tencent/tdesign-vue-next/issues/1834))
> fix(tooltip): 修复tooltip内部visible属性被默认配置覆盖问题

- src/dropdown/_example/slot.vue
- src/dropdown/dropdown-menu.tsx
- src/dropdown/hooks/useDropdownOptions.ts
- https://github.com/Tencent/tdesign-vue-next/issues/1850
- fix(dropdown): 修复插槽平铺内容为子节点内容渲染丢失部分元素的问题
> fix(dropdown): flat children as item children

- src/select/select.tsx
- fix(Select): 修复无法使用 `0` 作为 `value` ([issue #1928](https://github.com/Tencent/tdesign-vue-next/issues/1928))
> fix: select value 0 disabled

- src/table/base-table.tsx
https://github.com/Tencent/tdesign-vue-next/issues/1934
1. 增加判断，在resizable为false时，表格本体忽略thWidthList的传值
- fix(table): 当禁用resizable时，表格默认使用用户定义的列宽
> fix(table): 当禁用resizable时，表格默认使用用户定义的列宽

- README-zh_CN.md
- README.md
> docs: add README in English

- src/input/input.tsx
- src/input/useInput.ts
- src/input/useInputWidth.ts
- src/pagination/usePaginationClasses.ts
- src/table/tr.tsx
- fix(Input): 默认值 `format` 失效问题，[issue#1964](https://github.com/Tencent/tdesign-vue-next/issues/1964)
- fix(Input): 修复在输入框进行预渲染处于 `display: none` 状态时，宽度计算不正确问题，[tdesign-vue#1678](https://github.com/Tencent/tdesign-vue/issues/1678)
- feat(Table): 优化超出省略场景，浮层默认出现位置 `placement`
> fix(Input): auto width in display: none

- src/popup/__tests__/index.test.tsx
> test(unit): 新增 `Popup` 测试用例

- src/popconfirm/_example/describe.vue
[#251](https://github.com/Tencent/tdesign/issues/251)
带有描述文案的demo气泡框里描述字体的颜色不对
解决方案：
只改了demo里describe.vue中的类describe，加了颜色设置，修改后：
fix(PopConfirm): 修复官网 `demo` 气泡框描述文案字体颜色 ([#251](https://github.com/Tencent/tdesign/issues/251))
> fix: popconfirm describe text color

- src/menu/head-menu.tsx
closed #1810
#1810
- fix(Menu): 修复多层收纳导航 `head-menu` 默认未激活([issue 1810](https://github.com/Tencent/tdesign-vue-next/issues/1810))
> fix(menu): 初始化时维护menu数据

- src/popconfirm/popconfirm.tsx
- src/popup/popup.tsx
- fix(Popconfirm): 修复 `confirmBtn` 等属性存在类型错误 ([issue #1642](https://github.com/Tencent/tdesign-vue-next/issues/1642))
- fix(Dropdown): 修复 `hover` 有时候不能触发打开下拉菜单 ([issue #1642](https://github.com/Tencent/tdesign-vue-next/issues/1648))
> fix: 修复popup 类型问题

- site/plugin-doc/md-to-vue.js
> docs: 优化最后更新日期展示

- src/select/__tests__/index.test.jsx
- src/select/select.tsx
closed #2206
- fix(Select): `valueType` 或 `multiple` 动态切换导致组件失效 ([issue #2206](https://github.com/Tencent/tdesign-vue-next/issues/2206))
- test(Select): 补充单元测试
> fix(select): fix the calculation of innerValue

- package.json
> docs: release 1.0.6

- src/table/_example/editable-cell.vue
- src/table/editable-cell.tsx
- fix(Table): 修复 `column.edit.on.onChange` 无效报错问题，[issue#2362](https://github.com/Tencent/tdesign-vue-next/issues/)
> fix(table): fix edit.on.onChange is invalidate

- CHANGELOG.md
- package.json
> docs: release 1.0.7

- src/anchor/anchor.tsx
- src/badge/badge.tsx
- src/breadcrumb/breadcrumb-item.tsx
- src/color-picker/color-picker-panel.tsx
- src/dialog/dialog.tsx
- src/drawer/drawer.tsx
- #2421 
> 部分组件属性自动继承和手动绑定同时存在造成class属性会重复问题
- fix(Dialog):  修复 `class` 属性出现警告
- chore: 禁用部分组件属性自动继承
> fix: turn off auto attribute propagation for specific components

- CHANGELOG.md
- package.json
> docs: release 1.1.0

- src/popconfirm/popconfirm.tsx
- fix(Popconfirm): 修复 `visible-change` 事件中的的 `context.trigger` 在 `confirm` 事件中不携带标识 ([issue #2516](https://github.com/Tencent/tdesign-vue-next/issues/2516))
> fix: popconfirm visible-change ctx

- src/menu/menu.tsx
- [√] 日常 bug 修复
#2557 
- fix(Menu): 因为normal和popup的展开方式均使用同一个expandValues存储，在鼠标移出popup模式的子菜单之后，就会直接用setExpand的方法设置空的数组。因此重新展开后，normal模式的子菜单就是空的。
- 但是同时也发现了子菜单的bug，已经发起了新的issue #2588 
- fix(Menu): 修复重新展开后，`normal` 模式的子菜单就是空的。([issue #2557](https://github.com/Tencent/tdesign-vue-next/issues/2557))
- [√] 文档已补充或无须补充
- [√] 代码演示已提供或无须提供
- [√] TypeScript 定义已补充或无须补充
- [√] Changelog 已提供或无须提供
> fix(Menu): click twice to re-expand submenus

- src/table/sorter-button.tsx
- fix(Table): `getSortIcon is not a function` in Webpack5 & Vue3, [issue#2538](https://github.com/Tencent/tdesign-vue-next/issues/2538)
> fix(table): getSortIcon is not a function in webpack5 Vue3

- src/guide/guide.tsx
#2536 
高亮区域位置更新后调用popup update 以达到更新的目的
- fix(Guide):  解决 `guide popup` 提示在重叠情形下不更新 ([issue #2536 ](https://github.com/Tencent/tdesign-vue-next/issues/2536))
> fix(guide): update when popup ref position change

- src/input-number/useInputNumber.tsx
closed #2616 
- fix(input-number): 修复有 `max` 值时，清空数值，`blur` 会自动填充 `max` 的值([issue #2616](https://github.com/Tencent/tdesign-vue-next/issues/2616))
> fix(input-number): empty value change on blur

- src/menu/submenu.tsx
- [√] 日常 bug 修复
#2588 
fix(menu):
第一次鼠标触发事件的时候，组件才会开始渲染，然后触发handleMouseEnter，接着在setTimeout中在nextTick阶段将ref传递出来给subPopupRef。
但是实际上却没有改动，导致handleMouseLeavePopup方法中的target === subPopupRef.value判断为假（此时subPopupRef.value是undefined）所以直接导致追踪到根子菜单触发消失，然后整个popup菜单树消失。
第二次触发hover的时候才能真正拿到subPopupRef，于是符合target === subPopupRef.value条件，正常触发消失流程。
目前用watch来监视popupWrapperRef能够在更新值之后及时通过passSubPopupRefToParent传递给subPopupRef，handleMouseLeavePopup能够正常拿到subPopupRef即可
- [√] 文档已补充或无须补充
- [√] 代码演示已提供或无须提供
- [√] TypeScript 定义已补充或无须补充
- [√] Changelog 已提供或无须提供
> fix(menu): mouse hover first in submenu will make next submenu disappear

- src/tooltip/tooltip.tsx
- fix(Tooltip): 修复当 `content` 是空字符或空插槽时，不显示提示([issue #2642](https://github.com/Tencent/tdesign-vue-next/issues/2642))
> fix: tooltip empty

- src/date-picker/hooks/useSingle.tsx
业务开发中遇到的问题，使用Space组件 设置align="center"后高度被prefixIcon撑高。
- fix(组件名称): prefixIcon未传递时仍透传了prefixIcon函数导致产生非预期渲染。
> fix: 修复DatePicker的prefixIcon未传递时仍透传了prefixIcon函数导致产生非预期渲染

- src/tree/tree-item.tsx
- fix(tree): 修复懒加载子节点时点击 `label` 会触发选中的问题
> fix(tree): prevent trigger check when branch lazy load

- src/input-number/useInputNumber.tsx
https://codesandbox.io/s/tdesign-vue-demo-forked-m372sx?file=/src/demo.vue
如 当输入1.01后失焦，再输入1.00，会被重置会1.01
- fix(InputNumber): 修复小数位操作以 `0` 结尾时部分边界场景异常的问题
> fix(input-number): change decimal value on blur when end of 0

- src/radio/props.ts
- src/radio/radio-group-props.ts
- src/radio/radio.en-US.md
- src/radio/radio.md
- src/radio/type.ts
```
const options=[
{ value: true,  label: '启用' },
{ value: false, label: '停用' }
]
<t-radio-group name="status" :options="options" ></t-radio-group>
```
- feat(RadioGroup): `options.value` 支持 `boolean`
> feat(RadioGroup): options.value支持 boolean

- src/dropdown/hooks/useDropdownOptions.ts
[2688](https://github.com/Tencent/tdesign-vue-next/issues/2688)
1.template配置的content和prefixIcon插槽未进行渲染
2.传递子元素属性时，未做驼峰转换，子元素读取属性时又是通过驼峰属性名读取
1.已有的处理方案：
- dropdown是通过解析所有子元素然后生成options的数据，再传递给dropdown-menu的，处理过程未读取template
- 传递子元素属性时，未做属性驼峰转换
2.解决方案：
- 增加template的content和prefixIcon的插槽读取，优先template
- 传递子元素属性时，做属性名的驼峰转换处理
- fix(Dropdown): 修复下拉菜单配置 `template` 的 `content` 或 `prefixIcon` 插槽时未进行渲染的问题([issues #2688](https://github.com/Tencent/tdesign-vue-next/issues/2688))
> fix(dropdown): 修复下拉菜单配置template的content或prefixIcon插槽时未进行渲染的问题

- src/table/hooks/useColumnResize.ts
- src/table/thead.tsx
- fix(Table): 列宽调整功能，修复即使 `resizable=false` 时，也会显示拖拽调整列宽图标和辅助线问题，[issue#2699](https://github.com/Tencent/tdesign-vue-next/issues/2699)
- fix(Table): 列宽调整功能，修复在拖拽任意列宽使表格横向滚动条消失之后列宽无法正常调整的问题，即支持 `resize.minWidth`
- fix(Table): 列宽调整功能，修复开启多级表头时点击子表头后控制台报错的问题
> fix(table): column resizable

- src/popup/popup.tsx
[#2697](https://github.com/Tencent/tdesign-vue-next/issues/2697)
触发元素隐藏时，popper仍显示到页面左上角
- 触发元素或其上级元素通过block none隐藏了
- 触发元素或其上级元素从document.body中移除
- 通过getBoundingClientRect判断触发元素的宽高是否为0了
- 是否还在document.body中
- 如果宽高为0或者不在document.body中，则做隐藏处理
- fix(Popup): 修复触发元素隐藏时，`popper` 仍显示到页面左上角的问题([#2697](https://github.com/Tencent/tdesign-vue-next/issues/2697))
> fix(popup): 修复触发元素隐藏时，popper仍显示到页面左上角的问题

- src/icon/_example/icon-select.vue
- src/icon/icon.md
在用户群，有使用者反馈导入所有图标提示报错，经过排查发现因为 vite 的原生 module 加载方式不支持 cjs。现在改用入口导出的 esm 内容。
- docs(icon): 修复 manifest 统一入口导出 esm 模块，文档为及时更新的问题
> docs(icon): 修复 manifest 统一入口导出 esm 模块，文档为及时更新的问题

- src/date-picker/date-range-picker-props.ts
[#2755](https://github.com/Tencent/tdesign-vue-next/issues/2755)
校验器使用 || 并值，只会得到第一个值
把( || ) 改成( , )号，确保数组是类型的所有值
- fix(DateRangePicker): 修复valueType的validator校验错误([issue #2755](https://github.com/Tencent/tdesign-vue-next/issues/2755))
> fix(DateRangePicker): 修复valueType的validator校验错误

- src/affix/affix.tsx
[#2744](https://github.com/Tencent/tdesign-vue-next/issues/2744)
requestAnimationFrame在Unmounted之后仍执行了一次 导致异常报错
获取requestAnimationFrame的返回 ID，在BeforeUnmount进行cancelAnimationFrame调用取消后续的requestAnimationFrame的执行
- fix(table): 修复取消表尾吸底时requestAnimationFrame在Unmounted之后仍执行了一次导致的异常问题([issue #2744](https://github.com/Tencent/tdesign-vue-next/issues/2744))
> fix(table): 修复取消表尾吸底时requestAnimationFrame在Unmounted之后仍执行了一次导致的异常问题

- src/table/hooks/useFixed.ts
[#2759](https://github.com/Tencent/tdesign-vue-next/issues/2759)
由于updateFixedStatus里做了setTimeout事件，触发的setFixedRowPosition会去读取列表data的长度，所以在setTimeout之前构造一个setTimeout去更新data的长度，就会导致tr获取不到
做tr不存在的兼容处理
- fix(Table): 修复设置固定行位置信息时出现tr不存在情况时导致的异常报错([issue #2759](https://github.com/Tencent/tdesign-vue-next/issues/2759))
> fix(Table): 修复设置固定行位置信息时出现tr不存在情况时导致的异常报错

- src/table/ellipsis.tsx
[#2796](https://github.com/Tencent/tdesign-vue-next/issues/2796)
开启省略号ellipsis和虚拟滚动后，快速滚动控制台报读取null的属性异常
原因是：
开启debounce后，延迟80ms后节点不存在了，仍调用了isNodeOverflow方法
先判断一下节点是否存在，如果存在才继续执行后续函数逻辑
- fix(Table): open ellipsis and virtual scroll console error ([issue #2796](https://github.com/Tencent/tdesign-vue-next/issues/2796))
> fix(Table): open ellipsis and virtual scroll console error

- src/color-picker/color-picker.en-US.md
- src/color-picker/color-picker.md
- src/color-picker/color-picker.tsx
- src/color-picker/panel/index.tsx
- src/color-picker/panel/linear-gradient.tsx
- src/color-picker/props.ts
- src/color-picker/trigger.tsx
- src/color-picker/type.ts
- https://github.com/Tencent/tdesign-vue/issues/1548
- feat(ColorPicker): 新增`size` 和 `enableMultipleGradient` API
> feat(color-picker): support size and enableMultipleGradient api

- src/popup/popup.tsx
#2835 
暴露出的`close`方法由用户调用时大概率是不会传`event`事件的。因此在暴露`close`方法时不传参数，让`switch`走`default`判断，这里的`triggerType`可能需要决定一下叫啥名字。
- fix(popup): 修复调用popup组件暴露的`close()`时报错([issue #2835](https://github.com/Tencent/tdesign-vue-next/issues/2835))
> fix(popup): call close method will get error

- src/radio/group.tsx
暂时未提issue
如果父元素width设置为100%, 滑动块样式不会自动重新计算位置和偏移, 导致容易出现这样的情况.
- fix(RadioGroup): 修复父元素 `width` 设置为 `100%`, 滑动块样式不会自动重新计算位置和偏移
> fix(radio-group): 如果父元素width设置为100%, 滑动块样式不会自动重新计算位置和偏移

- src/message/messageList.tsx
- src/message/plugin.tsx
- src/message/type.ts
MessagePlugin.close方法在同时显示多个TMessage的时候会导致调用错对应TMessage Instance的close方法，导致关闭了错误的TMessage
https://stackblitz.com/edit/dq51jw-y8h43c?file=package.json,src%2Fdemo.vue
复现代码：
```javascript
new Promise((resolve) => {
const uploading1 = MessagePlugin.loading(`loading 1`, 0);
setTimeout(() => {
MessagePlugin.close(uploading1);
MessagePlugin.success('success 1', 0);
resolve(true);
}, 1000);
});
new Promise((resolve) => {
const uploading2 = MessagePlugin.loading(`loading 2`, 0);
setTimeout(() => {
MessagePlugin.close(uploading2);
MessagePlugin.success('success 2', 0);
resolve(true);
}, 5000);
});
```
- fix(message): 修复同时显示多个Message时，会导致调用错误的关闭方法导致关闭错误的Message的缺陷
> fix(message): messagePlugin extraApi return wrong Message instance

- src/image-viewer/image-viewer.tsx
closed #2872
#2872 #2858 
fix(ImageViewer): `closeBtn` 渲染异常([issue #2872](https://github.com/Tencent/tdesign-vue-next/issues/2872))([issue #2858](https://github.com/Tencent/tdesign-vue-next/issues/2858))
> fix(ImageViewer): closeBtn渲染异常

- src/dialog/dialog.tsx
#2644 
- fix(Dialog): 全屏状态下关闭 `footer`,仍然占据 `body` 高度([issue #2644](https://github.com/Tencent/tdesign-vue-next/issues/2644))
> fix(dialog): fullscreen without footer body height

- src/input-adornment/input-adornment.tsx
- https://github.com/Tencent/tdesign-vue/issues/2356
- fix(InputAdornment): 修复 `prepend` 或 `append` 为空字符串时仍然渲染节点的问题
> fix(input-adornment): fix render empty string prepend and append

- src/menu/submenu.tsx
common: https://github.com/Tencent/tdesign-common/pull/1366
线上样式：
顶部导航菜单位置有误
dark 主题下弹窗菜单缺少边框：
与设计稿不符：
https://www.figma.com/community/file/1053279236128724321/TDesign-for-web
- fix(Menu): 修复顶部导航菜单位置有误的问题
- fix(Menu): 修复 `theme = dark` 模式下弹窗菜单缺少边框样式的问题 https://github.com/Tencent/tdesign-common/pull/1366
> fix: menu popup style

- src/image-viewer/utils.ts
[#2395](https://github.com/Tencent/tdesign-vue-next/issues/2935)
1、问题
链接带参数时（?或#），扩展名失效
2、处理方案
做?和#的字符串分割，取无参数的部分再进行/分割，拿到最后的原文件名，再进行下载
- fix(ImageViewer): 修复图片链接带有参数时，下载时文件扩展名丢失 ([issue #2935](https://github.com/Tencent/tdesign-vue-next/issues/2935))
> fix(image-viewer): download img with params the file ext is lost

- CHANGELOG.md
- package.json
> release: 1.3.6

- src/drawer/drawer.tsx
#2947
- fix(Drawer): 打开抽屉后，无法直接摁 `ESC` 退出，必须先点击抽屉，才可关闭 ([issue #2947](https://github.com/Tencent/tdesign-vue-next/issues/2947))
> fix(Drawer): esc exit

- src/color-picker/color-picker.en-US.md
- src/color-picker/color-picker.md
- src/color-picker/panel/format/index.tsx
- src/color-picker/panel/index.tsx
- src/color-picker/type.ts
- https://github.com/Tencent/tdesign-vue-next/issues/2904
- https://github.com/Tencent/tdesign-vue-next/issues/2903
- https://github.com/Tencent/tdesign-vue/issues/2498
- fix(ColorPicker): 初始化为渐变模式时 支持空字符串作为初始值
- fix(ColorPicker): 修复 `recentColors` 等字段的类型问题
- fix(ColorPicker): 修复内部下拉选项未透传 `popupProps` 的缺陷
> fix(color-picker): gradient mode support empty string

- src/table/hooks/useSorter.tsx
closed #3021
- fix(Table): 修复启用 `multipleSort`，非受控用法不工作([issue #3021](https://github.com/Tencent/tdesign-vue-next/issues/3021
))
> fix(table): 启用multipleSort，非受控用法不工作

- src/calendar/calendar.tsx
- src/calendar/hook/useState.ts
https://github.com/Tencent/tdesign-vue-next/issues/3035
After fix：
- fix(Calendar): 修复返回`今天/本月`，自定义日期的实际选择范围与定义不符([issue #3035](https://github.com/Tencent/tdesign-vue-next/issues/3035))
> fix(calendar): custom range select wrong

- src/range-input/range-input.tsx
- fix(DateRangePicker): 修复`suffix` `prefix` 无法响应数据变化渲染的问题
> fix(range-input): prefix and suffix content reactive render

- src/menu/menu-item-props.ts
- src/menu/menu-item.tsx
- src/menu/type.ts
样式修改已在common仓库提PR https://github.com/Tencent/tdesign-common/pull/1506
vue2仓库的PR https://github.com/Tencent/tdesign-vue/pull/2565
API平台录入PR https://github.com/TDesignOteam/tdesign-api/pull/164
- feat(MenuItem): 新增 `API: routerLink`，可指定菜单项渲染为 `Router` 控制跳转的 `a` 标签
- fix(MenuItem): 渲染为 `a` 标签时，`a` 标签覆盖范围扩大至整个菜单项，而不是只有文本部分
- fix(MenuItem): 修复当菜单项渲染 `a` 标签并且 `menu` 在 `collapsed` 状态时，菜单项内容区隐藏导致无法点击跳转的问题
- fix(MenuItem): 修复渲染为 `a` 标签时并在 `popup` 出现时，文本对齐与正常菜单项的位置不一致的问题
> feat(MenuItem): 修正菜单项为a标签时的跳转行为与渲染样式

- src/table/hooks/usePagination.tsx
fix: #3038
- fix(Table): 修复主动触发页码更新时表格序号列没有重新计算([issue #3038](https://github.com/Tencent/tdesign-vue-next/issues/3038))
> fix: #3038

- CHANGELOG.md
- package.json
> docs: release 1.3.11

- src/rate/rate.tsx
closed #2891
#2891 
- fix(Tate): 修复 `rate` 在开启文字显示与半星时，`tooltip` 显示异常的问题([issue #2891](https://github.com/Tencent/tdesign-vue-next/issues/2891))
> fix(rate): 修复 rate 在开启文字显示与半星时，tooltip 显示异常的问题

- src/input-number/useInputNumber.tsx
fix #2900 
- fix(InputNumber): 修复 `input-number` 内容为空时，值为 `undefined` 的问题，应当为 `null` ([issue #2900](https://github.com/Tencent/tdesign-vue-next/issues/2900))
> fix: 修复 input number 内容为空时，值为 undefined 的问题，应当为 null

- src/input/useInput.ts
- src/select/select.tsx
#2970 
- fix(Select): 修复 `autofocus` 不生效的问题([issue #2970](https://github.com/Tencent/tdesign-vue-next/issues/2970))
> fix: 修复 select autofocus 不生效的问题

- src/table/hooks/useEditableRow.ts
- fix(Table): 修复可编辑单元格场景，执行 `validateTableData` 函数后，没有触发事件 `onValidate` 问题
> fix(table): validateTableData do not trigger onValidate event

- src/tree/useTree.tsx
closed #3110
[#3110](https://github.com/Tencent/tdesign-vue-next/issues/3110)
1. 目前actived的值与实际情况相反。
2. 解决方案：在传入ctx的时候做一遍判断，看当前节点是否在actived的数组中，然后调整ctx.node.actived的值。
- fix(tree): 修复Tree Events - active 事件中，参数 context 中 actived 值和实际状态相反
> fix(tree): 修复Tree active事件中actived值相反(#3110)

- src/hooks/index.ts
- src/image-viewer/base/ImageItem.tsx
- src/image-viewer/base/ImageViewerUtils.tsx
- src/image/__tests__/vitest-image.test.jsx
- src/image/image.tsx
- src/table/hooks/useFixed.ts
- src/table/tbody.tsx
- fix(Table): 固定表头固定列空数据场景，“暂无数据”错位显示问题，[issue#3166](https://github.com/Tencent/tdesign-vue-next/issues/3166)
- refactor(Image): 代码整理
> [fix] table empty elements does not displayed center

- src/table/_example/pagination-ajax.vue
- src/table/hooks/usePagination.tsx
closed #3172
https://github.com/Tencent/tdesign-vue-next/issues/3172
- fix(table): 远程分页使用非受控用法时，切换超过 `defaultPageSize` 的页面大小数据展示不全
> fix(table): 远程分页使用非受控用法时，切换超过defaultPageSize的页面大小数据展示不全

- CHANGELOG.md
- package.json
> docs: release 1.4.2

- src/tree-select/tree-select.tsx
closed #3216
#3216 
- fix(TreeSelect): 自定义显示 `tag` 关闭异常 ([issue #3216](https://github.com/Tencent/tdesign-vue-next/issues/3216))
> fix(tree-select): 自定义显示tag关闭异常

- CHANGELOG.md
- package.json
> docs: release 1.5.0

- src/image-viewer/base/ImageItem.tsx
- src/image-viewer/base/ImageViewerUtils.tsx
closed #3171
#3171
- fix(ImageViewer): 修复图片浏览的全局配置无效([issue #3171](https://github.com/Tencent/tdesign-vue-next/issues/3171))
> fix(ImageViewer): 使用全局配置

- src/upload/themes/dragger-file.tsx
- src/upload/themes/multiple-flow-list.tsx
- src/upload/themes/normal-file.tsx
close: #3239
部分主题内渲染百分比时未判断`showUploadProgress`
- fix(Upload): 修复`Upload`组件`showUploadProgress`属性不生效([issue #3239](https://github.com/Tencent/tdesign-vue-next/issues/3239))
> fix(Upload): fix `showUploadProgress` invalid

- src/menu/head-menu.tsx
- src/menu/v-menu.ts
- https://github.com/Tencent/tdesign-vue-next/issues/3261
- https://github.com/Tencent/tdesign-vue-next/issues/3256
- fix(Menu): 修复普通双层菜单模式路由跳转功能失效的问题([issue #3261](https://github.com/Tencent/tdesign-vue-next/issues/3261))
- fix(Menu): 修复普通双层菜单 `click` 事件丢失的问题([issue #3256](https://github.com/Tencent/tdesign-vue-next/issues/3256))
> fix(menu): fix normal submenu item event missing

- CHANGELOG.md
- package.json
> docs: release 1.5.2

- src/upload/themes/dragger-file.tsx
- src/upload/themes/image-card.tsx
close: #3273
根据PR https://github.com/Tencent/tdesign-vue-next/pull/3136 的修改
之后非自动上传的图片求`file.url`的逻辑放到了`image`组件, 所以我们渲染图片时不再需要 url 存在，根据 PR3136，应该传`file.raw`属性给`image`，由`image`组件求 url 然后渲染。
- fix(upload): 修复非自动上传时图片缩略图不显示
> fix(upload): fix thumbnails don't show

- src/tabs/tabs.tsx
#3281
- fix(tabs): 修复在封装`tabs`组件时内部定义了`slot`后使用`v-for`不渲染的问题([issue #3281](https://github.com/Tencent/tdesign-vue-next/issues/3281))
> fix(tabs): fix tab-panel render error when use v-for in slot

- src/form/form.tsx
form-item 中的 getFormItemClassName 函数会在组件名称后面加两个下划线，FORM_ITEM_CLASS_PREFIX 中应该去掉下划线，否则会导致生成的 className 多两个下划线.
同时 scrollTo 参数也不应该加.前缀，因为方法里面调用的是getElementsByClassName
- fix(form): 修复 form 组件 scrollToFirstError 无效的问题
> fix(form): 修复 form 组件 scrollToFirstError 无效的问题

- src/dialog/_example/base.vue
- src/dialog/plugin.tsx
- src/input/useInputWidth.ts
- fix(Input): 修复默认不显示，满足某种条件后才显示的场景下，自动宽度计算错误问题，[issue#3266](https://github.com/Tencent/tdesign-vue-next/issues/3266)，[issue#3092](https://github.com/Tencent/tdesign-vue-next/issues/3092)
- fix(Table): 修复 Dialog 弹框中打开表格，表格中分页组件信息出现超出省略问题，[issue#3266](https://github.com/Tencent/tdesign-vue-next/issues/3266)，[issue#3092](https://github.com/Tencent/tdesign-vue-next/issues/3092)
- fix(Pagination): 修复 Dialog 弹框中打开表格，分页组件信息出现超出省略问题，[issue#3266](https://github.com/Tencent/tdesign-vue-next/issues/3266)，[issue#3092](https://github.com/Tencent/tdesign-vue-next/issues/3092)
- fix(Dialog): 修复 Dialog 弹框中打开表格，分页组件信息出现超出省略问题，[issue#3266](https://github.com/Tencent/tdesign-vue-next/issues/3266)，[issue#3092](https://github.com/Tencent/tdesign-vue-next/issues/3092)
- fix(Dialog): 类型问题，修复 DialogPlugin({ …
> [Input][Pagination][Select][Table] fix auto width computed error

- src/dialog/_example/async.vue
- src/dialog/dialog.md
- src/dialog/hooks.tsx
- fix(Dialog): 修复没有定义确认按钮属性场景时（即没有设置 confirmBtn），`confirmLoading` 无效问题
> fix(dialog): support confirmLoading

- src/form/form-item.tsx
`Form` 组件的 `statusIcon` 为函数或插槽时，未传入 `props: TdFormItemProps` 参数，与 TS 类型声明的不一致
- fix(Form): 修复 `statusIcon` 为函数或插槽时，参数为空的问题
> fix(Form): 修复 Form.statusIcon 为函数或插槽时，参数为空的问题

- CHANGELOG.md
- package.json
> docs: release 1.6.0

- CHANGELOG.md
- package.json
> chore: release 1.6.2

- src/tree/hooks/useTreeNodes.tsx
#3474 
原因为当`node`的`value`为`0`时，使用`map.get()`后得到的值为`0`，导致`if`的判断不正确。
- fix(Tree): 修复当 `node` 的 `value` 为 `0` 时不会渲染([issue #3474](https://github.com/Tencent/tdesign-vue-next/issues/3474))
> fix(tree): fix tree-node render error when value is 0

- src/pagination/pagination.tsx
#3483 
当前页会在切换分页数量时被动更改，此时应只`update:modelValue`而不触发`onCurrentChange`事件
- fix(pagination): 修复当前页在被动更改时触发 `onCurrentChange` 事件([issue #3483](https://github.com/Tencent/tdesign-vue-next/issues/3483))
> fix(pagination): fix incorrect trigger onCurrentChange event

- src/table/primary-table.tsx
在多级表头的场景下，使用动态的列配置的时候，只能去配置到叶子节点的列名去展示相应的列，没办法通过配置一个父级的表头列，来指定之下的所有子列显示，批量地配置显示和隐藏不方便。
在判断列是否展示的时候，如果一个拥有 children 的列被配置在 displayColumns 中，透传它的显示属性，以下所有的子列都进行展示。
- feat(Table): 多级表头下，动态列配置支持指定父级列以展示其下的所有子列
> feat(table): 多级表头下,动态列配置支持指定父级列以展示其下的所有子列

- src/upload/hooks/useUpload.ts
- src/upload/props.ts
- src/upload/type.ts
- src/upload/upload.en-US.md
- src/upload/upload.md
- https://github.com/Tencent/tdesign-vue-next/issues/3279
修复当upload为手动上传时，进度无法显示的问题，代码中只处理了自动上传的情况，现修复支持手动上传的进度显示。
https://github.com/Tencent/tdesign-vue-next/issues/3279
- fix(Upload): 修复当upload为手动上传时，进度无法显示的问题.
> fix(upload): 修复当upload为手动上传时，进度无法显示的问题

- CHANGELOG.md
- package.json
> docs: release 1.6.7

- src/table/hooks/useFixed.ts
当列显示或隐藏时，通过保存的表头宽度计算原宽度时，会重复计算多级表头的宽度，导致隐藏列后表头宽度过长
- fix(Table): 多级表头 + 列宽调整场景，修正动态列表头宽度计算错误的问题
> fix: 🐛 修正计算总列宽时,重复叠加计算子表头宽度的问题

- src/table/hooks/useColumnController.tsx
- src/table/hooks/useFixed.ts
在提供列配置选项时,默认只提供叶子列作为配置选项,作为最细粒度配置的方式
- fix(Table): 在提供列配置选项时,默认只提供叶子列作为配置选项,作为最细粒度配置的方式
> fix(table): 在提供列配置选项时,默认只提供叶子列作为配置选项,作为最细粒度配置的方式

- src/table/base-table.tsx
- src/table/hooks/useColumnController.tsx
- src/table/hooks/useFixed.ts
修正动态列变化时,表头的宽度和高度更新问
- fix(Table): 修正动态列变化时，表头过小或表头高度更新错误导致意外的滚动条出现的问题
> fix(table): 修正动态列变化时,表头的宽度和高度更新问题

- src/checkbox/hooks/useKeyboardEvent.ts
- src/radio/useKeyboard.ts
https://github.com/Tencent/tdesign-vue-next/issues/3598
空格space, 删除backspace ,正则判断space，触发删除键误判断是空格
- fix(Radio): `useKeyboard` 通过正则匹配space,误判断删除键(backspace)是空格键(space)
- fix(Checkout): `useKeyboardEvent ` 通过正则匹配space,误判断删除键(backspace)是空格键(space)
> fix: 通过正则匹配space,误判断删除键(backspace)是空格键(space)

- src/breadcrumb/breadcrumb-item.tsx
[#3634](https://github.com/Tencent/tdesign-vue-next/issues/3634)
与a标签target属性的_blank选项表现一致
- fix(BreadcrumbItem): 修复breadcrumb-item组件target属性为'_blank'时没有在新标签页打开
> fix(BreadcrumbItem): target equals Invalid when '_blank'

- src/statistic/statistic.tsx
[(2931) [https://github.com/Tencent/tdesign-vue/issues/2931]](https://github.com/Tencent/tdesign-vue/issues/2931)
未设置 `decimalPlaces` 小数保留位数时，`tween` 更新数值时精度很高导致数字动画变化时很长。
1. 根据用户传入的 `value` 得到默认小数点位数，动画进行时保持这个小数点位数更新。
-  fix(Statistic): 修复动画缺失默认位数问题([issue #2931](https://github.com/Tencent/tdesign-vue/issues/2931))
> fix(statistic): fix with missing default precision in animation

- package.json
vue 3.3.10 导致 `npm run lint:tsc`报错，保证ci正常运行临时固定vue 3.3.9版本
错误信息暂时找不出是哪个地方引起的
```
> npm run lint:tsc && eslint --ext .vue,.js,.ts,.tsx ./src --max-warnings 0 --cache
> tdesign-vue-next@1.[7](https://github.com/Tencent/tdesign-vue-next/actions/runs/7096111038/job/19314098437?pr=3688#step:6:8).0 lint:tsc
> tsc --emitDeclarationOnly
/home/runner/work/tdesign-vue-next/tdesign-vue-next/node_modules/typescript/lib/tsc.js:9[8](https://github.com/Tencent/tdesign-vue-next/actions/runs/7096111038/job/19314098437?pr=3688#step:6:9)43[9](https://github.com/Tencent/tdesign-vue-next/actions/runs/7096111038/job/19314098437?pr=3688#step:6:10)
throw e;
^
Error: Debug Failure. No error for last overload signature
at resolveCall (/home/runner/work/tdesign-vue-next/tdesign-vue-next/node_modules/typescript/lib/t …
```
> chore: ci lint 报错

- src/tree/__tests__/activable.test.jsx
- src/tree/__tests__/adapt.js
- src/tree/__tests__/checkable.test.jsx
- src/tree/__tests__/expand.test.jsx
- src/tree/hooks/useTreeAction.ts
- src/tree/hooks/useTreeStore.ts
https://github.com/Tencent/tdesign-vue-next/issues/3670
变更了 value, expanded, actived 属性的监听方式
- fix(tree): value, active, expanded 属性, 支持数组操作触发视图变更
> fix(tree): tree 组件, value, active, expanded 属性, 支持数组操作触发视图变更

- src/select/_example/remote-search.vue
- src/select/hooks/useKeyboardControl.ts
- src/select/hooks/useSelectOptions.ts
- src/select/select-panel.tsx
- src/select/select.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/3605
- https://github.com/Tencent/tdesign-vue-next/issues/2801
- fix(Select): 远程搜索不再进行本地过滤，支持远程对选项 `trim` 或者额外处理的场景([issue #3605](https://github.com/Tencent/tdesign-vue-next/issues/3605))([issue #2801](https://github.com/Tencent/tdesign-vue-next/issues/2801))
- fix(Select): 修复非虚拟滚动场景下，无法键盘回车键直接选中过滤后的选项的缺陷
> fix(Select): pick correct option by keyboard enter

- CHANGELOG.md
- package.json
- src/tabs/tab-nav.tsx
> docs: release 1.7.1

- src/table/hooks/useColumnController.tsx
- fix(Table): 修复 `column-controller-visible-change` 事件参数 `trigger` 值不正确问题，[issue#3706](https://github.com/Tencent/tdesign-vue-next/issues/3706)
> fix(table): params of onColumnControllerVisibleChange `trigger` value is error

- src/input-number/useInputNumber.tsx
https://github.com/Tencent/tdesign-vue-next/issues/3721
当 :max="100" :allowInputOverLimit="false" :onBlur="handleBlur" 输入超过100的数字无法触发 onBlur 事件
- fix(InputNumber ): allowInputOverLimit为false时，数字超过最大值onBlur不触发
> fix: allowInputOverLimit为false时，数字超过最大值onBlur不触发

- src/date-picker/DateRangePicker.tsx
fix https://github.com/Tencent/tdesign-vue-next/issues/3683
- fix(DateRangePicker): 修复 `12` 月时选择同一个月内的日期后，第一次打开面板左右月份一样的问题([issue #3683](https://github.com/Tencent/tdesign-vue-next/issues/3683))
> fix(date-range-picker): 修复12月时选择同一个月内的日期后，第一次打开面板左右月份一样的问题

- src/table/hooks/useFixed.ts
affix 表头和表格宽度计算精度不统一，会导致出现预期外的滚动条，尝试fix
> fix: 🐛 修正表格精度,避免表头和表格出现精度误差因此预期外的滚动条

- src/dropdown/dropdown-menu.tsx
1. 跟进大部分用户反馈 不希望left direction的场景下将展开箭头与文案位置互换 去掉这部分特殊处理
处理前
处理后
2. 更新common
- feat(Dropdown): 移除对 `left` 的 `item` 样式特殊处理
- fix(DatePicker): 修复日期选择禁用后，后缀图标颜色改变的问题 @HaixingOoO 
> feat(dropdown): remove dropdown left special style

- src/radio/__tests__/vitest-radio.test.jsx
- src/radio/radio.tsx
fix #3781 
- fix(Radio): 处理选中状态也会触发 `change` 事件的问题
> fix(radio): the checked state also triggers the change event

- src/slider/_example/marks.vue
- src/slider/slider-button.tsx
- src/slider/slider.tsx
https://github.com/Tencent/tdesign-vue-next/issues/3772
- feat(slider): 点击游标需移动后 `mouseup` 时才触发 `changeEnd` 事件
- feat(slider): 点击刻度时触发 `changeEnd` 事件
> feat(slider): changeEnd 事件在点击刻度时触发以及点击游标需移动后 mouseup 才会触发changeEnd

- src/form/__tests__/__snapshots__/form.test.jsx.snap
- src/form/form-item.tsx
目前在校验信息超长时省略，无法查看完整内容，增加title以最小方案解决此问题
- feat(form): 为Form Item校验信息增加title属性，用于鼠标停留时展示完整信息
> feat(form): form-item extra增加title attribute显示超长内容

- src/image-viewer/hooks.ts
- src/image-viewer/image-viewer.en-US.md
- src/image-viewer/image-viewer.md
- src/image-viewer/image-viewer.tsx
- src/image-viewer/props.ts
- src/image-viewer/type.ts
> feat(ImageViewer): 新增默认缩放比例

- src/table/hooks/useDragSort.ts
- src/table/primary-table.tsx
可复现问题代码：https://stackblitz.com/edit/k63jyd?file=package.json,src%2Fdemo.vue
操作步骤：交换任意两行，“点击加载更多” 变到第一行，不符合预期
修复效果如下：
https://github.com/Tencent/tdesign-vue-next/assets/11605702/164a045b-be06-40c9-bcdd-c8aafd5e353e
- fix(Table): 修复行拖拽排序场景，异步加载行会变到第一行问题
> fix(table): drag sort with asyncLoading would make asyncLoading to be the first row line

- src/radio/props.ts
- src/radio/radio.en-US.md
- src/radio/radio.md
- src/radio/radio.tsx
- src/radio/type.ts
fix #3811 
- feat(Radio): 新增 `readonly` 属性
> feat(radio): enable readonly props

- src/table/hooks/useDragSort.ts
https://github.com/Tencent/tdesign-vue-next/issues/2847
https://github.com/Tencent/tdesign-vue-next/issues/3567
1.sortablejs拖拽会操作原生DOM，导致Vue的虚拟DOM监听异常，和数据层渲染不一致。
2.移除使用sortable实例直接操作DOM的代码。
3.参考[vue.draggable.next](https://github.com/SortableJS/vue.draggable.next/)，通过拖拽后手动还原DOM位置，保证虚拟DOM和DOM的一致性。
- fix(table): 修复sortablejs操作DOM后对虚拟DOM产生的副作用。
> fix(table): The effects on Virtual DOM after sortablejs operates DOM.

- src/drawer/drawer.tsx
fix #3835 
- fix(Drawer): `visible` 为 `false` 时，按 `esc` 会触发 `onEscKeydown` 和 `onCancel` 事件
> fix(drawer): unexpected event triggering

- src/tag-input/useTagList.tsx
- fix(tag-input): 修复 `size`属性对 `collapsedItems` 不生效导致样式不美观的问题
> fix(tag-input): 修复taginput中size对默认collapsedItems不生效的问题

- src/drawer/drawer.tsx
最新版本中开启非全局closeOnEscKeydown后会导致任意按键关闭drawer
原有逻辑下 组件的属性closeOnEscKeydown 为 true时, 判断中 ?? 运算直接命中true 跳过后续的判断
调整判断逻辑，先进行当前组件和全局的closeOnEscKeydown属性判断，再判断按键以及显示状态
> fix(Drawer):修复closeOnEscKeydown 开启时任意按键都会触发Drawer问题

- CHANGELOG.md
- package.json
> docs: release 1.8.1

- src/select/option.tsx
select createAble开启后， 选中没有触发change事件问题
点击创建的选项后，将调用的handleValueChange参数拷贝一份，同时push创建的值
- fix(Select): 修复select createAble 选中没有触发change事件问题
> fix: 🐛 修复select createAble 选中没有触发change事件问题

- src/form/form-item.tsx
- src/utils/string-template.ts
- https://github.com/Tencent/tdesign-vue-next/issues/3458
经排查是nuxt nitro编译问题，由lodash的template函数触发，该功能只在form-item中使用了变量替换功能，因此采用正则替换的方式替代该函数。
- fix(nuxt): 修复在`nuxt`中使用 `Form` 组件无法正常构建的问题
> fix(form): 替换lodash的template功能,避免由此导致的nuxt编译异常

- src/hooks/useVirtualScrollNew.ts
虚拟滚动场景下，数据长度变化时，需要裁剪缓存的高度数组，避免计算出错误的滚动总高度
复现和验证 demo 如下
https://stackblitz.com/edit/a2afwr?file=package.json,src%2Fdemo.vue
> [Table] 修正数据长度变化时，虚拟滚动表格总高度计算错误的问题

- src/input/useInput.ts
fix #3963
fix #3903
fix #3639
- fix(input): 修复 `hover` 时键盘操作无法触发 `blur` 事件。
> fix(input): `blur` cannot be triggered when input is hovered (#3963)

- package.json
- src/loading/plugin.tsx
* #4037 
1. 实现 `LoadingPlugin` 的 `preventScrollThrough` 逻辑。
2. 处理 `fullscreen = true` 时 `attach` 固定为 `body` 标签，保持和 `loading.tsx` 逻辑一致。
- fix(loading): 修复 `LoadingPlugin` 调用时 `preventScrollThrough` 参数无效。
> fix(loading): `preventScrollThrough` has no effect when using `LoadingPlugin` (#4037)

- src/loading/index.ts
* #4041 
背景：
`unplugin-vue-components` 中 [`TDesignResolver`](https://github.com/unplugin/unplugin-vue-components/blob/aeaf51d422da1286a204581ebd9d11d5e8c0361f/src/core/resolvers/tdesign.ts) 按需引入缺少处理 `directive`，`v-loading` 指令不工作。
方案：
默认将 `vLoading` 导出用于 `unplugin-vue-components` 后续增加 `directive` 逻辑。
tdesign-vue 已同步提交 https://github.com/Tencent/tdesign-vue/pull/3120
> fix(loading): export directive alias

- package.json
- src/date-picker/DatePicker.tsx
- https://github.com/Tencent/tdesign-vue/issues/3068
- formatDate 方法需要Date对象来计算，部分场景下，value.value为普通字符串或时间戳，无法得出正确的结果，需统一转为Date再进行计算
- 相关PR https://github.com/Tencent/tdesign-common/pull/1746
- fix(DatePicker): 修复 `format` 与 `valueType` 不一致的场景下计算错误的问题
- chore: remove duplicate dependency delcaration
> fix(Datepicker): value display wrong with special format

- src/date-picker/DatePicker.tsx
对于 Date 类型值，不再进行 parse，避免 dayjs 的异常处理
- fix(DatePicker): 对于 `valueType = 'Date'` 不进行初始化的 parse
> fix(DatePicker): fix over parse when value type is Date

- src/textarea/props.ts
- src/textarea/textarea.en-US.md
- src/textarea/textarea.md
- src/textarea/textarea.tsx
- src/textarea/type.ts
#4084
- feat(Textarea): 新增 `allow-input-over-max` 属性
- feat(Textarea): 新增`onValidate` 事件
> feat(textarea): enable props allow-input-over-max

- src/descriptions/__tests__/index.test.jsx
- src/descriptions/utils/index.ts
- fix(Descriptions): check empty for items label and content
> fix(descriptions): check empty for item label and content

- src/textarea/calcTextareaHeight.ts
* #4103 
这个 bug 应该是 Firefox 的问题。
Firefox 对 `textarea` 设置 overflow: hidden 后首次获取到的 `scrollHeight` 是错误的，导致初始化的容器高度是错误的。
我尝试将 `overflow: hidden` 去掉，但是会影响 Chrome 的样式，后面改成 `overflow-y: hidden` 后自测暂没发现问题。
或许跟下面这个远古 bug 有关。
https://bugzilla.mozilla.org/show_bug.cgi?id=33654
- fix(Textarea): `autosize` 在 `Firefox` 中不生效。
> fix(textarea): `autosize` doesn't work in Firefox (#4103)

- src/upload/upload.tsx
#4124 
- feat(Upload): 新增 `trigger-button-props` 中 `default` 和 `content` 参数透传
> feat(upload): enable default and content parameters in trigger-button-props

- src/cascader/core/effect.ts
closed #2778
#2778 
修复Cascader 多选状态下 删除选项时触发多次change事件的问题
去除没必要的setValue
fix(Cascader): 修复 `cascader` 多选状态下 删除选项时触发多次 `change` 事件的问题
> fix(cascader): 修复Cascader 多选状态下 删除选项时触发多次change事件的问题

- site/src/components/base-usage.vue
doc-usage 区域指定 `height: 100%` 后，可以使 slider vertical 布局显示正常（slider vertical 布局时 height 通过百分比获取，需要外部容器指定 height 高度），但是其他组件由于高度较大，溢出部分被截断不可见。
```css
align-items: safe center;
justify-content: safe center;
```
通过 safe 属性值可以解决上述问题，但兼容性还不够友好，Chrome 115 开始支持（见：https://www.w3.org/TR/css-align-3/#overflow-values  https://caniuse.com/?search=justify-content）
故，对于 slider demo 显式指定高度，其他组件设为 auto 自动获取
- fix: 修复 demo 展示不全
> fix: fix incomplete demo presentation

- src/time-picker/panel/time-picker-panel.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/4170
- feat(TimePicker): 此刻按钮在设置`preset` API 时不再展示
> feat(TimePicker): hide now button when presets is set

- src/cascader/cascader.tsx
- src/select-input/interface.ts
- src/select-input/props.ts
- src/select-input/select-input.en-US.md
- src/select-input/select-input.md
- src/select-input/type.ts
- src/select-input/useSingle.tsx
prefixIcon和suffixIcon的slot不起作用
详情见 [#4225 ](https://github.com/Tencent/tdesign-vue-next/issues/4225)
由于cascader过去的api并未传入suffix，suffixIcon，prefixIcon，select-input未有prefixIcon这个api，因此做了对应修改，并且更新了select-input的文档
- fix(Cascader): 修复`prefixIcon`、`suffix`和`suffixIcon`的 slot 功能缺失的问题
- feat(SelectInput): 新增`size`属性
> fix(cascader): fix lost prefixIcon and suffixIcon

- src/date-picker/DateRangePicker.tsx
- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/utils.ts
优化前，选择后左侧区间大于右侧区间只会同步右侧区间
优化后，选择后左侧区间大于右侧区间，默认调整为左侧区间始终比右侧区间小1，增加可操作范围
切换年且只有年选择器：
1. 点击左侧，且左侧大于右侧，右侧要自动加1；
2. 点击右侧，且右侧小于左侧，左侧要自动减1；
切换年且要有月份选择器：
1. 点击左侧，且左侧大于右侧，右侧要自动切换至左侧年+月份 加1；
1. 点击右侧，且右侧小于左侧，左侧要自动切换至右侧年+月份 减1；
切换月份选择器：
1. 点击左侧，且左侧大于右侧，右侧要自动切换至左侧年+月份 加1；
1. 点击右侧，且右侧小于左侧，左侧要自动切换至右侧年+月份 减1；
- feat(DatePicker): 优化日期区间选择器头部区间的变化逻辑，选择后左侧区间大于右侧区间，则默认调整为左侧区间始终比右侧区间小 1
> feat(DatePicker): optimize range picker panel header click logic

- src/dropdown/dropdown.tsx
#4286 
As the issue mentioned, change it to ` (delay[1] ?? delay[0]) + 10;`
- fix(Dropdown): fix the ?? syntax error
> fix(dropdown): fix the ?? syntax error

- src/cascader/core/effect.ts
[vue2#3091 
](https://github.com/Tencent/tdesign-vue/issues/3091)
- fix(cascader): 无children选项点击时不会显示之前的列表
> fix(cascader): hide children panel when toggle the node without children

- src/select/select.tsx
#4283
键盘上下键选中选项通过 onEnter 事件获取的context.value 错误，是因为当按下Enter按键时，会先触发onEnter回调函数，再触发useKeyboardControl中的handleKeyDown对应的Enter事件，导致先执行回调，再修改数据。目的就是要改成先触发Enter事件再触发onEnter回调函数，目前考虑两种方法，第一种使用setTimeout让onEnter回调函数事件缓于Enter事件，第二种是根据hoverIndex和innerPopupVisible判断当处于打开并且选中状态时按下Enter案件不触发onEnter，而是通过handleKeyDown对应的Enter事件进行触发对应的回调函数，第一种要用到setTimeout，第二种要用到nextTick，这里考虑到简单的变动选择第一种方案
- fix(Select): 修复键盘上下键选中选项后 onEnter 事件获取的context.value 错误的问题
> fix(select): fix onEnter context.value error when using keyboard to manipulate

- src/table/base-table.tsx
- src/table/hooks/useFixed.ts
复现demo: https://stackblitz.com/edit/vrnfnd?file=package.json,src%2Fdemo.vue
当固定表头和 tableLayout:auto 搭配使用时，在列宽初始化和变化的场景，同步列宽到 thWidthList 中，以便 affix Header 的渲染可以获得与表格一致的列宽
- fix(Table): 修正 tableLayout: auto 和 固定表头搭配使用的列宽不同步问题
> fix(Table): fix column width not being in sync when using auto layout and fixed table headers

- src/select/__tests__/index.test.jsx
- src/select/hooks/useSelectOptions.ts
- #4317
通过group获取option时没有使用getChildComponentSlots来进行获取，而是默认认为是一个数组，没有处理不同的情况，导致发生问题，已经修改为getChildComponentSlots
- fix(Select): 修复`Option`在`OptionGroup`中必须使用 `v-for` 才可以使用的缺陷
> fix(select): fix Option in OptionGroup must be render in v-for

- src/table/ellipsis.tsx
以省略号表示的标志值。TSX不再需要重置鼠标离开事件，因为它会导致不正确的行为。
closed #4342
#4342
- fix(table): 删除 ellipsis.tsx 中不必要的标志重置
> fix(table): 删除ellipsis.tsx中不必要的标志重置

- src/dialog/__tests__/index.test.jsx
- src/dialog/dialog.en-US.md
- src/dialog/dialog.md
- src/dialog/dialog.tsx
- src/dialog/props.ts
- src/dialog/type.ts
- https://github.com/Tencent/tdesign-vue-next/issues/4300
- feat(Dialog): 新增 `dialogStyle` 和 `dialogClassName` API，作用于弹窗本身，方便对弹窗本身样式进行调整
> feat(dialog): add dialogStyle and dialogClassName API

- src/tag-input/props.ts
- src/tag-input/tag-input.en-US.md
- src/tag-input/tag-input.md
- src/tag-input/tag-input.tsx
- src/tag-input/useTagList.tsx
- 将 disabled 的默认值设置为undefined，以允许正确使用基于组件状态的条件呈现。
- 重构标签输入。tsx和useTagList。tsx文件来使用useDisabled钩子并删除冗余的禁用状态处理。
BREAKING CHANGE: disabled 现在默认为undefined而不是false，这可能会影响依赖先前默认行为的消费者
closed #4352
#4352
- fix(TagInput): 修复 `Form` 组件 `disabled` 属性无法影响到 `TagInput` 组件
> fix(tag-input): form 组件的 disabled 属性无法影响到 TagInput 组件

- src/form/form.en-US.md
- src/form/form.md
- src/tag-input/props.ts
- src/tag-input/tag-input.en-US.md
- src/tag-input/tag-input.md
- src/tag-input/tag-input.tsx
- src/tag-input/useTagList.tsx
- 修改 TagInput 组件 props 中 readonly 属性未 undefined
- 修改 useTagList.tsx 只读状态的获取方式，使用 useReadonly Hook 获取
- 修改 tag-input.tsx 只读状态的获取方式，使用 useReadonly Hook 获取
- feat(Form): 支持通过表单的`readonly`属性影响`TagInput`组件
> feat(Form): readonly API supports tag-input

- src/tree-select/tree-select.tsx
- feat(TreeSelect): `valueDisplay` 回调整个节点信息，用于输入框的回调展示
> fix(TreeSelect): valueDisplay return whole node info

- src/dialog/props.ts
- #4400
- https://github.com/Tencent/tdesign-vue-next/issues/3919
- fix(Dialog): 修复 `cancelBtn` 和 `confirmBtn` 设置为`null` 的类型问题
> fix(dialog): add missing null type

- src/pagination/pagination.tsx
- #4430
表格改变每页行数时，@page-change事件参数不正确是因为在pageSize发生改变且会改变目前current值时，触发的handlePageChange会先执行setInnerPageSize，如果没有对onPageSize进行处理，会无法更新pageSize的值，而后触发的toPage函数获取pageInfo时，会尝试从props中进行获取，这就会导致获取不到最新的pageSize，从而引发bug
这里发现原来的isTriggerChange仅在上述情况下会使用，所以将其改为了pageInfo用于直接传入数据，避免了从props中无法出现最新值的问题
- fix(Pagination): 修复`pagination`在`pageSize`改变时`onChange`无法获取最新pageSize的问题
> fix(pagination): fix pageSize param when page change

- src/radio/constants.ts
- src/radio/radio-group-props.ts
- src/radio/radio.en-US.md
- src/radio/radio.md
- src/radio/radio.tsx
- src/radio/type.ts
https://github.com/Tencent/tdesign-vue-next/issues/4350
- feat(Radio): `RadioGroup` change事件回调添加`name`属性
> feat(radio): radioGroup组件change事件添加name属性

- src/button/button.en-US.md
- src/button/button.md
- src/button/props.ts
- src/button/type.ts
- src/form/form.en-US.md
- src/form/form.md
- src/form/props.ts
- src/form/type.ts
- src/table/primary-table.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/4448
- feat(Form): 新增`id` API，表单原生的 id 属性，支持用于配合非表单内的按钮通过 form 属性来触发表单事件
- feat(Button): 新增`form` API，原生的 form 属性，支持用于通过 form 属性触发对应 id 的 form 的表单事件
> feat(form): support form id and button form API

- src/menu/menu.en-US.md
- src/menu/menu.md
- https://github.com/TDesignOteam/tdesign-api/pull/164
- #3057 
- #4542 
貌似组件更新了，文档没更新
- docs(Menu): 更新关于`MenuItem`的 `routerLink`的相关文档
> docs(menu): update docs about `routerLink`

- src/cascader/cascader.en-US.md
- src/cascader/cascader.md
- src/cascader/cascader.tsx
- src/cascader/props.ts
- src/cascader/type.ts
- feat(Cascader): 新增 `panelTopContent` 和 `panelBottomContent` API
> feat(cascader): support panel content

- src/table/ellipsis.tsx
- fix(Table): 修复开启`ellipsis`配置的节点因为状态更新问题导致部分场景分页切换时存在异常的问题
> fix(table): fix ellipsis status

- src/tree-select/tree-select.tsx
- src/tree/hooks/useRenderLabel.tsx
- fix(TreeSelect): 修复多选状态下默认点击父节点选项的行为为选中
- fix(Tree): 修复多选下配置 `expandOnClickNode` 后没有正确生效的问题
> fix(tree-select): fix multiple select click parent node callback

- src/image-viewer/hooks.ts
- src/image-viewer/image-viewer.tsx
- style(ImageViewer): 优化图片查看器默认的缩放比例，减少滚轮缩放效果的闪烁感
> style(image-viewer): adjust the default zoom ratio of the image

- src/select-input/useSingle.tsx
- src/select/_example-ts/base.vue
- src/select/_example/base.vue
- src/select/helper.ts
- src/select/option.tsx
- src/select/select.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/4554
- fix(Select): 修复选项的title为空字符串或置空时的渲染效果
- fix(Select): 修复选中选项后没有正常触发`blur`事件的问题
> feat(Select): fix render result of empty string or null title of option

- src/rate/__tests__/index.test.jsx
- src/rate/_usage/props.json
- src/rate/props.ts
- src/rate/rate.en-US.md
- src/rate/rate.md
- src/rate/rate.tsx
- src/rate/type.ts
- 其他API文档改动系API平台携带，disabled 的变动为 form disabled 需要
- feat(Rate): 新增`clearable` API, 用于支持清空评分
> feat(Rate): support clearable API

- src/config-provider/useConfig.tsx
```html
<script>
const globalConfig = computed(() => {
return locale.value === "zh-CN" ? zhCN : enUS
})
</script>
<template>
<TConfigProvider :globalConfig="globalConfig">
<TAlert :max-line="2">
<-- ... !-->
</TAlert>
</TConfigProvider>
</template>
```
devtools查看 config-provider 中的globalConfig是具备响应式的
本地组件手动inject也是可以的，但是 TAlert 中的不会变
最终定位是computed返回的对象保持了引用：
https://github.com/Tencent/tdesign-vue-next/blob/ada18a13fcf3af25bfd1683d30457a334e2bf014/src/config-provider/useConfig.tsx#L70-L75
参考[useConfig](https://github.com/Tencent/tdesign-vue-next/blob/ada18a13fcf3af25bfd1683d30457a334e2bf014/src/config-provider/useConfig.tsx#L28) 本地node_modules手动修改测试可行：
```diff
-mergeWith(defaultData as unknown as GlobalConfigProvider, props.globalConfig),
+Object.assign({}, mergeWith(defaultData as unknown …
```
> fix(config-provider): computed globalConfig reactivity

- src/input-number/hooks/useInputNumber.tsx
fix #4657 
- fix(InputNumber): 禁用时焦点事件仍然会触发的问题
> fix(input-number): the focus event is still triggered when disabled

- src/table/_example/multi-header.vue
- src/table/thead.tsx
Added support for multi-header to ensure correct colspan calculation for child columns.
closed #4667
[#4667](https://github.com/Tencent/tdesign-vue-next/issues/4667) 
1. 多级表头下的表头通过colspan进行合并
2. 在`thead.tsx`下的`colspanSkipMap`函数下，增加`children`的处理逻辑
- fix(table): 多级表头下的通过colspan合并表头
> fix(table): resolve colspan handling for multi-header

- src/input/useInputWidth.ts
无
选择器自动宽度偶尔会失效，排查逻辑后发现此处不合理的地方，理论上应该用preInput的resize去更新input，否则若input不发生resize，将无法根据pre更新宽度，易出现于dom挂载后绑定到ref的时机不可知，修正该逻辑，不确定是否为问题成因，未能稳定复现该场景
> fix(input): autoWidth observe preInput dom instead of input dom

- CHANGELOG.md
- package.json
> docs: release 1.10.3

- src/input/input.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/4666
- fix(input): 修复`AutoWidth`状态下，使用中文输入法时，`InputPreValue`不会更新为输入值的问题
> fix(input): input AutoWidth the width(PreValue) does not respond when use Chinese input method

- src/tag-input/__tests__/index.test.jsx
- src/tag-input/useTagList.tsx
- fix(tag-input):修复在`readonly`模式下仍可以通过Backspace按键删除已选项的缺陷
> fix(tag-input): prevent backspace event in readonly mode

- script/generate-usage/config.js
- src/drawer/_usage/index.vue
* [[Drawer] 官网usage demo中开关header表现不符合预期 #4697](https://github.com/Tencent/tdesign-vue-next/issues/4697)
使用`header slot` 和 `boolean header` 组合用于区分 `header` 为开关时的区别
- fix(drawer): fix the issue where the header does not behave as expected
> fix(drawer): fix the issue in the demo where the "header" does not behave as expected

- src/input/useInputWidth.ts
getBoundingClientRect 会受到 scale 影响，在 dialog 等有时长的过渡动画下，获取到错误的宽度，引起自动宽度的错位
- fix(Input): 优化 scale 下的自动宽度错位的问题
> fix(Input): 优化 scale 下的自动宽度错位的问题

- src/cascader/core/effect.ts
- feat(Cascader): 单选模式下当`trigger`为`hover`时，选中选项后自动关闭面板
> feat(cascader): click item to close panel when trigger is hover

- src/swiper/swiper.tsx
[[Swiper] navigation切换轮播有bug #4648](https://github.com/Tencent/tdesign-vue-next/issues/4648)
背景：
当autoplay=false且当swiperItemLength=2时，会重复触发swiperTo方法
解决方案：
设置watch的props.current变化时，当props.autoplay为true才触发类型为“autoplay”的swiperTo事件。
- fix(swiper): swiper在autoplay=false时切换轮播bug
> fix(swiper): fix bug when autoplay is false 

- src/menu/menu-group.tsx
[导航菜单 分组 title 使用插槽无效 #4739](https://github.com/Tencent/tdesign-vue-next/issues/4739)
背景：menu-group 没有使用插槽
解决方案：添加 renderTNodeJSX(this, 'title', { silent: false })
- fix(menu): menu-group的title插槽无效
> fix(menu): fix menu-group title slot usage

- src/menu/menu-item.tsx
(https://github.com/Tencent/tdesign-vue-next/issues/4718)
感觉有点脏，如果可以的话最好有个统一的抽象惰性的方式。
- fix(menu): suppress warning if the project does not contain `vue-router`
> fix(menu): do not eagerly access `$router` in rendering

- src/cascader/components/Item.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/4721
- fix(Cascader): 修复当选项 `label` 非字符串时 `title` 渲染异常的问题
> fix(cascader): fix option title render bug when label is function

- CHANGELOG.md
- package.json
> chore: release 1.10.4

- src/tabs/tab-nav.tsx
https://github.com/Tencent/tdesign-vue-next/issues/4690
查看报错，会落到 vue 中的此处代码
因为 nav 渲染中使用到了 ref 特性，但是原实现中，nav 的内容渲染使用了一个 computed 进行实现，比较不合理，重构了相关的渲染函数
- fix(Tabs): 修正渲染函数导致的生产版本错误
> fix(Tabs): refactoring nav render function to fix error in production

- src/tabs/tab-nav-bar.tsx
https://github.com/Tencent/tdesign-vue-next/issues/4309
getBoundingClientRect 会受到 scale 影响，dialog 场景下定位会有问题，切换使用的api
- fix(Tabs): 优化 `scale` 下的指示器宽度错位的问题
> fix: 🐛 修复 tab 指示器受到 scale 影响的尺寸计算错误的问题

- src/time-picker/props.ts
- src/time-picker/time-picker.tsx
- src/time-picker/time-range-picker-props.ts
- src/time-picker/time-range-picker.tsx
对于 https://github.com/Tencent/tdesign-vue-next/pull/4737 功能的补充
- feat(TimePicker): 支持 `readonly` 属性
> feat(TimePicker): support `readonly`

- src/date-picker/DatePicker.tsx
https://github.com/Tencent/tdesign-vue-next/issues/4767
原逻辑浮窗关闭时，needConfirm 为 false时，会读入 input 结果并将其设置到 value，preset 选择后只更改了 value，未对 input 进行修改，导致关闭时被旧的 input 值覆盖。
- fix(DatePicker): 修正 `needConfirm` 为 `false` 的场景下，`preset` 选择失效的问题
> fix(DatePicker): fix preset invalid when needConfirm is false

- src/time-picker/time-picker.en-US.md
- src/time-picker/time-picker.md
- src/time-picker/time-picker.tsx
- src/time-picker/time-range-picker.tsx
…s docs
对于 https://github.com/Tencent/tdesign-vue-next/pull/4812 代码的进一步优化
- perf(timePicker): 使用全局 `readOnly` 控制并添加关于 `readOnly` 的文档
> perf(timePicker): use global `readOnly` control and add docs

- src/input/useInput.ts
- Introduce `useReadonly` hook
- Use `readonly` instead of `props.readonly`
- Optimize the clear icon display logic to account for Form readonly state
- fix(Input): 修复在 `Form` 设置全局只读下 `Input` 组件的状态异常问题
> fix(input): fix the display issue of Input in Form readonly state

- src/hooks/useVirtualScrollNew.ts
- src/tree/hooks/useTreeScroll.ts
- https://github.com/Tencent/tdesign-vue-next/issues/4564
- fix(Tree): 修复树开启虚拟滚动后容器宽度发生变化会导致回滚到顶部的问题
> fix(Tree): fix tree scroll to top when resize

- src/dialog/__tests__/index.test.jsx
- src/dialog/dialog.tsx
- #4832 
- fix(Dialog): 当 `header` 和 `closeBtn` 都为 `false` 时，不渲染 `header dom`
> fix(Dialog): don't render header dom when header and closeBtn are false

- src/cascader/core/helper.ts
- src/cascader/hooks.ts
from https://github.com/Tencent/tdesign-vue/issues/3430 https://github.com/Tencent/tdesign-vue/issues/3436
- fix(Cascader): 当 `valueType` 为 `full` 时会意外触发 `change` 事件
- fix(Cascader): 校验无效值逻辑错误并优化代码
> fix(cascader): logical error in setting and verifying value

- src/dialog/props.ts
- fix(Dialog): 修复`1.10.4`版本后`closeOnClickOverlay`默认开启行为和挂载`body`行为的缺失问题
> fix(Dialog): fix overlayclick default behavior

- src/date-picker/DateRangePickerPanel.tsx
- fix(DatePicker): 优化日期范围选择面板初始化展示的逻辑，保持右侧面板大于左侧面板
> fix(DatePicker): optimize date range picker panel initial render result

- src/select/hooks/useSelectOptions.ts
- src/select/option-group-props.ts
- src/select/optionGroup.tsx
- src/select/select-panel.tsx
对于 https://github.com/Tencent/tdesign-vue/pull/3445 功能的同步
- fix(select): 修复分组情况下标题不存在 `group` 的渲染报错的问题
> fix(select): `group` title not exist still renders children

- src/breadcrumb/breadcrumb-item.tsx
- src/breadcrumb/breadcrumb.md
[Breadcrumb] BreadcrumbItem 如果同时存在 to 和 href 的 props，在点击后会先后触发，建议设置默认行为 #4885
- fix(breadcrumb): set the default opening method of navigation
> fix(breadcrumb): set the default opening method of navigation

- src/select/option-props.ts
- src/select/type.ts
#4922 
需求背景：option 组件 value 原类型为 string | number，在使用 boolean 类型时控制台打印 vue 类型错误警告
解决方法：添加 boolean
- fix(select): 修复 option value 为 boolean 时控制台类型错误警告
> fix(select): fix warning when type of option value is boolean 

- src/color-picker/panel/index.tsx
closed #4861
[issue #4861](https://github.com/Tencent/tdesign-vue-next/issues/4861)
问题：两种模式同时存在时，固定第一次打开是单色
解决方案：根据当前的 value 切换到正确的 tab
- fix(color-picker): 修复支持渐变模式下，第一次打开时 tabs 位置没有跟随变化的问题
> fix(color-picker): 修复默认模式第一次打开显示出错

- src/select/select.en-US.md
- src/select/select.md
#4922
`Select` 组件的 `option.value` 目前仅支持 `string` 和 `number` 类型，但实际使用场景中还需要支持 `boolean` 类型。此 PR 修复了这一问题。
1. 更新`Option` 组件的API，使其支持 `option.value` 为 `boolean` 类型。（其他PR已实现）
2. 更新api文档，说明 `option.value` 支持 `boolean` 类型。（本次PR解决）
- docs(Select): update API documentation to support boolean type for option.value
> docs(Select): update API documentation to support boolean type for options.value

- src/loading/loading.md
chore: lint md code
- docs(loading): 移除重复的示例
> docs(loading): remove repeat demo

- src/table/base-table.tsx
- src/table/table.md
- src/table/type.ts
https://github.com/Tencent/tdesign-vue-next/issues/4823
https://github.com/Tencent/tdesign-vue-next/issues/4705
https://github.com/Tencent/tdesign-vue-next/issues/4193
增加非虚拟滚动情况下，滚动到某行的实现
[demo](https://stackblitz.com/edit/de21xmeh?file=package.json,src%2Fdemo.vue)
- feat(Table): 支持 `scrollToElement` 方法在非虚拟滚动的情况下使用
> feat(Table): ✨ scrollToElement 支持在非虚拟滚动的情况下使用

- src/select/select.tsx
#4937
在 `Select` 组件的全选逻辑存在问题：
- 当点击“全选”时，已经选中的 `disabled` 选项会被错误地取消选中。
- 期望 `disabled` 选项的选中状态应该完全独立于“全选”操作，无论是否全选， `disabled` 选项的选中状态都应保持不变。
- 优化全选逻辑，额外处理 `disabled` 选项，确保 `disabled` 选项的选中状态不受“全选”操作的影响。
- fix(select): optimize select-all logic to handle disabled options
> fix(select): optimize select-all logic to handle disabled options

- CHANGELOG.md
- package.json
> chore: release 1.10.7

- src/select/__tests__/index.test.jsx
#4937
在 [#4937] 中，发现 select-option的checkAll（全选）逻辑存在问题，尤其是在处理禁用选项时，状态切换不符合预期。为解决该问题并防止未来出现类似问题，本次提交补充了相关的测试样例。
- test(select): add test cases for select component
> test(select): add test cases for select component

- package.json
- script/rollup.config.js
1. `@types/lodash-es` move to devDep
2. remove lodash build config
- fix: lodash-es
> chore: remove lodash from rollup config

- packages/components/form/form-item.tsx
- packages/components/form/form.en-US.md
- packages/components/form/form.md
- packages/components/form/type.ts
chore: remove `statu`s intermediate  `'validating'`
当前 `status` 只能应用到 `tips`上，且 `'validating'` 并无样式实现
- fix(Form): 修复`status` 属性没有应用到校验状态上的问题
> fix(form): `status` attribute being used validator

- internal/utils/index.ts
- internal/utils/package.json
- internal/utils/rollup.config.ts
- internal/utils/src/package-json.ts
- internal/utils/src/paths.ts
- internal/utils/types/index.d.ts
- internal/utils/types/src/package-json.d.ts
- internal/utils/types/src/paths.d.ts
- package.json
- packages/tdesign-vue-next/site/plugin-doc/md-to-vue.js
- packages/tdesign-vue-next/site/plugin-doc/transforms.js
- packages/tdesign-vue-next/site/src/components/codeSandbox/content.js
- packages/tdesign-vue-next/site/src/components/components.jsx
- packages/tdesign-vue-next/site/src/components/stackblitz/content.js
https://github.com/Tencent/tdesign-vue-next/issues/5045
仓库内部使用的 utils 之 _package.json_ 文件引用
- _package.json_ 文件引用 相关
多处文件均需要 _package.json_ 文件引用，目前的获取方式是直接使用的是相对路径，比如:
**处理方式**
- refactor: internal/utils package-json
> refactor: internal/utils package-json

- packages/components/select/hooks/useSelectOptions.ts
问题，在一些选项数量多的场景下，使用默认排序，较短的匹配项可能会被排在很后面，默认的搜索行为应该要能够优先展示全等项
https://stackblitz.com/edit/dmwb73st?file=package.json,src%2Fdemo.vue
- fix(Select): 默认搜索方法优先展示全等项
> feat(Select): set fuzzy match option as the first result when using  default filter

- packages/components/affix/__tests__/index.test.jsx
- packages/components/affix/affix.tsx
- script setup return
- modify exposure and test
- refactor(affix): script setup return
> refactor(affix): component optimization

- packages/components/table/hooks/useHoverKeyboardEvent.ts
- https://github.com/Tencent/tdesign-vue-next/issues/4990
- fix(Table): 修复按下`Ctrl C`复制快捷键导致清空选中行的问题。
> fix(Table): Keyboard Ignore Ctrl & Command

- packages/components/dialog/hooks/useAction.tsx
resolve  #5158
- fix(Dialog):  自定义 `cancelBtn` 文本时保留 `t-dialog__cancel` 样式
> fix(Dialog):  custom `cancelBtn` text retains `t-dialog__cancel` className

- packages/components/table/hooks/useDragSort.ts
- https://github.com/Tencent/tdesign-vue-next/issues/4985
- fix(Table): 表格内容未渲染时，设置`drag-sort`拖动事件报错的问题
> fix(Table): DonT Register Drag Events When NoChildren

- packages/components/select/select.tsx
当 `valueType = 'object'` 时如果使用 filter 进行筛选数据，然后点击全选就会产生tag 显示错误。
https://github.com/user-attachments/assets/157b2317-5c24-4de2-a99e-e0c7509c3b55
- fix(Select): 修复当 `valueType = 'object'` 时，在有已选择数据的情况下筛选数据，全选产生错误 Tag 显示的问题。
> fix(Select): select all error when `valueType = 'object'`

- packages/components/menu/type.ts
修复menu-item的props中to定义时缺少string类型问题
解决tdesign-vue-next-starter路径的类型问题，会导致项目编译错误，实际是支持string类型的：
https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/src/types/interface.d.ts#L18
解决tdesign-vue-next-starter路径的类型问题，会导致项目编译错误，实际是支持string类型的：
https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/src/types/interface.d.ts#L18
- fix(menu): 修复menu-item的props中to定义时缺少string类型问题
> fix(menu): 修复menu-item的props中to定义时缺少string类型问题

- packages/components/drawer/drawer.tsx
- packages/components/drawer/hooks/index.ts
https://github.com/Tencent/tdesign-vue-next/issues/5216
问题：Drawer 拖拽调整size时，Drawer页内容会被选中
- fix(Drawer): 修复Drawer 拖拽调整size时，Drawer页内容会被选中
> fix(drawer): 修复拖拽调整size时，Drawer页内容会被选中的问题

- packages/components/menu/menu-item.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/5273
- fix(menu-item): 修复 `onClick ` 事件触发两次
> fix(menu-item): prevent double `onClick` firing

- packages/components/config-provider/config-provider.en-US.md
- packages/components/config-provider/config-provider.md
- packages/components/config-provider/type.ts
类型错误修改
```diff
- weekdays | Object | - | Typescript：`string[]` | N
+ weekdays | Array | - | Typescript：`string[]` | N
```
months 文案错误修正
```diff
- months | Array | - | 星期文本描述，默认值：['1 月', '2 月', '3 月', '4 月', '5 月', '6 月', '7 月', '8 月', '9 月', '10 月', '11 月', '12 月']。TS 类型：`string[]` | N
+ months | Array | - | 月文本描述，默认值：['1 月', '2 月', '3 月', '4 月', '5 月', '6 月', '7 月', '8 月', '9 月', '10 月', '11 月', '12 月']。TS 类型：`string[]` | N
```
各组件Config按字母排序
> docs(config-provider): sync api

- packages/components/date-picker/date-picker.en-US.md
- packages/components/date-picker/date-picker.md
- packages/components/date-picker/props.ts
- packages/components/date-picker/type.ts
- fix #5291 
- https://github.com/TDesignOteam/tdesign-api/pull/598
- <img width="616" alt="image" src="https://github.com/user-attachments/assets/49ba1286-a929-4bfb-8ee3-122f2ea3dd15" />
- 在 DatePicker.tsx 文件中已实现，问题出在没有接收 props
- 增加 props type docs 等即可
- feat(datePicker): 新增`readOnly`属性，用于只读配置
> feat(DatePicker): support readonly props

- packages/components/tree-select/tree-select.tsx
https://github.com/user-attachments/assets/236f8ae7-feb8-4c10-ada8-239fe78e643d
- fix(tree-select): 修复当 `valueType='object '` 时无初始化选中数据时产生意外错误
修复第二次点击已选中的 item 时 `onChange` 抛出的选中值为空并且取消 item 的选中状态的错误
> fix(tree-select): 当 `valueType='object '` 时无初始化 value导致错误和意外产生取消选中

- packages/components/select/option.tsx
- packages/components/select/select.tsx
ref #5302
1. `selectProvider.value.handleValueChange` 传递的 option 应该是从所有可选项中匹配，而不是最新的已选项中匹配
2. 在 `context.trigger === 'uncheck'`时触发 remove 事件
- feat(select): 取消勾选面板中的已选项时触发 `remove` 事件
> feat(select): add option removal handling for multiple selection

- packages/components/tag-input/hooks/useTagList.tsx
当设置了value，且value为 undefined 时（或者值被外部重置为 undefined ），tag-input 相关逻辑判空不全面，导致组件初始化失败。
- fix(tag-input): fix(tag-input): 修复 useTagList 中 tagValue 的空值逻辑
> fix(tag-input): 修复 useTagList 中 tagValue 的空值逻辑

- packages/components/select/select.tsx
[#3576](https://github.com/Tencent/tdesign-vue/issues/3576)
修复valueType:object与keys同时设置时的绑定值错误
- fix(Select): 修复valueType:object与keys同时设置时的绑定值错误
> fix(Select): 修复valueType:object与keys同时设置时的绑定值错误

- packages/components/color-picker/_example/recent-color.vue
- packages/components/color-picker/color-picker-panel.tsx
- packages/components/color-picker/color-picker.tsx
- packages/components/color-picker/components/panel/index.tsx
- packages/components/color-picker/props.ts
- packages/tdesign-vue-next/.changelog/pr-5428.md
- fix(color-picker): 无法正常显示和添加最近使用颜色
> fix(color-picker): incorrect default value for `recentColors`

- packages/components/space/space.tsx
Because the filtering of teleport child has been implemented in the useFlatChildrenSlots hook #5446
精简代码实现：因为在 useFlatChildrenSlots hook 中已实现对 teleport child 的过滤 #5446
- perf(Space): 移除对 teleport 子 Node 的重复过滤
> perf(space): remove the duplicate filter for teleport child

- .kuai.yaml
- .vscode/settings.json
- packages/components/chat/_example/chat-action.vue
- packages/components/chat/chat-action-props.ts
- packages/components/chat/chat-action.md
- packages/components/chat/chat-action.tsx
- packages/components/chat/type.ts
- [✅ ] 新特性提交
- [✅] 文档改进
- [✅] 演示代码改进
内部需求
- [✅] 本条 PR 不需要纳入 Changelog
- [✅] 文档已补充或无须补充
- [✅ ] 代码演示已提供或无须提供
- [✅] TypeScript 定义已补充或无须补充
- [✅] Changelog 已提供或无须提供
> chat-action 组件 isGood/isBad 参数合并为 comment 参数

- packages/components/color-picker/color-picker.tsx
- packages/tdesign-vue-next/.changelog/pr-5545.md
- https://github.com/Tencent/tdesign-vue-next/pull/5428 中将 `delete` 移除了，本以为后者会覆盖前者，但实际导致传递了一个数组进来
- fix(ColorPicker): 修复 `onChange` 和  `onRecentChange`  回调失效
> fix(ColorPicker): prevent `onChange` prop from being passed as an array

- packages/pro-components/chat/_example/chat-sender-slot.vue
- packages/pro-components/chat/_example/chat-sender.vue
- packages/pro-components/chat/_example/reasoning-drag.vue
- packages/pro-components/chat/_example/reasoning-drawer.vue
- packages/pro-components/chat/_example/reasoning.vue
- packages/pro-components/chat/chat-sender-props.ts
- packages/pro-components/chat/chat-sender.tsx
- packages/pro-components/chat/type.ts
- packages/tdesign-vue-next-chat/.changelog/pr-5595.md
[ChatSender] 修复stopDisabled直接修改值不生效，需要调用发送事件才生效 #5258
closed #5258
https://github.com/Tencent/tdesign-vue-next/issues/5258 
-  通过stopDisabled或者loading传入值来改变按钮状态
-  stopDisabled待废弃，请使用loading替代
- feat(ChatSender):  新增`loading` API，用于控制按钮状态,  `stopDisabled` 将在未来版本废弃，请尽快使用`loading`替换⚠️
- fix(ChatSender): 修复`stopDisabled` 直接修改值不立即生效的问题
- fix(ChatSender): 修复`header`、`innerHeader` 等插槽的传参问题
> fix(ChatSender): fix stopDisabled is effected by internal loading 

- packages/components/alert/_usage/index.vue
- packages/tdesign-vue-next/.changelog/pr-5646.md
无。此改进由贡献者主动发现并提出。
当前 Alert 组件演示中，开启 `close` 属性后，用户关闭 Alert 之后无法在页面上重新显示它。如果想查看其他配置效果，只能刷新页面，使用体验不够友好。 
本次改动在 Alert 被关闭时新增一个“显示 Alert”按钮，用户点击后可以无需刷新页面，直接恢复 Alert 显示，提升演示交互体验。 
该改动仅影响演示示例文件，不涉及组件本身逻辑。
- docs(alert): 优化 Alert 演示交互，在关闭后显示“显示 Alert”按钮以恢复显示
> docs(alert): add  a button to redisplay alert component when it is closed in usage demo

- packages/components/message/__tests__/message.test.tsx
- packages/components/message/plugin.tsx
Fix a regression introduced by switching from `createApp` to `createVNode`.  
Previously, instance existence was checked using `$el`, which is undefined on a VNode.  
This caused multiple `MessageList` instances to be created for the same `placement` (e.g. `'top'`).  
As a result, messages appeared overlapped instead of stacking vertically, and `closeAll` could not clear all messages as expected.  
Now, by using `component.proxy.$el` to check whether the instance is already mounted, the logic ensures only one instance is created per `placement`.  
This guarantees consistent stacking behavior and correct behavior of `closeAll`.
Closes #5559
---
Closes #5559  
问题来源：切换为 `createVNode` 后，message 组件实例判断逻辑失效，导致多个 message 实例叠加。
- **问题**：在 `plugin.tsx` 中将消息组件由 `createApp` 改为 `createVNode` …
> fix(message): reuse message instance to fix overlapped messages and closeAll not working

- packages/components/pagination/__tests__/pagination.test.tsx
- packages/components/pagination/pagination-mini.tsx
- packages/tdesign-vue-next/.changelog/pr-5670.md
…ini navigation buttons
Replace native browser title attributes with TDesign Tooltip component to improve visual consistency and user experience. Configured `showArrow=false` in TTooltip to match the original native title behavior. Added unit tests to verify tooltip rendering and configuration behavior.
无
在 TPaginationMini 组件中，上一页 / 当前 / 下一页按钮原使用原生 `title` 提示，样式与 TDesign 视觉体系不统一，且其样式不可控，在不同浏览器和系统下表现不一致，可能影响整体视觉统一性。TDesign 本身有提供 Tooltip 组件，所以我在想是否可以用它来替代原生 title。
本 PR 使用 TDesign 提供的 `<TTooltip>` 组件替代 `title` 属性，提升提示体验与一致性：
- 配置 `showArrow=false`，以复现原生 title 的纯文本提示体验；
- 同时补充对应的单元测试，覆盖显示逻辑与 props 配置行为。
- feat(Pagination): 优化 `PaginationMini`  的显示提示文案展示
> feat(Pagination): Use Tooltip to replace title in navigation buttons

- packages/components/select/select.tsx
- packages/tdesign-vue-next/.changelog/pr-5775.md
https://github.com/Tencent/tdesign-vue-next/issues/5762
具体问题：要解决的问题是Form表单设置disabled/readonly时，多选select选中项还显示删除按钮，点击还能删除选中项
解决方案：多选Select的选中项的删除按钮判断显隐时考虑Form设置的disabled/readonly，使用hook返回的字段判断
修复了Form设置为disabled或readonly时，其中的多选Select组件在disabled/readonly时标签存在删除按钮且可以删除标签的问题。
- fix(Select): 修复 Form 设置为 disabled 或 readonly 时，多选选项仍可删除的错误
> fix(select): selected option can be removed when form is disabled

- packages/components/color-picker/components/panel/index.tsx
- packages/components/color-picker/components/panel/slider.tsx
- packages/tdesign-vue-next/.changelog/pr-5814.md
色相(Hue)滑动条上的点频繁跳跃：
- 该点由 `color.hsv` 的 `h` 控制
- RGB -> HSV -> RGB，色彩在转换过程中存在小数点误差，多次累计后偏差越来越大
https://github.com/user-attachments/assets/5db5f794-483d-4a3b-be8e-22fee1a09379
---
此外，优化了一下滑动条上的点的颜色显示，三个点的颜色代表意义是不同的，不应该统一设为最终的显示数值
- fix(ColorPicker): 减少颜色跨色彩空间的多次转换，降低误差
> fix(ColorPicker): reduce multiple color conversions to minimize errors

- packages/components/select/__tests__/select.test.tsx
- packages/components/select/_example/multiple.vue
- packages/components/select/components/select-panel.tsx
- packages/components/select/hooks/useSelectOptions.ts
- packages/components/select/select.tsx
- packages/tdesign-vue-next-chat/.changelog/pr-5779.md
…meter content in option data
Related https://github.com/Tencent/tdesign-vue-next/pull/5199
- fix(select): 解决 keys 别名出现 `content` 冲突的问题
- fix(select): 恢复 onChange 的 `conte.option` 参数数据
> fix(select): fix keys alias restore onChange params

- packages/components/input/__tests__/input.test.tsx
- packages/components/input/hooks/useInputEventHandler.ts
- packages/components/input/input.tsx
- packages/tdesign-vue-next/.changelog/pr-5862.md
在 `useInputEventHandler` 中添加 `isComposition` 检查以防止回车键事件
在中文输入法输入过程中
将 `useInput` 中的 `isComposition` 状态传递给 `useInputEventHandler`
- 添加测试用例以验证输入法组合行为
修复了表格筛选组件的问题，即按回车键会同时触发两个操作
输入法提交和过滤确认
- #5860
- fix(Input): 修复中文输入法激活时不触发 `onEnter` 事件的问题
> fix(input): prevent onEnter event during IME composition

- packages/components/color-picker/color-picker.tsx
- packages/components/color-picker/components/panel/header.tsx
- packages/components/color-picker/components/panel/index.tsx
- packages/tdesign-vue-next/.changelog/pr-5839.md
https://github.com/Tencent/tdesign-vue-next/issues/5837
-  `...((props.popupProps as any) || {})` 应该放在最后面，否则无法被用户自定义的属性覆盖
- 实际上这个组件也不需要让 `visible` 受控...让 `Popup` 内部自己控制即可 
- fix(ColorPicker): 修复 `popupProps.onVisibleChange` 回调函数不执行
> fix(ColorPicker): remove unused visibility state and related logic

- packages/components/watermark/__tests__/watermark.hooks.test.tsx
- packages/components/watermark/__tests__/watermark.test.tsx
> test(watermark): improve watermark test coverage

- packages/components/notification/_example/plugin.vue
- packages/components/notification/notification-list.tsx
- packages/components/notification/notification.en-US.md
- packages/components/notification/notification.md
- packages/components/notification/notification.tsx
- packages/components/notification/props.ts
- packages/components/notification/type.ts
- packages/tdesign-vue-next/.changelog/pr-5958.md
修复了 `NotifyPlugin.close()` 会错误触发 `onCloseBtnClick` 事件的问题。
**问题背景：**
`onCloseBtnClick` 事件本应仅在用户手动点击关闭按钮时触发。但在之前的实现中，通过代码调用 `NotifyPlugin.close()` 方法同样会错误地触发该事件。这会导致开发者在 `onCloseBtnClick` 回调中编写的、仅针对用户行为的逻辑被意外执行，从而引发潜在的 Bug。
**解决方案：**
新增 `onClose` 事件，将程序化关闭和用户手动关闭的逻辑进行解耦。
**`Notification`**: 新增 `onClose` prop，并重构内部关闭逻辑，区分了用户点击 (`handleCloseBtnClick`) 和程序化调用 (`close`)，确保只有前者触发 `onCloseBtnClick` 事件。
**备注：**
‘packages/components/notification/_example/plugin.vue’是为了演示这个场景，后续需要删除
- feat(Notification): 新增`onClose` 事件，用于处理调用  `NotifyPlugin.close()`  的相关回调场景
-  fix(Notification): 修复调用 `NotifyPlugin.close()` 错误触发 `onCloseBtnClick` 回调的问题
> fix(notification): 修复 NotifyPlugin.close 错误触发 onCloseBtnClick 的问题
