Tencent/tdesign-vue-next

- src/drawer/drawer.tsx
- test/unit/calendar/__snapshots__/demo.test.js.snap
- test/unit/calendar/demo.test.js
> fix: drawer api

- examples/tooltip/demos/theme.vue
- src/popup/popup.tsx
- src/tooltip/tooltip.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/anchor/__snapshots__/demo.test.js.snap
- test/unit/calendar/__snapshots__/demo.test.js.snap
- test/unit/calendar/__snapshots__/index.test.js.snap
- test/unit/cascader/__snapshots__/demo.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/date-picker/__snapshots__/demo.test.js.snap
- test/unit/date-picker/__snapshots__/index.test.js.snap
- test/unit/dropdown/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/pagination/__snapshots__/demo.test.js.snap
- test/unit/popconfirm/__snapshots__/demo.test.js.snap
- test/unit/popup/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/index.test.js.snap
- test/unit/slider/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/time-picker/__snapshots__/demo.test.js.snap
- test/unit/tooltip/__snapshots__/demo.test.js.snap
- test/unit/transfer/__snapshots__/demo.test.js.snap
- test/unit/tree-select/__snapshots__/demo.test.js.snap
| 组件 | 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|-----|
| Popup | t-popup-content | t-popup__content | - |
| Popup | t-popup-reference | t-popup__reference | - |
| Popup | t-popup_animation-enter | t-popup--animation-enter | - |
| Popup | t-popup_animation-enter-from | t-popup--animation-enter-from | - |
| Popup | t-popup_animation-exiting | t-popup--animation-exiting | - |
| Popup | t-popup_animation-leave-to | t-popup--animation-leave-to | - |
| Popup | t-popup_animation-enter-to | t-popup--animation-enter-to | - |
| Popup | t-popup_animation-entering | t-popup--animation-entering | - |
| Popup | t-popup_animation-leave-from | t-popup--animation-leave-from | - |
| Popup | t-popup_animation-leave | t-popup--animation-leave | - |
| Popup | t-popup_animation-enter-active | …
> feat: bem style classes

- src/menu/head-menu.tsx
- src/menu/menu-group.tsx
- src/menu/menu-item.tsx
- src/menu/menu.tsx
- src/menu/submenu.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/menu/__snapshots__/demo.test.js.snap
- test/unit/menu/__snapshots__/head-menu.test.js.snap
- test/unit/menu/__snapshots__/menu-item.test.js.snap
- test/unit/menu/__snapshots__/menu.test.js.snap
Menu：更正 classname，以及移除无用 classname
> refactor(menu): correct classname

- .github/workflows/tag-push.yml
- examples/config-provider/demos/pagination.vue
- examples/table/demos/filter-controlled.vue
- examples/table/demos/tree-select.vue
- src/tree-select/tree-select.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- 处理table报错问题
- 处理tree-select 空判断问题
> feat(table): demo update

- src/date-picker/panel/date-range.tsx
date-range-picker: click failure
> fix: date-picker-range click error

- src/checkbox/group.tsx
- src/steps/step-item.tsx
- src/steps/steps.tsx
- src/table/base-table/index.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/steps/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/index.test.js.snap
- steps bem refactor
- checkbox fix select all
- table bem fix
> refactor: bem steps and checkbox checkAll bug

- src/date-picker/basic/cell.tsx
- src/date-picker/calendar-presets.tsx
- src/date-picker/date-picker.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/date-picker/__snapshots__/demo.test.js.snap
- test/unit/date-picker/__snapshots__/index.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
> fix(date-picker): fix date-picker style and clicker fail

- src/table/base-table/col-group.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/index.test.js.snap
Table: 在多级表头情况下，正确处理 column 的宽度
> fix(table): resolve column width on multiple columns

- package.json
> feat: add init submodule command

- src/tabs/tabs.tsx
> fix: tabs render error

- examples/input/demos/base.vue
- examples/input/input.md
- src/input/input.tsx
- src/input/props.ts
- src/input/type.ts
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/date-picker/__snapshots__/demo.test.js.snap
- test/unit/date-picker/__snapshots__/index.test.js.snap
- test/unit/drawer/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/input/__snapshots__/demo.test.js.snap
- test/unit/input/__snapshots__/index.test.js.snap
- test/unit/message/__snapshots__/demo.test.js.snap
- test/unit/notification/__snapshots__/demo.test.js.snap
- test/unit/popup/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/time-picker/__snapshots__/demo.test.js.snap
- test/unit/tooltip/__snapshots__/demo.test.js.snap
- test/unit/transfer/__snapshots__/demo.test.js.snap
- test/unit/tree-select/__snapshots__/demo.test.js.snap
- test/unit/tree/__snapshots__/demo.test.js.snap
> feat(input): 加左侧、右侧文本

- src/calendar/calendar.tsx
> fix(Calendar): month mode disable status wrong  performance

- .github/workflows/tag-push.yml
- doc/CONTRIBUTING.md
- package.json
docs: edit contribute and tag-push workflow
> docs(contribut): edit contribute

- examples/tag/demos/delete.vue
> fix: modify add tag demo

- examples/table/demos/filter-controlled.vue
> fix(table): filter demo error

- site/site.config.js
- site/src/routes.js
- src/table/base-table/table-body.tsx
- src/table/base-table/table-row.tsx
- src/table/primary-table/index.tsx
修复 onRowMouseenter、onRowMouseleave事件能正常触发
> fix(table): event

- .github/workflows/preview-publish.yml
- .github/workflows/pull-request.yml
- action pr add types
- action action/comment update version
> ci: add pr type and update comment version

- examples/popup/demos/destroy.vue
- examples/tooltip/demos/base.vue
- src/popup/popup.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/popup/__snapshots__/demo.test.js.snap
- test/unit/tooltip/__snapshots__/demo.test.js.snap
> fix: popup destory on close

- examples/select/demos/remote-search.vue
- src/textarea/textarea.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
> fix(select): fix select remote search demo

- examples/steps/demos/icon.vue
- examples/steps/demos/no-sequence.vue
- examples/steps/demos/status.vue
- examples/steps/demos/vertical-no-sequence.vue
- examples/steps/demos/vertical-sequence.vue
- examples/steps/steps.md
- src/steps/props.ts
- src/steps/step-item.tsx
- src/steps/type.ts
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/steps/__snapshots__/demo.test.js.snap
feat: add steps readonly props
> feat(steps): readonly

- src/popup/popup.tsx
> fix(popup): fix popup mousedown event

- src/tree-select/tree-select.tsx
修复组件data异步加载展示异常的问题
https://github.com/Tencent/tdesign-vue/issues/96
> fix(tree-select): fix data lazy load bug

- src/input/index.ts
- src/input/input.tsx
- test/unit/input/index.test.js
> fix(input): focus after clear

- src/tabs/tabs.tsx
> fix(tabs): one panel render error fix

- src/style/index.js
just like tdesign-vue fix pr: https://github.com/Tencent/tdesign-vue/pull/141
> feat: add css vars into style/index

- src/button/button.tsx
> refactor(button): improve computing performance

- src/menu/menu-item.tsx
> fix(menu): correct plain menu item

- src/upload/single-file.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/upload/__snapshots__/demo.test.js.snap
> fix: upload delete button

- examples/steps/demos/extra.vue
- src/steps/steps.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/layout/__snapshots__/demo.test.js.snap
- test/unit/steps/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
> WIP：fix: fix the steps component to render custom content

- src/cascader/utils/inputContent.ts
fix full value-type mutiple remove tag bug
> fix(cascader): fix full value-type mutiple remove tag

- src/dropdown/dropdown-item.tsx
- src/dropdown/dropdown.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/dropdown/__snapshots__/demo.test.js.snap
fix dropdown slot click popup hide
https://tdesign.tencent.com/vue-next/components/dropdown#%E9%80%9A%E8%BF%87%E6%8F%92%E6%A7%BD%E6%96%B9%E5%BC%8F%E4%BD%BF%E7%94%A8%E4%B8%8B%E6%8B%89%E8%8F%9C%E5%8D%95
> fix(dropdown): fix dropdown slot click hide

- examples/tabs/demos/custom.vue
- src/steps/steps.tsx
- src/tabs/tabs.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/tabs/__snapshots__/demo.test.js.snap
修复 插槽为循环创建与常规混用时的渲染错误
```html
<t-tabs>
<t-tabs-panel v-for="(item, index) in 5" :key="index" :label="item.label" :value="item.value" />
<t-tabs-panel   lable="test" value="test" />
</t-tabs> 
```
> fix(steps,tabs): fix steps and tabs

- examples/radio/radio.md
- src/radio/group.tsx
- src/radio/props.ts
- src/radio/radio-group-props.ts
- src/radio/radio.tsx
- src/radio/type.ts
support radio allowUnCheck props
> feat: support radio allowUnCheck

- examples/tree/demos/operations.vue
- src/menu/menu.tsx
- src/textarea/textarea.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
fix textarea custom classname invalid
> fix(textarea): fix textarea custom classname invalid

- examples/select/demos/creatable.vue
> fix: issue 111

- src/slider/slider-button.tsx
修复slider组件滑块只有在鼠标移入元素时会显示弹窗 
关联issue：#117
> fix(slider): fix the slider component popup display

- CHANGELOG.md
- package.json
> docs(version): release 0.6.1

- examples/swiper/demos/swiper.vue
- src/swiper/swiper.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/swiper/__snapshots__/demo.test.js.snap
> fix(swiper): fix issue 169

- examples/select/demos/creatable.vue
> fix(select): fix creatable demo

- src/hooks/event.ts
> feat(hooks): add emitEvent hook

- src/avatar/avatar.tsx
- src/avatar/group.tsx
> refactor(avatar): refactor avatar component used by composition

- examples/menu/demos/multi-side.vue
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/menu/__snapshots__/demo.test.js.snap
> fix(menu): fix menu muti-side demo

- site/docs/getting-started.md
add vue-next library options to fix import error
> doc: add library options for tdesign resolver

- examples/menu/demos/custom-header.vue
- examples/menu/demos/double.vue
- src/menu/index.ts
> fix(menu): fix issue 168

- src/alert/alert.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/alert/__snapshots__/demo.test.js.snap
- test/unit/calendar/__snapshots__/demo.test.js.snap
- test/unit/swiper/__snapshots__/demo.test.js.snap
> refactor(alert): refactor alert component used by composition

- src/alert/alert.tsx
- src/cascader/cascader.tsx
- src/cascader/components/InputContent.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/alert/__snapshots__/demo.test.js.snap
- test/unit/calendar/__snapshots__/demo.test.js.snap
- test/unit/swiper/__snapshots__/demo.test.js.snap
- fix cascader style
- optimize alert code
> fix(cascader): fix cascader input width and input-inner style

- .eslintrc
- examples/slider/demos/base.vue
- src/dropdown/dropdown.tsx
- test/unit/slider/__snapshots__/demo.test.js.snap
> fix(dropdown): fix popupProps overlayClass

- src/alert/alert.tsx
- src/hooks/icon.tsx
> feat(hooks): add icon hook

- src/menu/head-menu.tsx
- src/menu/menu.tsx
> fix(menu): fix menu events firing twice

- src/tabs/tab-nav.tsx
- src/tabs/tabs.tsx
- test/unit/tabs/__snapshots__/index.test.js.snap
修复没有 planels data 时 tabs header不渲染的问题。
> fix(tabs): tabs of header are always rendered when planels is null

- .eslintrc
- site/src/components/components.jsx
> feat(surge): edit surge domain

- src/hooks/tnode.ts
- src/layout/content.tsx
https://github.com/Tencent/tdesign-vue-next/issues/161
> feat: add useTNodeJSX hook

- src/breadcrumb/breadcrumb.tsx
- src/comment/comment.tsx
avatar suport slot
BreadcrumbItem code optimize
> fix(comment): avatar suport slot

- package.json
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/input-number/__snapshots__/demo.test.js.snap
- test/unit/input-number/__snapshots__/index.test.js.snap
- test/unit/slider/__snapshots__/demo.test.js.snap
- test/unit/tree-select/__snapshots__/demo.test.js.snap
1. 修复t-icon ssr 渲染的问题
2. 修复medium size问题 由`middle`改为`medium`（影响snapshot）
> fix(icon): ssr render & medium size

- script/rollup.config.js
- site/pwaConfig.js
- src/index.ts
关联 https://github.com/Tencent/tdesign-vue/pull/271
> feat(style): update build umd

- src/cascader/utils/inputContent.ts
> fix(issue): fix 166

- script/rollup.config.js
- src/index-lib.ts
- src/index.ts
修复 umd 产物中没有 reset 和 theme 下 css variables 的问题，与 vue2 类似 pr：https://github.com/Tencent/tdesign-vue/pull/271、https://github.com/Tencent/tdesign-vue/pull/285
> feat: import style in index-lib

- examples/select/demos/remote-search.vue
- src/select/select.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/calendar/__snapshots__/demo.test.js.snap
- test/unit/calendar/__snapshots__/index.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/pagination/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/index.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
> fix(issue): 235

- examples/tag-input/demos/collapsed.vue
- examples/tag-input/demos/custom-tag.vue
- examples/tag-input/demos/excess.vue
- examples/tag-input/demos/size.vue
- examples/tag-input/demos/status.vue
- examples/tag-input/demos/theme.vue
- examples/tag-input/tag-input.md
- src/tag-input/props.ts
- src/tag-input/tag-input.tsx
- src/tag-input/type.ts
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/tag-input/__snapshots__/demo.test.js.snap
add size props and style optimize
> feat(tag-input): add size props and style optimize

- src/loading/loading.tsx
- 日常 bug 修复
- 无
- 修复重构Loading导致lock在全屏未移除的错误
> fix(loading): remove lock

- examples/table/demos/lazy.vue
- examples/table/demos/virtual-scroll.vue
- examples/table/table.md
- site/site.config.js
- src/table/base-table-props.ts
- src/table/base-table/table-body.tsx
- src/table/base-table/table-cell.tsx
- src/table/base-table/table-row.tsx
- src/table/primary-table-props.ts
- src/table/type.ts
- src/table/util/interface.ts
- test/ssr/__snapshots__/ssr.test.js.snap
- feat(table): table 增加 `cell-click` 事件
> feat(table): add table cell-click

- jsx.d.ts
- src/hooks/tnode.ts
- src/utils/render-tnode.ts
- tsconfig.json
> feat(tnode): optimize render tnode

- examples/table/demos/data-sort.vue
- examples/table/demos/expandable.vue
- examples/table/demos/multiple-sort.vue
- examples/table/demos/select-multiple.vue
- examples/table/demos/select-single.vue
- examples/table/demos/show-columns.vue
- examples/table/demos/single-sort.vue
- examples/tree/demos/operations.vue
> fix(table): remove demo @import

- src/layout/content.tsx
#255 
修复 `t-content` 无法控制内容的显示与隐藏 
-  修复 `t-content` 无法控制内容的显示与隐藏 
> fix(issue): fix issue 255

- src/slider/slider.tsx
https://github.com/Tencent/tdesign-vue-next/issues/260
查阅代码发现 watch 里，当 Slider 不是双游标时，value 的新值赋值给了错误的变量，commit 已更正这个问题。
- fix(slider): fix value watching (修复不正确的值监听)
> fix(slider): fix value watching

- src/select/select.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/calendar/__snapshots__/demo.test.js.snap
- test/unit/calendar/__snapshots__/index.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/pagination/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/index.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/transfer/__snapshots__/demo.test.js.snap
优化 select 样式
优化 select 样式
select: 优化 select 样式
> feat(select): update classname

- src/tabs/tab-nav-item.tsx
#248 
- fix(tabs): 处理 remove 出发时 warning 
> fix(tabs): fix remove warning

- src/select/select.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/index.test.js.snap
- Select: 更改加载中的元素标签，[pr 270](https://github.com/Tencent/tdesign-vue-next/pull/270)，[@geff1991](https://github.com/geff1991)
- 更改前
- 更改后
> feat: 加载中元素标签

- src/select/select.tsx
- src/tree-select/tree-select.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/tree-select/__snapshots__/demo.test.js.snap
#165 
#271 
- fix(select): 修复在可过滤状态下双击背景才可以关闭弹窗
- fix(tree-select): 修复在可过滤状态下双击背景才可以关闭弹窗
- fix(tree-select): 修复在控状态时不显示placeholder
> fix(select,tree-select): fix double-click bg close popup

- package.json
- test/unit/table/demo.test.js
- babel 7.17.x变动会导致流水线的test失败 需要将babel固定到7.16.x的版本 
- table 的 demo 用到了 date-picker，增加了mock-date
> fix: new babel core leads to test fail

- script/test/generate-demo-test.js
- test/unit/date-picker/demo.test.js
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/table/demo.test.js
调整生成demo test的脚本 避免重跑覆盖导致Mockdate丢失
> chore: fix table demo test date

- src/drawer/action.tsx
- src/drawer/drawer.tsx
- src/hooks/action.tsx
> refactor(drawer): refactor drawer component used by composition

- src/progress/progress.tsx
使用 `Composition API` 重构 `Process` 组件
重构 `Process` 组件
https://github.com/Tencent/tdesign-vue-next/issues/58
1. `conputed` 和 `methods` 迁移至 `setup`
> refactor(process): refactor process component used by composition

- src/cascader/cascader.tsx
- src/cascader/utils/helper.ts
- src/cascader/utils/inputContent.ts
[#300 ](https://github.com/Tencent/tdesign-vue-next/issues/300)
- fix(cascader): 解决value类型为Number时，数据回填异常及clearable失效问题
> fix(cascader): 解决value类型为Number时，数据回填异常及clearable失效问题

- src/alert/alert.tsx
- src/avatar/avatar.tsx
- src/drawer/drawer.tsx
- src/hooks/event.ts
- src/menu/head-menu.tsx
- src/menu/menu.tsx
> hooks/useEmitEvent 去除useEmitEvent入参

- src/popup/popup.tsx
- 调整基于popup的动画的实现方式，实现方式由max-height改为基于clip-path via @ikeq 
- 简化了一些代码，减少大量耦合在transition阶段的max-height/overflow多个阶段重置、修改的代码
- https://github.com/Tencent/tdesign-common/issues/155
- https://github.com/Tencent/tdesign-common/issues/155
- feat(popup): 优化展开收起动画，基于clip-path实现
> feat(popup): sync clip-path expand-collapse animation

- examples/tag-input/demos/base.vue
- examples/tag-input/demos/collapsed.vue
- examples/tag-input/demos/custom-tag.vue
- examples/tag-input/demos/excess.vue
- examples/tag-input/demos/max.vue
- examples/tag-input/demos/size.vue
- examples/tag-input/demos/status.vue
- examples/tag-input/demos/theme.vue
- src/alert/alert.tsx
- src/hooks/action.tsx
- src/hooks/icon.tsx
- src/hooks/tnode.ts
- src/tag-input/tag-input.tsx
- src/tag-input/useTagList.tsx
> refactor(hooks): fix tnode hooks

- src/dialog/dialog.tsx
- src/dialog/plugin.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/dialog/__snapshots__/demo.test.js.snap
- test/unit/upload/__snapshots__/demo.test.js.snap
- fix(dialog): 优化dialog弹框动画
- fix(dialog): 优化dialog插件调用时候的弹框动画
- fix(dialog): 优化lock条件边界
> refactor(dialog): refactor dialog component used by compoisitionAPI

- src/input/input.tsx
- test/unit/input/__snapshots__/index.test.js.snap
- fix(input): 修复 `prefixIcon`, `suffixIcon` 对驼峰写法的支持
> fix(input): fix prefix icon

- site/src/components/demo-page.vue
- site/src/routes.js
- src/affix/affix.tsx
#213 
修复 affix 无效
- fix(affix): 修复 affix 显示无效
> fix: issue 213

- src/list/list-item-meta.tsx
- src/list/list.tsx
refactor list component used by composition
[#58 ](https://github.com/Tencent/tdesign-vue-next/issues/58)
1. 使用setup收拢method、computed
2. scroll回调直接使用event.target获取计算值，减少声明ref获取实例以代替this.$el的成本
> refactor(List): refactor list component used by composition

- src/time-picker/panel/panel-col.tsx
- 日常 bug 修复
- https://github.com/Tencent/tdesign-vue/issues/107
- 改onmousewheel事件为scroll事件
- fix(time-picker): 修复部分鼠标滚动选择出现偏差的问题
> fix(timepicker): panel scroll

- examples/loading/demos/attach.vue
- examples/loading/demos/base.vue
- examples/loading/demos/delay.vue
- examples/loading/demos/fullscreen.vue
- examples/loading/demos/icon-text.vue
- examples/loading/demos/service.vue
- examples/loading/demos/size.vue
- examples/loading/demos/text.vue
- examples/loading/demos/wrap.vue
- examples/loading/loading.md
- src/loading/loading.tsx
- src/loading/plugin.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/loading/__snapshots__/demo.test.js.snap
- 日常缺陷修复
https://github.com/Tencent/tdesign-vue/issues/398
- fix(Loading): 存在 attach 时，当 loading 设置为 false，无法隐藏加载元素
> fix(loading): can not hide loading when it is false for attached loading

- examples/notification/demos/operation.vue
- examples/notification/demos/toggle.vue
- src/notification/const.ts
- src/notification/notification.tsx
- src/notification/notificationList.tsx
- src/notification/plugin.ts
- src/upload/upload.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/notification/__snapshots__/demo.test.js.snap
- test/unit/upload/__snapshots__/demo.test.js.snap
#349 
#351 
- fix(upload): 修复文件数大于等于 `max` 时，上传按钮依然可以点击
- fix(notification): 修复 offset 参数无效
> fix(issue): fix 349 and 342

- src/table/base-table/index.tsx
- src/table/base-table/table-cell.tsx
- src/table/base-table/table-header.tsx
ix table fixed-column error
修复表头错位
#325 
#316 
#299 
before
after
> fix(table): fixed column

- src/config-provider/useConfig.tsx
- [feat]:[使用compositionAPi重构国际化mixin]
> 使用compositionAPi重构国际化mixin

- src/hooks/tnode.ts
- src/utils/render-tnode.ts
> fix(tnode): fix tnode

- CHANGELOG.md
- package.json
- site/site.config.mjs
版本发布
- 发布版本0.9.0，已经发布0.9.0-alpha.1 测试 
> docs(version): release version 0.9.0

- src/input-number/input-number.tsx
- src/menu/menu-item.tsx
#390 
#373 
- fix(menu): 修复menu-item跳转未保留历史记录，误用了replcae
- fix:inputNumber: 修复在增加小数点位数的状态下，v-model绑定的value与展示的值不同
> fix(issue): fix issue 373 && 390

- src/dialog/plugin.tsx
- src/input/input.tsx
- src/message/plugin.tsx
- src/notification/plugin.ts
- src/utils/map-props.ts
#393 
#395 
- fix(dialog): 修复 dialog plugin 聚焦 button 通过键盘频繁触发
- fix(input): 修复 mapProps 导致 input 的 on-change 函数不执行的问题
> fix(dialog,): 修复 dialog plugin 聚焦 button 通过键盘频繁触发问题

- CHANGELOG.md
- package.json
- src/affix/affix.tsx
> docs(version): release 0.9.3

- CHANGELOG.md
- package.json
- src/checkbox/group.tsx
- src/pagination/pagination.tsx
> docs(version): release 0.9.4

- src/affix/affix.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/affix/__snapshots__/demo.test.js.snap
- test/unit/anchor/__snapshots__/demo.test.js.snap
- fix(affix): 优化affix 代码结构，移除冗余dom节点
> chore(affix): optimize affix dom logic

- src/input-number/input-number.tsx
- src/input/input.tsx
- src/select/select.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/calendar/__snapshots__/demo.test.js.snap
- test/unit/calendar/__snapshots__/index.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/date-picker/__snapshots__/demo.test.js.snap
- test/unit/date-picker/__snapshots__/index.test.js.snap
- test/unit/drawer/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/input-number/__snapshots__/demo.test.js.snap
- test/unit/input-number/__snapshots__/index.test.js.snap
- test/unit/input/__snapshots__/demo.test.js.snap
- test/unit/input/__snapshots__/index.test.js.snap
- test/unit/message/__snapshots__/demo.test.js.snap
- test/unit/notification/__snapshots__/demo.test.js.snap
- test/unit/pagination/__snapshots__/demo.test.js.snap
- test/unit/popup/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/index.test.js.snap
- test/unit/slider/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/tag-input/__snapshots__/demo.test.js.snap
- test/unit/time-picker/__snapshots__/demo.test.js.snap
- test/unit/tooltip/__snapshots__/demo.test.js.snap
- test/unit/transfer/__snapshots__/demo.test.js.snap
- test/unit/tree-select/__snapshots__/demo.test.js.snap
- test/unit/tree/__snapshots__/demo.test.js.snap
- fix(input): 
- 修复前后置标签输入框同事存在时左侧样式异常
- dom节点调整 https://github.com/Tencent/tdesign-common/pull/276
- chore(select): 增加select 组件 polyfill class，重构兼容代码，无需记录changelog
> refactor: input wrapclass

- src/alert/alert.tsx
- src/avatar/avatar.tsx
- src/dialog/dialog.tsx
- src/drawer/drawer.tsx
- src/list/list.tsx
https://github.com/Tencent/tdesign-vue-next/wiki/TDesign--CompositionAPI-
%E5%BC%80%E5%8F%91%E8%A7%84%E8%8C%83
> chore(useEmit): remove useEmit

- examples/pagination/demos/base.vue
- src/hooks/useDefaultValue.ts
- src/hooks/useVModel.ts
- src/pagination/index.ts
- src/pagination/pagination.tsx
- src/pagination/props.ts
- src/pagination/useMoreAction.ts
- src/pagination/usePaginationClasses.ts
- src/popconfirm/popconfirm.tsx
- src/select-input/useMultiple.tsx
- src/tag-input/tag-input.tsx
- src/tag-input/useTagList.tsx
- src/tag/check-tag.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/pagination/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/transfer/__snapshots__/demo.test.js.snap
- feat: 移除pagination 组件的 mapProps
- optimize useVModel and useDefaultValue params
> feat(pagination):  useVModel and useDefaultValue replace mapprops

- src/select/option.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/calendar/__snapshots__/demo.test.js.snap
- test/unit/calendar/__snapshots__/index.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/pagination/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/index.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/transfer/__snapshots__/demo.test.js.snap
- 日常 bug 修复
修复前：
修复后：
- fix(select): 修复单选下斜八度动画覆盖文字的错误
> select: 修复单选下斜八度动画覆盖文字的错误

- src/cascader/utils/item.ts
- 日常 bug 修复
#405
#203 
before
after
- fix(select): filterable属性导致高度变化 #405
- fix(cascader): 
- 修复 filterable属性导致的hover态样式异常
- 修复可选任意一级缺少高亮状态 #203 
> fix(cascader): fix checkStrictly status style

- src/date-picker/date-picker.tsx
日常 bug 修复
#419 
直接使用 TButton 而不是 t-button
- fix(date-picker): close #419, use TButton instead of t-button
> fix(date-picker): close #419, use TButton instead of t-button

- src/hooks/useDefaultValue.ts
- src/hooks/useVModel.ts
修复受控时的事件执行顺序
前置双向绑定数据更新，后置事件执行, 否则执行事件时，change事件不为新值
- fix(select): 修复 select 事件与双向绑定数据更新时机不一致问题
> fix(hook): fix useVModel and useDefaultValue event order

- CHANGELOG.md
- package.json
> docs(version): release 0.10.0

- examples/input-number/demos/align.vue
- examples/input-number/demos/auto-width.vue
- examples/input-number/demos/status.vue
- examples/input-number/input-number.md
- src/input-number/input-number.tsx
- src/input-number/props.ts
- src/input-number/type.ts
- src/input/input.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/input-number/__snapshots__/demo.test.js.snap
- test/unit/input-number/__snapshots__/index.test.js.snap
- test/unit/pagination/__snapshots__/demo.test.js.snap
- test/unit/slider/__snapshots__/demo.test.js.snap
- 日常 bug 修复：修复input组件keypress事件未触发问题
- 新特性提交：新增autoWidth、align、tips的支持，统一InputNumber中的Input使用Input组件 减少重复实现
- 演示代码改进：新增auto-width、align及status等演示demo
- 修复decimal计算错误
- fix typo : inputing -> inputting
- feat(input-number): 支持autoWidth、align及tips等属性
> InputNumber: 支持align、auto-width及tips等属性

- examples/switch/switch.md
- src/hooks/useVModel.ts
- src/switch/index.ts
- src/switch/props.ts
- src/switch/switch.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/calendar/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/loading/__snapshots__/demo.test.js.snap
- test/unit/skeleton/__snapshots__/demo.test.js.snap
- test/unit/switch/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/tree/__snapshots__/demo.test.js.snap
- test/unit/upload/__snapshots__/demo.test.js.snap
Composition Api 重构计划 #58 
切换 `Switch` 代码风格
> refactor(switch): change component's style to Composition Api

- examples/select-input/demos/width.vue
- src/hooks/useDefaultValue.ts
- src/hooks/useVModel.ts
- src/input/input.tsx
- src/select-input/useSingle.tsx
- src/tag-input/useTagScroll.ts
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/select-input/__snapshots__/demo.test.js.snap
简化useVModle和useDefaultValue 参数。
fix(tag-input): 
- 修复 breakline 模式下的clearIcon样式重叠 https://github.com/Tencent/tdesign-common/pulls
- 修复 autowidth 模式下的 padding 不对称 https://github.com/Tencent/tdesign-common/pulls
- 修复超出滚动失效
fix(input): 修复在readonly模式下的聚焦样式
> fix(tag-input): scroll error and autowidth style

- src/table/base-table/table-row.tsx
- src/table/primary-table/index.tsx
> fix(table): fix cell click warn

- src/textarea/index.ts
- src/textarea/props.ts
- src/textarea/textarea.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/comment/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/input/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
- test/unit/textarea/__snapshots__/demo.test.js.snap
- refactor(textarea): 使用composition api 重构
> refactor(textarea): use composition api

- examples/select/demos/custom-selected.vue
- src/select/select.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/calendar/__snapshots__/demo.test.js.snap
- test/unit/calendar/__snapshots__/index.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/pagination/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/index.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/transfer/__snapshots__/demo.test.js.snap
支持单选状态下的 `valueDisplay` 插槽
- fix(select): 支持单选 `valueDisplay` 插槽
> feat(select): support single select valueDisplay

- src/time-picker/panel/index.tsx
- src/time-picker/time-picker.tsx
- src/time-picker/time-range-picker.tsx
- 日常 bug 修复 close、open事件回调增加参数
- fix(time-picker):  close、open事件回调增加参数
> fix(time-picker): close、open事件增加回调参数

- src/loading/loading.tsx
- src/radio/group.tsx
- src/select-input/select-input.tsx
- src/tag-input/tag-input.tsx
- src/tree/constants.ts
- src/tree/td-tree.tsx
- src/tree/tree-item.tsx
- fix(classPrefix): add global classPrefix
> feat(classprefix): add global classPrefix

- src/textarea/textarea.tsx
- refactor(textarea): move usePrefixClass
> refactor: move usePrefixClass

- CHANGELOG.md
- package.json
> docs(version): release version 0.10.2

- src/date-picker/date-picker.tsx
- src/time-picker/time-picker.tsx
- src/time-picker/time-range-picker.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/date-picker/__snapshots__/demo.test.js.snap
- test/unit/date-picker/__snapshots__/index.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/time-picker/__snapshots__/demo.test.js.snap
> fix: clearable of datepicker and timepicker

- CHANGELOG.md
> docs(version): release 0.10.2

- src/dialog/dialog.tsx
resolved #435 435
- fix(dialog): 修复 `dialog` 组件点击警告
> fix(dialog): fix inject warn

- src/steps/steps.tsx
- fix(steps): 修复 `readonly` 状态下依然可以点击
> fix(steps): add steps click disabled

- src/pagination/pagination.tsx
resolved #469
resolved #466
- fix(pagination): 修复 `onPageSizeChange` 和 `onCurrentChange` 事件参数
> fix(pagination): fix pagination params

- src/form/form.tsx
- fix(form): 修复空表单时候的 `reduce` 语法错误
> fix(form): fix form validate reduce error

- src/cascader/components/InputContent.tsx
- src/cascader/utils/inputContent.ts
- src/select/select.tsx
- src/time-picker/panel/index.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/time-picker/__snapshots__/demo.test.js.snap
过滤状态下的交互问题
- fix(cascader):
- 修复可过滤状态下的下拉面板拉起闪烁 #477
- 修复可过滤状态下的输入内容未被正常销毁 #478
- fix(time-picker):
- 修复此刻文案为空
- fix(select):
- 修复popup属性透传问题
> fix(cascader): fix filter interaction

- src/checkbox/checkbox-group-props.ts
- src/checkbox/checkbox.tsx
- src/checkbox/group.tsx
- src/checkbox/index.ts
- src/checkbox/props.ts
- src/checkbox/type.ts
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/checkbox/__snapshots__/demo.test.js.snap
- test/unit/checkbox/__snapshots__/index.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/select-input/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/demo.test.js.snap
- test/unit/select/__snapshots__/index.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/transfer/__snapshots__/demo.test.js.snap
- test/unit/tree/__snapshots__/demo.test.js.snap
Composition Api 重构计划 #58 
- 切换 `checkbox` 代码风格
> refactor(checkbox): refactor checkbox used by compositionAPI

- src/cascader/utils/cascader.ts
- fix(cascader): 修复value为number类型时无法回显
> fix:  cascader empty refresh

- CHANGELOG.md
- package.json
> docs(version): release 0.11.0

- src/color-picker/color-picker-panel.tsx
- src/color-picker/hooks.ts
- src/color-picker/interfaces.ts
- src/color-picker/panel/format/index.tsx
- src/color-picker/panel/format/inputs.tsx
- src/color-picker/panel/format/style/css.js
- src/color-picker/panel/format/style/index.js
- src/color-picker/panel/index.tsx
- src/color-picker/panel/linear-gradient.tsx
- src/color-picker/panel/style/css.js
- src/color-picker/panel/style/index.js
- src/color-picker/trigger.tsx
> fix: colorPicker reference

- examples/select-input/demos/autowidth-multiple.vue
- examples/select-input/demos/borderless-multiple.vue
before
after
- fix(select-input): demo样式修复
> fix: select-input style

- examples/dropdown/dropdown.md
> chore: modify dropdown minColumnWidth description

- examples/tree-select/demos/valuedisplay.vue
- src/select-input/useSingle.tsx
- src/tree-select/index.ts
- src/tree-select/interface.ts
- src/tree-select/props.ts
- src/tree-select/tree-select.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/tree-select/__snapshots__/demo.test.js.snap
重构 TreeSelect 为 Composition-api
- refactor(tree-select): 重构为 CompositionApi
> refactor(tree-select): refactor component

- src/input/input.tsx
resolved #501
- fix(input): 修复input type 传入无效
> fix:  input type

- script/test/generate-demo-test.js
- src/tree-select/tree-select.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/tree-select/__snapshots__/demo.test.js.snap
- test/unit/tree-select/__snapshots__/index.test.js.snap
- test/unit/tree-select/demo.test.js
- test/unit/tree-select/index.test.js
添加TreeSelect组件测试用例，覆盖率70%
- testtree-select): 添加TreeSelect组件单测用例
> test(tree-select): add test file

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
> ci: 添加release

- .github/release-drafter.yml
- CHANGELOG.md
- package.json
> chore: dump 0.11.1

- examples/upload/demos/custom-drag.vue
- src/upload/upload.tsx
1.自定义拖拽demo点击上传无效
- fix(upload): 修复upload中triggerUpload方法未正确导出
- fix(upload): 修复自定义拖拽上传demo中“点击上传”按钮无效
> fix(upload): expose syntax error

- package.json
> chore: dump 0.11.2

- examples/loading/demos/fullscreen.vue
resolves #548
https://github.com/Tencent/tdesign-vue-next/issues/548
- docs(loading): 修复一处示例文本和代码不相符的问题
> docs(loading): fix loading example description mismatch code

- src/slider/slider.tsx
fix #544
https://github.com/Tencent/tdesign-vue-next/issues/544
- fix(slider): 修复 inputNumberProps 未正常透传
> fix(slider): fix slider's inputNumberProps not passthrough

- examples/message/demos/placement.vue
- src/message/animation.ts
- src/message/const.ts
- src/message/message.tsx
- src/message/messageList.tsx
同：https://github.com/Tencent/tdesign-vue/pull/405
> feat(message): add fadeIn and fadeOut animation

- src/input/input.tsx
#556 
- fix(input): toggle password
> fix(input): password toggle

- package.json
> chore: dump 0.12.0

- CHANGELOG.md
> chore: 0.12.0 changelog

- examples/message/demos/close.vue
- src/message/message.tsx
- src/message/messageList.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/message/__snapshots__/demo.test.js.snap
- test/unit/message/index.test.js
https://github.com/Tencent/tdesign-vue-next/issues/58
1. 使用compositionAPI重构message和messageList组件。
2. 修复API错误onCloseClick。
3. message组件onDurationEnd事件测试用例优化。
1. 使用compositionAPI重构message和messageList组件。
2. 修复API错误onCloseClick。
3. message组件onDurationEnd事件测试用例优化。
> refactor message component used by composition

- examples/tabs/demos/base.vue
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/tabs/__snapshots__/demo.test.js.snap
> chore(tabs): update demo

- examples/time-picker/demos/hms.vue
- src/date-picker/date-picker.tsx
- src/time-picker/time-picker.tsx
- src/time-picker/time-range-picker.tsx
- 日常 bug 修复 修复time-picker手动情况value的异常
- 修复点击clear按钮 timepicker和datepicker样式的异常
- fix(timepicker):  修复time-picker手动清空value的异常
> fix(timepicker): clear value reset current time

- src/anchor/anchor-item.tsx
#574
- fix(anchor): 修复 `click` 事件参数不正确 
> fix: anchor click parmas

- src/hooks/slot.ts
- src/steps/constants.ts
- src/steps/index.ts
- src/steps/props.ts
- src/steps/step-item.tsx
- src/steps/steps.tsx
- src/steps/type.ts
- src/swiper/swiper.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/steps/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
#58 
- refactor(steps): 使用 `Compositon API` 重构 `steps` 组件
- fix(demo): 修复 `step` demo 中"带额外内容的步骤条"无法选中正确步骤的问题
- fix(steps): 修复 通过 `options` 属性动态添加步骤时，无法选中新增步骤的问题
> refactor(steps): refactor steps with vca

- CHANGELOG.md
- package.json
- src/slider/hooks/style/css.js
- src/slider/hooks/style/index.js
- src/slider/hooks/useSliderInput.tsx
> docs: release 0.12.2

- src/table/hooks/useRowSelect.tsx
- src/upload/useUpload.tsx
#601 #582
- fix(upload): 
- 修复上传失败状态流转问题 #582
- 修复上传文件尺寸限制计算问题 #601
> fix: upload fail  status

- src/drawer/drawer.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/drawer/__snapshots__/demo.test.js.snap
fix #609
fix(drawer): 修复 header 属性无效问题
> fix(drawer): 修复 header 属性无效问题

- src/textarea/textarea.tsx
- src/utils/dom.ts
- fix(textarea): 修复textarea组件在设置自动高度后，赋值后不高度不改变的问题(#597)
> 优化写法；修复textarea赋值后自动高度问题BUG(#597)

- examples/tabs/demos/custom.vue
> fix(tabs): correct demo

- src/date-picker/calendar-presets.tsx
https://github.com/Tencent/tdesign-vue-next/issues/512
点击的时候判断传入值类型，对非日期格式进行message提示
https://user-images.githubusercontent.com/3335540/164188107-2623a97c-a558-4ad2-b4d8-8589c4c316a5.mp4
- fix(datePicker): 修复当传入值为非日期格式的情况页面卡死的问题
> fix(DatePicker): 组件卡死问题(#512)

- src/tree-select/tree-select.tsx
1、修复：value=0时渲染异常问题，同步Vue2
- fix(tree-select): 修复value渲染异常问题
> fix(tree-select): 修复value渲染异常问题

- CHANGELOG.md
- package.json
> docs: release 0.13.0

- examples/dialog/dialog.md
- src/dialog/plugin.tsx
- src/dialog/props.ts
- src/dialog/type.ts
#625
#521
- fix(dialog): 修复 `alert` 类型错误
> fix: dialog ts error

- src/form/const.ts
- src/form/form-item.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/form/__snapshots__/demo.test.js.snap
- test/unit/input-number/__snapshots__/demo.test.js.snap
- test/unit/tree/__snapshots__/demo.test.js.snap
> fix: form helpNode staus error

- src/transfer/components/transfer-list.tsx
- src/transfer/components/transfer-operations.tsx
- src/transfer/components/transfer-search.tsx
- src/transfer/transfer.tsx
> fix: transfer checked

- examples/pagination/demos/base.vue
- examples/pagination/pagination.md
- examples/pagination/usage/props.json
- src/pagination/pagination.tsx
- src/pagination/props.ts
- src/pagination/type.ts
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/pagination/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/transfer/__snapshots__/demo.test.js.snap
- feat(Pagination): 新增 showFirstAndLastPageBtn、showPreviousAndNextBtn api
> feat: 新增 showFirstAndLastPageBtn、showPreviousAndNextBtn api

- examples/pagination/pagination.md
- examples/pagination/usage/props.json
- src/pagination/pagination.tsx
- src/pagination/props.ts
- src/pagination/type.ts
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/config-provider/__snapshots__/demo.test.js.snap
- test/unit/pagination/__snapshots__/demo.test.js.snap
- test/unit/table/__snapshots__/demo.test.js.snap
- test/unit/transfer/__snapshots__/demo.test.js.snap
> [Pagination] 新增 showPageSize、showPageNumber API

- src/card/card.tsx
> fix: remove duplicate showDescription.value

- .github/workflows/auto-release.yml
背景：action 内推送代码没有触发新的工作流程
解决方案：使用非默认 TOKEN
> ci: 修复推送没有触发新的工作流程

- src/dialog/dialog.tsx
fix #788
- fix(dialog): 修复 dialog 初始化时滚动穿透问题
> fix(修复 dialog 初始化时滚动穿透问题): 修复 dialog 初始化时滚动穿透问题

- examples/dialog/demos/attach.vue
- src/dialog/dialog.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/dialog/__snapshots__/demo.test.js.snap
#695
- fix(dialog): 增加 `showInAttachedElement` 特性
> feat(dialog): add showInAttachedElement

- examples/tooltip/demos/duration.vue
- package.json
- src/popup/popup.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/tooltip/__snapshots__/demo.test.js.snap
> feat(tooltip): 优化定时消失 demo

- src/tabs/tab-nav.tsx
resolve #658 
- fix(tabs): 修正右箭头出现的时机
> fix(tabs): recalculate right arrow condition when navs has changed

- .github/workflows/auto-release.yml
- CHANGELOG.md
> chore: 修复changelog的插入

- src/input-number/input-number.tsx
- src/input-number/useComponentComputed.ts
- src/input-number/useInputNumberAction.ts
#707 
- fix(input-number): 修复input-number重构hook使用错误出现的问题
> fix(input-number): wrong usage of input-number's hooks

- examples/tooltip/demos/duration.vue
- examples/tooltip/demos/mouse.vue
- examples/tooltip/tooltip.md
- examples/tooltip/usage/props.json
- src/popup/popup.tsx
- src/tooltip/props.ts
- src/tooltip/tooltip.tsx
- src/tooltip/type.ts
- src/tooltip/util.ts
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/tooltip/__snapshots__/demo.test.js.snap
- test/unit/tooltip/demo.test.js
#630
- fix(tooltip): support set placement by mouse
> feat(tooltip): support set placement by mouse

- examples/config-provider/config-provider.md
- src/config-provider/type.ts
- src/table/interface.ts
- fix(ConfigProvider): 修复`animation`属性`exclude`和`include`在TS中都必填的问题
- fix(Table): `renderExpandedRow`为非必填
> fix: ts type

- examples/dialog/dialog.md
https://github.com/Tencent/tdesign-react/issues/713
https://github.com/Tencent/tdesign-common/issues/448
该问题来自于 tdesign-common 的 md 文案修改。
tdesign-common/dialog 中删去了关于 “插件函数式调用” 的相关公共描述。理由是该公共描述涉及 vue 特定的语法糖，从而在 tdesign-react 的网站中描述会使读者产生困惑。
根据 @[Kyrielin](https://github.com/HQ-Lin) 的 [描述](https://github.com/Tencent/tdesign-react/issues/713#issuecomment-1120184435)，需从 common 仓库删除，在 [tdesign-vue](https://github.com/Davont/tdesign-vue) 本仓库中自维护 。
> 备注：**该 PR 不会对 文案本身产生任何修改，只涉及 md 文案引用方式。**
- docs(Dialog): 更新 dialog “插件函数式调用”的描述
> docs(dialog): 更新 dialog “插件函数式调用”的描述

- package.json
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/input-number/__snapshots__/demo.test.js.snap
- test/unit/input-number/__snapshots__/index.test.js.snap
- test/unit/slider/__snapshots__/demo.test.js.snap
- 新特性提交 更新图标 新增`file-icon`图标 修改部分图标路径
- feat(Icon): 更新图标 新增`file-icon`图标 调整`file-excel`、`file-pdf`、`file-powerpoint`、`file-unknown`、`file-word`和`star-filled`图标的绘制路径
> chore: update icon

- src/time-picker/time-range-picker.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/time-picker/__snapshots__/demo.test.js.snap
- 日常 bug 修复 
- #721 
- fix(time-picker): time-range-picker suffix icon丢失问题
> fix(timepicker): range picker suffix icon

- src/steps/steps.tsx
- test/ssr/__snapshots__/ssr.test.js.snap
- test/unit/steps/__snapshots__/demo.test.js.snap
> fix: 修复 steps extra 渲染问题

- src/table/hooks/useColumnController.tsx
- fix(Table): 修复 多级表头 + 列配置 综合示例中，列数量超出一定限制时报错，[issue#713](https://github.com/Tencent/tdesign-vue-next/issues/713)
> fix(table): uncaught (in promise) RangeError: Invalid array length #713

- test/unit/config-provider/__snapshots__/demo.test.js.snap
> chore: remove conflict

- src/popup/popup.tsx
fix(popup): add `zIndex` api
fix(popup): 修复设置 `destroyOnClose` 后可能出现的异常抖动
> fix(popup): add `zIndex` api

- examples/anchor/demos/container.vue
https://github.com/Tencent/tdesign-common/pull/464
> feat(anchor): 增加 demo 演示功能

- src/menu/menu.tsx
#663 
- fix(menu): 修复 width 不生效的问题
> fix(menu): using width correctly

- src/utils/render-tnode.ts
- test/snap/__snapshots__/csr.test.js.snap
- test/unit/progress/index.test.jsx
- test/unit/tag/__snapshots__/index.test.jsx.snap
- test/unit/tag/index.test.jsx
- test/unit/tree-select/__snapshots__/index.test.jsx.snap
- fix(test): renderTNode 默认参数和 tag 组件单元测试用例修复
> fix: renderTNode and tag test case fix

- CHANGELOG.md
- package.json
> docs: release 0.15.1

- src/swiper/style/index.js
- 组件样式/交互改进 替换swiper样式路径
- 关联Common改动 https://github.com/Tencent/tdesign-common/pull/476
> chore: replace swiper style path

- src/form/form.tsx
- src/upload/image.tsx
- src/upload/upload.tsx
- fix(form): 修复表单重置 `onReset` 不传会报错 ([issue #860](https://github.com/Tencent/tdesign-vue-next/issues/860)), ([issue #856](https://github.com/Tencent/tdesign-vue-next/issues/856))
- fix(upload): 修复 `placeholder` 在 `image` 模式下不生效 ([issue #853](https://github.com/Tencent/tdesign-vue-next/issues/853))
> fix: form reset fun

- src/transfer/components/transfer-list.tsx
同步修复来自 Vue2 版本的问题： https://github.com/Tencent/tdesign-vue/pull/893
- fix(Transfer): 修复列表数量变化时的页码展示问题
> fix(transfer): update current page when total size change

- src/form/const.ts
- src/form/form-item.tsx
- src/form/form.tsx
- src/form/type.ts
- fix(form): 修复实例方法 `reset` 参数不生效的问题
- fix(form): `reset` 和 `submit` 现在会调用原生 `form` 中的方法
> fix(form): reset & submit instance func

- .github/workflows/tag-push.yml
- CHANGELOG.md
- package.json
> docs: release 0.15.2

- src/input-number/useInputNumberAction.ts
- src/input-number/useInputNumberTools.ts
#791 
- fix(InputNumber): 修复必填问题
> fix(input-number): input empty value

- src/button/button.tsx
> fix(components): [button] change ref

- CHANGELOG.md
- package.json
> docs: release 0.15.3

- site/plugin-doc/md-to-vue.js
> fix: 修复 windows 下usage 路径报错问题

- package.json
- site/src/components/components.jsx
- site/src/main.js
- 新特性提交 主题配置生成器
- 关联PR https://github.com/Tencent/tdesign-common/pull/487
- 解决用户自定义组件库主题的困难
- 新增主题配置生成器web component挂件
- feat: 新增主题配置生成器 
> feat(site): add theme generator

- src/menu/submenu.tsx
#882
#837
#832  
- fix(Menu): 修复暗黑模式下 popup 样式问题
- fix(Menu): 修复箭头方向错误的问题
> fix(menu): calc nest or not correctly

- CHANGELOG.md
- package.json
> docs: release 0.15.4

- src/popup/container.tsx
- src/popup/popup.tsx
https://github.com/Tencent/tdesign-vue-next/issues/889
- feat(popup): 支持动态设置 trigger & placement
- fix(popup): 修复初始化 visible 为 true 时的定位抖动
> feat(popup): 支持动态设置 trigger & placement

- examples/date-picker/demos/custom-icon.vue
- src/date-picker/date-picker.tsx
https://github.com/Tencent/tdesign-vue-next/issues/733
datepicker enable-time-picker状态下，prefixIcon不起作用
- fix(datepicker): enable-time-picker状态下，prefixIcon不起作用
> fix(date-picker): enable-time-picker状态下，prefixIcon不起作用

- src/date-picker/date-picker.tsx
- src/date-picker/props.ts
https://github.com/Tencent/tdesign-vue-next/issues/754
[DatePicker] separator日期分隔符属性失效
修复datepicker separator日期分隔符属性失效问题
- fix(datepicker): 修复datepicker separator日期分隔符属性失效问题
> fix(date-picker): fix separator bug

- package.json
> feat: update dep

- script/init/index.js
chore(script): init check component name is not emtry
> chore(script): init check component name

- package.json
> chore: hide theme generator on mobile device

- examples/tabs/tabs.md
- docs(tabs): remove repeat attributes
> docs(tabs): remove repeat attributes

- src/date-picker/DateRangePicker.tsx
- src/date-picker/hooks/useFormat.ts
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useRangeValue.ts
- src/date-picker/panel/RangePanel.tsx
- src/date-picker/panel/SinglePanel.tsx
> feat: 优化 datepicker 交互

- src/tabs/tab-nav.tsx
无
- fix(tabs): 修复 panels 变化时，往右按钮不出现的问题
> fix(tabs): calc arrow button after panels changed

- src/dialog/dialog.tsx
- feat(Dialog): 新增`preventScrollThrough`
> feat(dialog): add preventScrollThrough

- CHANGELOG.md
- package.json
> docs: release 0.16.1

- examples/radio/usage/props.json
- site/docs/getting-started.md
- site/docs/starter.md
> docs: release beta

- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/base/Header.tsx
- src/date-picker/panel/RangePanel.tsx
- src/date-picker/panel/SinglePanel.tsx
> feat: 优化datepicker 逻辑

- src/select/helper.ts
- src/select/hooks.ts
- src/select/select-panel.tsx
- src/select/select.tsx
- fix(Select): 修复 `options content`  属性向下透传问题
> fix: select options

- src/tree-select/tree-select.tsx
closed #1017
#1017 
- fix(tree-select): 修改因传入 treeProps.keys.children 不生效的问题
> fix(tree-select): fix treeProps.keys bug

- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
#1037 
- fix(date-picker): 处理`disabled`无法生效的问题
> Fix the disabled of date-picker is invalid

- examples/notification/notification.md
[关于Notification中文档的错误 #1045 ](https://github.com/Tencent/tdesign-vue-next/issues/1045)
N/A
> docs: 修复文档错误（#1045）

- src/range-input/range-input.tsx
- fix(DatePicker): 修复 clearable 失效问题
> fix: 修复 clearable 失效问题

- .husky/prepare-commit-msg
- package.json
- site/src/components/components.jsx
- src/time-picker/style/index.js
- 升级主题生成器 改名规范为`<td-theme-generator />` 减少控制台告警
- windows bypass husky prepare-commit-msg
- 修改timepicker样式路径
> chore: infrastructure 

- src/form/form-item.tsx
before:
after:
- fix(Form): 修复校验规则为空时，校验信息不清空的问题
> fix(form): dynamic rules validate status

- src/checkbox/group.tsx
- src/hooks/slot.ts
- src/select/hooks.ts
- src/select/select.tsx
- src/steps/steps.tsx
- src/swiper/swiper.tsx
- fix(Select): 修复分组插槽使用在列表尾部会产生多余渲染，修复筛选状态交互。([issue #1048](https://github.com/Tencent/tdesign-vue-next/issues/1048))
> fix: select filter

- CHANGELOG.md
- package.json
> docs: release 0.17.1

- CHANGELOG.md
- package.json
- site/docs/getting-started.md
> chore: update docs

- src/select/hooks.ts
- src/select/option.tsx
- fix(Select): 修复 `options` 属性 `disabled` 禁用选项不起作用 ([#1093](https://github.com/Tencent/tdesign-vue-next/issues/1093))
> fix: select disabled

- src/table/base-table.tsx
- src/table/hooks/useAffix.ts
- fix(table): 表头吸顶显示问题
- fix(table): `paginationAffixedBottom` 支持配置 Affix 组件全部特性
> feat(table): paginationAffixProps & affixed Header

- src/upload/useUpload.tsx
closed #1076
[https://github.com/Tencent/tdesign-vue-next/issues/1076](https://github.com/Tencent/tdesign-vue-next/issues/1076)
- fix(Upload): 在每次上传前将错误提示数据重置
> fix(upload): 在每次上传前将错误提示数据重置

- examples/date-picker/usage/date-picker-props.json
- src/date-picker/DatePicker.tsx
- src/date-picker/DatePickerPanel.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/panel/ExtraContent.tsx
> feat: 修复响应式问题

- src/date-picker/DatePicker.tsx
- src/date-picker/hooks/useSingle.tsx
https://github.com/Tencent/tdesign-vue-next/issues/1113
- fix(DatePicker): 修复 `clearble` 响应式问题
> fix: 修复 clearble 响应式问题

- src/dialog/dialog.tsx
> fix: 修复 dialog 滚动失效问题

- examples/table/demos/filter-controlled.vue
- src/table/hooks/useRowspanAndColspan.ts
- src/table/hooks/useTreeData.tsx
- fix(table): 修复动态数据合并元格问题，[issue#1070](https://github.com/Tencent/tdesign-vue-next/issues/1070)
- fix(table): 修复树形结构设置 `indent = 0` 无效问题，[issue#909](https://github.com/Tencent/tdesign-vue-next/issues/909)
> feat(table): 1. 修复动态数据合并单元格问题；2. 表格可筛选功能补充日期面板使用

- CHANGELOG.md
- package.json
> docs: release 0.17.3

- src/hooks/slot.ts
- src/space/space.tsx
- fix(Space): 通过FOR循环的内容 没有实现间隔效果 ([issue #1084](https://github.com/Tencent/tdesign-vue-next/issues/1084))
> fix: space slot length

- examples/date-picker/date-picker.md
- src/date-picker/DatePicker.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/date-range-picker-panel-props.ts
- src/date-picker/date-range-picker-props.ts
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useRangeValue.ts
- src/date-picker/hooks/useSingle.tsx
- src/date-picker/hooks/useSingleValue.tsx
- src/date-picker/panel/PanelContent.tsx
- src/date-picker/panel/RangePanel.tsx
- src/date-picker/panel/SinglePanel.tsx
- src/date-picker/props.ts
- src/date-picker/type.ts
- fix(DatePicker): 修复日期格式化问题
- feat(DatePicker): 新增 `panelPreselection api`
> feat: 新增 panelPreselection api & 修复日期格式化问题

- src/time-picker/panel/single-panel.tsx
优化前
https://user-images.githubusercontent.com/26377630/177519272-a763e51c-90ad-4493-ae54-55cd5f0ab43c.mp4
优化后
https://user-images.githubusercontent.com/26377630/177519279-c679641e-ea83-4b4b-9052-e4d0eebefd3c.mp4
- fix(TimePicker): 优化可输入模式的使用体验 避免高频输入场景与滚动事件重复更新 `value` 的异常
> fix(time-picker): allow input perform

- src/date-picker/DatePicker.tsx
- src/date-picker/DatePickerPanel.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/date-picker-panel-props.ts
- src/date-picker/date-range-picker-panel-props.ts
- src/date-picker/index.ts
- src/date-picker/props.ts
- src/table/editable-cell.tsx
> refactor(date-picker): props

- .github/workflows/pr-auto-link.yml
- chore(CI): 新增PR合并后自动为相关issue添加标签的CI
> CI: 新增PR合并后自动为相关issue添加待发布标签的CI

- src/date-picker/DateRangePicker.tsx
> feat: 优化面板月份展示

- src/transfer/components/transfer-list.tsx
#1175 
- fix(Transfer): 全选应该只选择搜索后的结果
> fix(components): [transfer] only select search results

- .github/workflows/pr-auto-link.yml
> ci: 改用仓库自身的Token

- examples/table/usage/index.vue
- script/generate-usage/config.js
- feat(Table): 优化 table live demo
> feat: 优化 table live demo

- src/date-picker/DatePicker.tsx
- feat(DatePicker): 支持面板年月动态响应 value 变化
> feat: 支持面板年月动态响应 value 变化

- src/input-number/useComponentComputed.ts
#1208 
- fix(InputNumber): 修复初始化时对 `null` 及字符串校验异常
> fix(input-number): 初始化时对null及字符串校验异常

- examples/table/demos/editable-row.vue
- src/input/useInputWidth.ts
- fix(Input): 修复 `autowidth` 表现异常 ([issue #1212](https://github.com/Tencent/tdesign-vue-next/issues/1212))
> fix: input auto width

- CHANGELOG.md
- package.json
- docs: release 0.17.5 version
> docs: release 0.17.5

- test/unit/tree/index.test.jsx
https://github.com/Tencent/tdesign-vue-next/issues/1204
优化单测
> test(unit): tree test optimization

- src/swiper/swiper.tsx
#1223 
- fix(Swiper): 动态修改 `swiper item` 会出现 `vue` 警告
> fix(components): [swiper] fix swiper item duplicate key warn

- src/date-picker/DatePicker.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- src/select-input/useOverlayStyle.ts
- fix(`DatePicker`): 修复重置日期后面板月份未重置问题
> fix: 修复重置日期后面板月份未重置问题

- src/form/form-item.tsx
#1267 
- fix(Form): 修复 `help` 插槽不生效的问题([issue #1267](https://github.com/Tencent/tdesign-vue-next/issues/1267))
> fix: help插槽不渲染问题

- CHANGELOG.md
- package.json
> docs: release 0.18.1

- src/badge/badge.tsx
- src/dialog/dialog.tsx
- src/drawer/drawer.tsx
- fix: 修复`dialog`、`drawer`中部分节点未使用classPrefix导致的替换prefix样式异常的问题
> fix: prefix replace

- src/cascader/core/helper.ts
fix(Cascader): 修复在异步获取 `option` 的情况下，参数校验导致用户行为异常
> fix: cascader value check

- examples/upload/demos/request-method.vue
- src/tabs/tab-nav.tsx
- src/upload/hooks.tsx
- src/upload/upload.tsx
- fix(Tabs): 修复 `tabpanel` 组件的 `label` 不能根据函数进行自定义展示 ([issue #1311](https://github.com/Tencent/tdesign-vue-next/issues/1311))
- feat(Upload): 增加 `setPercent ` 实例方法用于满足自定义上传方法时设置上传进度([issue #1266](https://github.com/Tencent/tdesign-vue-next/issues/1266))
- feat(Upload): 修复 ` draggable` 和 `multiple` 组合使用时组件无输出([issue #1326](https://github.com/Tencent/tdesign-vue-next/issues/1326))
> fix: upload some issues

- src/menu/submenu.tsx
#1243 , #1312 
- fix(Menu):  使用 `relatedTarget` 标准属性兼容浏览器差异，修复在火狐浏览器无法收起的问题 ([issue #1312](https://github.com/Tencent/tdesign-vue-next/issues/1312)), ([issue #1243](https://github.com/Tencent/tdesign-vue-next/issues/1243)) ([issue #1198](https://github.com/Tencent/tdesign-vue-next/issues/1198))
> fix(menu): 使用relatedTarget标准属性兼容浏览器差异

- examples/rate/rate.en-US.md
- examples/rate/rate.md
- src/rate/props.ts
- src/rate/type.ts
> feat: 更新 Rate api

- test/unit/slider/base.test.jsx
- test/unit/slider/behavior.test.jsx
补充slider关于disabled、onChange行为层单元测试
- test(slider): 补充slider单元测试
> test(unit): add slider unit test

- examples/input/input.md
- examples/textarea/textarea.md
- src/textarea/textarea.tsx
- #1338 
- feat(Textarea): 增加 `focus` 和 `blue` 实例方法
- feat(Input): 增加 `focus` 和 `blue` 实例方法
> feat: 为Textarea组件暴露方法

- examples/input/input.en-US.md
- examples/input/input.md
- examples/textarea/textarea.en-US.md
- examples/textarea/textarea.md
- src/dialog/type.ts
- src/drawer/type.ts
- src/dropdown/dropdown.tsx
- src/select/select.tsx
- src/tag-input/hooks/useDragSorter.ts
- src/tag-input/interface.ts
- src/tag-input/type.ts
- src/tag-input/useTagList.tsx
- fix(Dialog): 修复 `confirm-btn` 类型问题 ([issue #1347](https://github.com/Tencent/tdesign-vue-next/issues/1347))
- fix(Dropdown): 修复 `popupElem` 为空时的组件内部报错 ([issue #1344](https://github.com/Tencent/tdesign-vue-next/issues/1344))
- fix(TagInput): 修复 `taginput` 空值时缺失 `padding` 的问题 @uyarn 
- chore(TageInput): 非 API 平台生成内容迁移到 `interface` 文件
> fix: issues  0806

- CHANGELOG.md
- package.json
> docs: release 0.19.1

- src/table/base-table.tsx
- src/table/hooks/useEditableRow.ts
- src/table/hooks/useRowspanAndColspan.ts
- src/table/tfoot.tsx
> feat(table): add footerSummary to props

- examples/config-provider/config-provider.en-US.md
- examples/config-provider/config-provider.md
- src/config-provider/type.ts
- src/date-picker/hooks/useTableData.tsx
- feat(`DatePicker`): 支持季度国际化配置
> feat(DatePicker): 支持季度国际化配置

- examples/popup/popup.en-US.md
- examples/popup/popup.md
- src/cascader/cascader.tsx
- src/color-picker/color-picker.tsx
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- src/menu/submenu.tsx
- src/popup/popup.tsx
- src/popup/props.ts
- src/popup/type.ts
- src/range-input/range-input-popup.tsx
- src/select-input/select-input.tsx
- src/select-input/useOverlayInnerStyle.ts
- src/slider/hooks/useSliderTooltip.tsx
- src/time-picker/time-picker.tsx
- src/time-picker/time-range-picker.tsx
- src/tooltip/tooltip.tsx
-  feat(`Popup`): `overlayStyle` 调整为控制 `t-popup` 层级，新增 `overlayInnerStyle` 控制 `t-popup__content` 层级与原先 `overlayStyle` 效果一致。
> feat: popup 支持 overlayInnerStyle

- package.json
- https://github.com/Tencent/tdesign-icons/issues/36
- https://github.com/Tencent/tdesign-icons/issues/33
- feat(Icon): 新增`qq`、`wechat`、`wecom`、`relativity`和`pin-filled`等图标
> feat: add new icons

- src/date-picker/base/Header.tsx
- src/select/select.tsx
> fix: 修复 datepicker 下拉样式问题

- src/hooks/useListener.tsx
Tabs 选项卡在nuxt3 ssr应用中报window is not defined：https://github.com/Tencent/tdesign-vue-next/issues/1262
具体的背景和解决方案在 https://github.com/Tencent/tdesign-vue-next/issues/1262 中有详述
- fix(Tabs): 修复 `Tabs` 选项卡在 `nuxt3 ssr` 应用中报 `window is not defined`
> fix(taps): tabs ssr window not defined 

- src/popup/popup.tsx
- src/utils/dom.ts
https://github.com/Tencent/tdesign-vue-next/issues/1227
- fix(Popup): 修复嵌套使用点击 trigger 元素时异常关闭 ([issue #1227](https://github.com/Tencent/tdesign-vue-next/issues/1227))
> fix(popup): use capturing listener to improve robustness

- CHANGELOG.md
- package.json
> docs: release 0.20.0

- src/date-picker/DatePicker.tsx
- src/date-picker/DateRangePicker.tsx
- fix(`DatePicker`): 修复有值时面板切换失效问题
> fix: 修复有值时面板切换失效问题

- CHANGELOG.md
- package.json
> docs: release 0.20.1

- src/table/hooks/useFixed.ts
- fix(Table): 修复窗口变化时，固定列阴影未更新问题 ([issue #1289](https://github.com/Tencent/tdesign-vue/issues/1289))
> fix(table): refresh table on resize without fixedHeader

- src/drawer/hooks.ts
- fix(Drawer): 修复拖拽改变抽屉高度时可超出屏幕的问题
> fix(drawer): 修复拖拽改变抽屉高度时可超出屏幕的问题

- src/date-picker/DateRangePicker.tsx
- src/date-picker/panel/PanelContent.tsx
- feat(`DatePicker`): 调整默认展示时间为 `00:00:00`
> feat: 调整默认展示时间为 00:00:00

- src/hooks/useDragSort.tsx
- fix(Tabs): 修复 `card` 主题下 `onDragSort` 的 `targetIndex` 参数不正确的问题
> fix(tabs): 修复card主题下onDragSort的targetIndex参数不正确的问题

- src/breadcrumb/breadcrumb-item.tsx
[#1460 ](https://github.com/Tencent/tdesign-vue-next/issues/1460)
- fix(breadcrumb): 修复了设置disabled属性后仍触发点击事件的问题
> fix(breadcrumb): 修复了设置disabled属性后仍触发点击事件的问题

- test/unit/breadcrumb/index.test.jsx
#768
- test(Breadcrumb): 增加 `breadcrumb` 单元测试
> test(unit): test(unit): add breadcrumb unit test

- src/tree/hooks/useExposeFunc.ts
#1428 
- fix(Tree): 修正 `setItem` 无法正确 展开，高亮，选中节点 ([issue #1428](https://github.com/Tencent/tdesign-vue-next/issues/1428))
> fix(tree): 修正 setItem 无法正确 展开，高亮，选中 节点

- examples/config-provider/config-provider.md
- docs: 新增替换`classPrefix`使用组件库的文档
> chore: add docs for replace classprefix

- src/select/hooks/usePanelVirtualScroll.ts
- src/select/select-panel.tsx
> fix(select): optional value

- site/src/components/stackblitz/content.js
https://github.com/Tencent/tdesign-vue-next/issues/1478
- docs: add stackblitz playground less dep
> docs: stackblitz playground add less dep

- CHANGELOG.md
- package.json
> docs: release 0.20.2

- examples/table/demos/editable-cell.vue
- src/table/primary-table.tsx
- test/snap/__snapshots__/csr.test.js.snap
[#1488 ](https://github.com/Tencent/tdesign-vue-next/issues/1488)
- fix(table): 修复了editableCellState表现与预期相反的问题
> fix(table): 修复了editableCellState表现与预期相反的问题

- src/date-picker/panel/ExtraContent.tsx
- fix(DatePicker): 修复了 `TExtraContent` 组件中的 `selectedValue Props` 定义不正确的问题 ([#1508 ](https://github.com/Tencent/tdesign-vue-next/issues/1508))
> fix(DatePicker): 修复了TExtraContent组件中的selectedValue Props定义不正确的问题

- examples/popconfirm/demos/describe.vue
组件【Popconfirm 气泡确认框】样式优化: https://github.com/Tencent/tdesign/issues/191
样式优化
- style(Popconfirm): Popconfirm 样式优化
> style(popconfirm): popconfirm demo style

- src/cascader/cascader.tsx
https://github.com/Tencent/tdesign-vue-next/issues/1521
- fix(cascader): single mode clearable
> fix(cascader): single mode clearable

- package.json
> chore: 优化站点 tab 切换滚动条进度体验

- examples/calendar/demos/events.vue
针对issue：https://github.com/Tencent/tdesign-vue-next/issues/1526，优化了一下日历组件事件示例代码。
> docs(calendar): 更新日历组建事件示例代码

- src/input/input.tsx
feat(input): 优化 `clearable` 按钮显示逻辑区分 `password` 输入框
> feat(input): 优化 `clearable` 按钮显示逻辑

- site/docs/getting-started.md
当输入分页页数时，从111往1回删 会触发inputnumber的bug '1'<1 导致error样式
- fix(InputNumber): 修复 `string` 与 `number` 比较错误及其导致的分页组件样式异常的问题 ([common#784](https://github.com/Tencent/tdesign-common/pull/784))
- docs: 更新使用说明文档内容及结构
> fix(inputnumber): string and number compare

- package.json
> docs: release 0.20.3

- examples/date-picker/demos/panel.vue
- src/date-picker/DatePickerPanel.tsx
- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/base/Header.tsx
- fix(DatePicker): 修复 `cell-click` 事件失效问题
> fix: 修复 cell-click 事件失效问题

- src/select/select-panel.tsx
- fix(Select): 修复 `creatable` 模式下的 `filter` 能力
> fix(select): 修复 creatable 模式下的 filter 能力

- src/form/type.ts
fix(form): 修复 `Form` 实例方法类型 `FormInstanceFunctions` 可能为未定义的问题 ([issue #1481](https://github.com/Tencent/tdesign-vue-next/issues/1481))([issue #1491](https://github.com/Tencent/tdesign-vue-next/issues/1491))
> fix(form): update api

- src/input-number/useInputNumber.tsx
https://github.com/Tencent/tdesign-vue-next/issues/1545
- fix(InputNumber): 修复 `numbe`r 类型校验 `bug`
> fix(input-number): fixed number delete got string

- site/docs/getting-started.md
> fix(docs):reset.css path

- src/jumper/__tests__/__snapshots__/index.test.jsx.snap
- src/jumper/__tests__/index.test.jsx
- test(jumper): jumper unit test
> test(jumper): jumper unit test

- src/popup/popup.en-US.md
- src/popup/popup.md
- src/popup/popup.tsx
- src/popup/props.ts
- src/popup/type.ts
- feat(popup): add `delay` prop
- fix(popup): 修复子 `popup` 销毁时父级意外关闭
> feat(popup): add `delay` prop

- src/swiper/swiper.tsx
fix #1558 
- fix(Swiper):  修复动态渲染问题
> fix(swiper): dynamic rendering error

- src/cascader/components/Item.tsx
https://github.com/Tencent/tdesign-vue-next/issues/1570
- fix(cascader): option value number warning
> fix(cascader): option value number warning

- src/popup/popup.tsx
> fix(popup): fix potential memory leak

- src/table/_example/editable-cell.vue
https://github.com/Tencent/tdesign-vue-next/issues/1483
- docs(table): fixed editable cell error
> docs(table): fixed editable cell error

- site/src/components/base-usage.vue
closed #1600
#1600 
- fix(LiveDemo): 修复`slider` 垂直布局预览问题 (issue 1600[](https://github.com/Tencent/tdesign-vue-next/issues/1600))
> fix(slider): change usage container height 100%

- src/time-picker/panel/single-panel.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/1012
- fix(TimePicker): 修复部分设备滚动边界的跳动异常 ([issue #1012](https://github.com/Tencent/tdesign-vue-next/issues/1012))
> fix(timepicker): boundary scroll

- .github/workflows/typos-config.toml
- CHANGELOG.md
- package.json
> docs: release 0.20.5

- script/generate-usage/config.js
- src/tree/_usage/index.vue
- fix(LiveDemo): 修复 `tree` ` live demo` 问题
> chore: 修复 tree live demo 问题

- src/image-viewer/_example/multiple.vue
- chore(ImageViewer):  `demo` 优化
> fix(image-viewer): demo优化

- .gitignore
- package.json
- script/rollup.config.js
- feat: 支持es module 导出不带样式产物，调整 lib 包内容
> feat: 支持es module 导出不带样式产物，调整 lib 包内容

- src/dropdown/dropdown-menu.tsx
- fix(Dropdown): 修复树形结构下的 `onclick` 调用错误
> fix: dropdown item click

- src/table/base-table.tsx
- src/table/hooks/useColumnResize.ts
- src/table/hooks/useFixed.ts
- src/table/thead.tsx
https://github.com/Tencent/tdesign-vue/issues/1428
1. 允许多级表头调整列宽
2. 抽离公共代码
3. 计算列宽时需要考虑列的minWidth设置
- fix(table): 优化列宽调整策略
> fix(table): 优化列宽调整策略

- src/date-picker/DateRangePicker.tsx
- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/hooks/useRange.tsx
- feat(`DatePicker`): 支持二次更改时间选择器时可单次变更日期
> feat: 支持二次更改时间选择器时可单次变更日期

- src/time-picker/panel/single-panel.tsx
- fix(TimePicker): 修复往前点击时间时滚动异常的问题
> fix(timepicker): click ahead time scroll to prev position

- src/date-picker/DatePicker.tsx
- feat(`DatePicker`): 默认时间调整成 00:00:00
> feat: 默认时间调整成 00:00:00

- src/jumper/props.ts
- fix(Jumper): 修复 `tips props` 类型缺失
> fix(jumper): 修复 tips props 类型缺失

- src/select-input/_example/autocomplete.vue
- src/select-input/_example/autowidth-multiple.vue
- src/select-input/_example/autowidth.vue
- src/select-input/_example/borderless-multiple.vue
- src/select-input/_example/borderless.vue
- src/select-input/_example/collapsed-items.vue
- src/select-input/_example/custom-tag.vue
- src/select-input/_example/excess-tags-display-type.vue
- src/select-input/_example/label-suffix.vue
- src/select-input/_example/multiple.vue
- src/select-input/_example/single.vue
- src/select-input/_example/status.vue
- src/select-input/_example/width.vue
- fix(Demos): 修复 `select-input` 示例展示 ([issue #1640](https://github.com/Tencent/tdesign-vue-next/issues/1640)) ([issue #1641](https://github.com/Tencent/tdesign-vue-next/issues/1641))
> fix: select-input demo style fix

- CHANGELOG.md
> chore: add 0.21.1 CHANGELOG

- package.json
> fix: 修复默认导入引用文件缺失问题

- script/generate-usage/config.js
- script/generate-usage/index.js
- src/form/_usage/index.vue
- src/select/_usage/index.vue
- src/swiper/_usage/index.vue
- src/table/_usage/index.vue
- src/watermark/_usage/index.vue
- src/watermark/_usage/props.json
- fix(LiveDemo): 修复 select LiveDemo 问题 ([issue #1679](https://github.com/Tencent/tdesign-vue-next/issues/1679))
- feat(LiveDemo): 添加 watermark LiveDemo
> fix: 修复live-demo select 选择后没有显示的问题

- site/vite.config.js
添加vite配置：`optimizeDeps.include`，提前进行依赖处理，避免出现二次预构建导致的页面`reload`
[相关链接](https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-include)
> build: add pre-building dependency include

- src/pagination/__tests__/index.test.jsx
#768 
- test(Pagination): 补充单元测试
> test(unit): add test for pagination

- src/select/select.tsx
- fix(Select): 修复 `clear` 清除操作，当前会设置 `value` 为空字符串 ([issue #1678](https://github.com/Tencent/tdesign-vue-next/issues/1678))
> fix: select clear value

- src/menu/_example/multiple.vue
- src/menu/const.ts
- src/menu/submenu.tsx
closed #1249
- fix(Menu): 修复 `menuItem` 过多时超出显示滚动条 ([issue #1249](https://github.com/Tencent/tdesign-vue-next/issues/1249))
- fix(Menu): 平铺式侧边导航，收起菜单，三级目录不展示 ([issue #1692](https://github.com/Tencent/tdesign-vue-next/issues/1692))([issue #1571](https://github.com/Tencent/tdesign-vue-next/issues/1571))
> fix(menu): menuItem超出显示滚动条

- CHANGELOG.md
- package.json
> docs: release 0.22.0

- src/collapse/__tests__/index.test.jsx
#768 
- test(Collapse): add unit test for collapse
> test(collapse): add unit test for collapse

- src/collapse/__tests__/index.test.jsx
- src/collapse/collapse-panel.tsx
closed #1703
#1703 
- test(Collapse): 增加单元测试用例
- fix(Collapse): 修复 `content api` 不支持 ([issue #1703](https://github.com/Tencent/tdesign-vue-next/issues/1703))
> fix(collapse): support content api and add unit testcase

- src/tag/tag.tsx
Closes #1710
- fix(tag): 修复 `tag` 中 `close` 事件冒泡([issue #1710](https://github.com/Tencent/tdesign-vue-next/issues/1710))
> fix(tag): 修复tag中close事件冒泡(#1710)

- CHANGELOG.md
- package.json
> docs: release 0.22.1

- src/dropdown/__tests__/index.test.jsx
> test-dropdown

- src/time-picker/time-picker.tsx
- src/time-picker/time-range-picker.tsx
https://github.com/Tencent/tdesign/issues/224
- style(TimePicker): 调整 `time-pick` 样式
> style: 调整time-pick样式

- src/dialog/dialog.tsx
- src/dialog/hooks.tsx
close #1737 
记录鼠标 click 的起点和落点并进行对比
- fix(Dialog): 修复在弹窗内按下鼠标,在蒙层中松开会关闭弹窗的问题
> fix(Dialog): 修复在弹窗内按下鼠标,在蒙层中松开会关闭弹窗的问题

- src/tag/__tests__/index.test.jsx
tag: add tag test
添加组件单元测试
- test(Tag): 增加 `tag` 单元测试
> test(unit): tag: add tag test

- src/table/base-table.tsx
- src/table/hooks/useFixed.ts
- src/upload/themes/style/css.js
- src/upload/themes/style/index.js
- https://github.com/Tencent/tdesign-vue-next/issues/1207
- fix(Table): 修复多种视图切换或表格变化的场景下 吸顶效果没有重新渲染计算的问题
> fix(table): update affix position when resize

- src/badge/__tests__/index.test.jsx
Badge: add badge test
新增组件单元测试
- test(Badge): 补充 `Badge` 组件单元测试
> test(unit): badge: add badge test

- src/date-picker/panel/RangePanel.tsx
- src/date-picker/panel/SinglePanel.tsx
- fix(`DatePicker`): 修复 disableDate 传入 lambda 函数被频繁触发问题
> fix: 修复 datepicker 传入 lambda 函数被频繁触发问题

- src/grid/__tests__/index.test.jsx
grid: add grid test
新增组件单元测试
test(Grid)：补充 `grid` 单元测试
> test(unit): grid: add grid test

- src/layout/__tests__/index.test.jsx
layout: add layout test
新增组件单元测试
-  test(Layout)：补充 `layout` 单元测试
> test(unit): layout: add layout test

- src/input-number/useInputNumber.tsx
- src/upload/_example/base.vue
- src/upload/hooks/useUpload.ts
https://github.com/Tencent/tdesign-common/pull/878
- fix(InputNumber): 输入中文或特殊符号时，清空数字为 `undefined`
- fix(Upload): 请求支持带上自定义 `headers`
> [Upload]headers support and input-number letters input

- src/upload/hooks/useUpload.ts
- fix(Upload): 恢复 `withCredentials` ([issue #1765](https://github.com/Tencent/tdesign-vue-next/issues/1765))
> fix(upload): add withCredentials

- src/date-picker/DatePicker.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/date-picker.en-US.md
- src/date-picker/date-picker.md
- src/date-picker/date-range-picker-props.ts
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- src/date-picker/props.ts
- src/date-picker/type.ts
- fix(DatePicker): 支持 `valueType api`
> feat: support valueType

- CHANGELOG.md
- package.json
> docs: release 0.23.1

- src/upload/constants.ts
- src/upload/index.ts
- src/upload/interface.ts
- src/upload/themes/custom-file.tsx
- src/upload/themes/dragger-file.tsx
- src/upload/themes/image-card.tsx
- src/upload/themes/multiple-flow-list.tsx
- src/upload/themes/normal-file.tsx
- fix(Upload): 修复 `upload` 导出预期外的变量导致组件注册时出现告警
> fix: upload export interface

- src/radio/__tests__/index.test.jsx
新增组件单元测试
test(Radio): 补充 radio 单元测试
> test(unit): radio: add radio test

- src/checkbox/__tests__/index.test.jsx
新增组件单元测试
- test(Checkbox): 补充 checkbox 单元测试
> test(unit): checkbox: add checkbox test

- src/progress/__tests__/index.test.jsx
新增组件单元测试
- test(Progress): 补充 progress单元测试
> test(unit): progress: add progress test

- src/comment/__tests__/index.test.jsx
新增组件单元测试
- test(Comment): 补充 `comment` 单元测试
> test(unit): comment: add comment test

- src/list/__tests__/index.test.jsx
新增组件单元测试
- test(List): 补充 `list` 单元测试
> test(unit): list: add list test

- src/swiper/swiper.tsx
fix #1763 
- fix(Swiper): 修复卡片模式时，切换空白的问题([issue #1763](https://github.com/Tencent/tdesign-vue-next/issues/1763))
> fix(swiper): adjust the card switch

- src/dialog/__tests__/index.test.jsx
新增组件单元测试
- test(Dialog): 补充 `dialog` 单元测试
> add dialog test

- src/date-picker/date-range-picker-props.ts
- fix(`DateRangePicker`): 兼容 `value`、`v-model` 传入 `undefined` 报错问题
> fix: 兼容 value、v-model 传入 undefined 报错问题

- src/input-number/__tests__/index.test.jsx
新增组件单元测试
- test(InputNumber): 补充 `input-number` 单元测试
> test(unit): input-number: add input-number test

- src/message/__tests__/index.test.jsx
新增组件单元测试
- test(Message): 补充 `message` 单元测试
> test(unit): add message test

- src/dropdown/_example/slot.vue
- src/dropdown/hooks/useDropdownOptions.ts
- https://github.com/Tencent/tdesign-vue-next/issues/1825
- fix(Dropdown): 修复插槽用法的使用缺陷 ([issue #1825](https://github.com/Tencent/tdesign-vue-next/issues/1825))
> fix(dropdown): item slot

- CHANGELOG.md
- package.json
> docs: release 0.24.1

- src/form/form-item.tsx
- feat(`Form`): 调整 `requiredMark` api 可独立控制星号展示
> feat: 调整 requiredMark api 可独立控制星号展示

- package.json
- src/guide/guide.md
- test/snap/__snapshots__/csr.test.js.snap
- https://github.com/Tencent/tdesign-vue-next/issues/1840
- https://github.com/Tencent/tdesign-vue-next/issues/1839
- chore: 修复文档渲染问题
- chore: 修复CI问题
> chore: fix guide docs render

- src/tooltip/__tests__/index.test.jsx
- src/tooltip/_example/arrow.vue
新增组件单元测试
- test(Tooltip): 补充 `tooltip` 单元测试
> test(unit): tooltip: add tooltip test

- src/select/select.tsx
- feat(select): 下拉框隐藏的时候清空筛选文本
> feat(select): 下拉框隐藏的时候清空筛选文本

- src/drawer/__tests__/index.test.jsx
新增组件单元测试
- test(Drawer): 补充 `drawer` 单元测试
> test(unit): drawer: add drawer test

- src/date-picker/DateRangePicker.tsx
- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/hooks/useRange.tsx
- fix(DatePicker): 修复 `range` 数据格式化异常问题
> fix: 修复 range 数据格式化异常问题

- src/dropdown/dropdown.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/1835
- fix(Dropdown): 修复`trigger`部分响应式丢失的问题
> fix(dropdown): fix trigger responsive

- src/table/_example/affix.vue
demo中吸顶表格在小窗口转变为大窗口时，宽度没有撑满容器
1. 移除demo css中的max-width: 800px限制
- fix(table): 移除demo中对吸顶表格的最大宽度限制
> fix(table): 移除demo中对吸顶表格的最大宽度限制

- src/transfer/__tests__/index.test.jsx
新增组件单元测试
- test(Transfer): 补充 transfer 单元测试
> test(unit): transfer: add transfer test

- src/popup/popup.tsx
https://github.com/Tencent/tdesign-vue-next/issues/1802
-fix(Popup): 修复 `destroyOnClose` 未能彻底清除 `DOM` 元素的 `bug`
> fix(popup): close destroy dom

- src/upload/interface.ts
- fix(Upload): 组件类型未导出 ([issue #1815](https://github.com/Tencent/tdesign-vue-next/issues/1815))
> fix: upload types

- package.json
> docs: release 0.24.2

- src/dropdown/dropdown-menu.tsx
- fix(Dropdown): 修复子节点文字省略功能丢失的问题
> fix(dropdown): no children item class

- package.json
Co-authored-by: @yilaierwang 
- feat: 主题生成器新增阴影配置 co-authored @yilaierwang
> feat: add boxshadow theme generator

- package.json
> chore: replace generator version

- src/date-picker/DateRangePicker.tsx
> fix(date-picker): 月份及季度选择时右侧面板展示修复

- src/upload/_example/image.vue
- src/upload/hooks/useUpload.ts
- src/upload/themes/dragger-file.tsx
- src/upload/themes/image-card.tsx
- src/upload/themes/multiple-flow-list.tsx
- src/upload/themes/normal-file.tsx
- fix(Upload): 修复 `name` 无效问题
- fix(Upload): 修复 `theme=file` `draggable=true` 时，拖拽无效问题，[issue#1559](https://github.com/Tencent/tdesign-react/issues/1559)
> [Upload] Some features and bugs

- site/src/components/components.jsx
- src/dropdown/__tests__/index.test.jsx
> chore: remove patch version from history options

- CHANGELOG.md
- package.json
> release: 0.24.3

- src/space/__tests__/index.spec.jsx
添加组件单元测试
- test(Space): 补充 `Space` 单元测试
> test: add space test

- src/icon/__tests__/index.spec.jsx
新增组件单元测试
- test(Icon): 补充 `Icon` 组件单元测试
> test(unit): add icon test

- src/image/__tests__/index.test.jsx
- src/image/_usage/index.vue
新增组件单元测试
- test(Image): 补充 `Image` 组件单元测试
> add image test

- src/jumper/__tests__/index.test.jsx
新增组件单元测试
- test(Jumper): 补充 `Jumper` 单元测试
> test(unit): add jumper test

- src/checkbox/checkbox.tsx
- fix(Select): 修复无法使用 `0` 作为 `value` ([issue #1928](https://github.com/Tencent/tdesign-vue-next/issues/1928))
- fix(CheckBox): 修复 `readonly` 属性没效果 ([issue #1928](https://github.com/Tencent/tdesign-vue-next/issues/1919))
> fix: checkbox readonly

- src/pagination/pagination.en-US.md
- src/pagination/pagination.md
- src/pagination/pagination.tsx
- src/pagination/props.ts
- src/pagination/type.ts
- src/table/_example/tree.vue
- src/table/enhanced-table.tsx
- src/table/hooks/useDragSort.ts
- src/table/thead.tsx
- fix(Table): 修复吸顶表头超出省略问题，[tdesign-vue#1639](https://github.com/Tencent/tdesign-vue/issues/1639)
- fix(Table): 提高 `dragSortOptions` 优先级，以便父组件自定义全部参数，[tdesign-react#1556](https://github.com/Tencent/tdesign-react/issues/1556)
- fix(Table): 本地分页表格中，使用拖拽排序，数据交换结果不正确，[tdesign-vue#1342](https://github.com/Tencent/tdesign-vue/issues/1342)
- feat(Pagination): 透传`selectProps` 和 `selectProps.popupProps` 到组件 `Pagination`，以便实现挂载节点等复杂场景需求， [tdesign-react#1611](https://github.com/Tencent/tdesign-react/issues/1611)
> [Table] some features and bugs

- package.json
- src/loading/plugin.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/1917
- fix(Loading): 修复部分场景 `v-loading` 异常的问题 ([issue #1917](https://github.com/Tencent/tdesign-vue-next/issues/1917))
> fix(loading): parentNode could be null

- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- fix(Datepicker): 修复 `popupProps.onVisibleChange` 方法不能正常触发的问题
> fix: datepicker popupProps onVisibleChange

- src/date-picker/DatePicker.tsx
> fix: 修复单选日期时间无法确定问题

- CHANGELOG.md
- package.json
> docs: release 0.24.4

- CHANGELOG.md
- package.json
> docs: release 0.24.5

- src/time-picker/_example/hms.vue
- src/time-picker/_example/range.vue
- src/time-picker/panel/props.ts
- src/time-picker/panel/single-panel.tsx
- src/time-picker/panel/time-picker-panel.tsx
- src/time-picker/props.ts
- src/time-picker/time-picker.en-US.md
- src/time-picker/time-picker.md
- src/time-picker/time-picker.tsx
- src/time-picker/time-range-picker-props.ts
- src/time-picker/time-range-picker.tsx
- src/time-picker/type.ts
- feat(TimePicker): 新增`onPick` API 用于处理每次选择时间的回调
- fix(TimePicker): 修复12小时制时分列首位的异常
> feat(TimePicker): add onPick API 

- site/src/components/stackblitz/index.vue
- src/image/image.tsx
- src/popup/_example/style.vue
- feat(Demo): `stackblitz` 默认打开 `.vue` 文件 ([issue #1974](https://github.com/Tencent/tdesign-vue-next/issues/1974))
- fix(Popup): 使用 `overlayInnerStyle` 定义定宽 ([issue #1970](https://github.com/Tencent/tdesign-vue-next/issues/1970))
- fix(Image): 修复 `error slot` 无效 ([issue #1961](https://github.com/Tencent/tdesign-vue-next/issues/1961))
> feat: update stack blitz nav url

- src/time-picker/__tests__/index.test.jsx
> chore: add timepicker unit test

- CHANGELOG.md
- package.json
> docs: release 0.24.6

- src/input-number/useInputNumber.tsx
- fix(InputNumber): `value` 支持受控
> fix(input-number): value controlled

- src/alert/alert.tsx
https://github.com/Tencent/tdesign-vue-next/issues/1990
- fix(Alert): 修复内嵌 `link` 时，`hover` 会导致 `alert` 消失
> fix(alert): child trigger transition end event

- src/table/enhanced-table.tsx
- fix(Table): 修复 `EnhancedTable` 树形结构，在编译后的运行过程中缺少实例方法（开发环境正常）问题，[issue#1999](https://github.com/Tencent/tdesign-vue-next/issues/1999)
> fix(table): enhanced table missing instance functions

- helper/attributes.json
- helper/tags.json
- helper/web-types.json
- package.json
- docs: 编辑器代码提示文件 ([issue #1900](https://github.com/Tencent/tdesign-vue-next/issues/1900))  ([issue #1617](https://github.com/Tencent/tdesign-vue-next/issues/1617))
使用 `nom run api:helper 'VueNext(PC)' 1 finalProject` 输出相关文件到项目中
> docs: code helper tips

- src/watermark/watermark.tsx
- fix(Watermark): 修复异步获取 `watermark` `content`，水印不更新的问题
> fix(watermark): 修复异步获取 watermarkcontent，水印不更新的问题

- src/image-viewer/__tests__/__snapshots__/index.test.jsx.snap
- src/image-viewer/base/ImageViewerModal.tsx
- src/image-viewer/image-viewer.tsx
> feat: 修复 image-viewer 样式问题

- CHANGELOG.md
- package.json
> docs: release 0.24.7

- src/color-picker/panel/linear-gradient.tsx
修复渐变滑竿滑动后导致picker自动关闭的问题
- fix(ColorPicker): 修复渐变滑竿滑动后导致 `picker` 自动关闭的问题
> fix(color-picker): 修复渐变滑竿滑动后导致picker自动关闭的问题

- src/tag-input/_example/custom-tag.vue
#1950 
示例代码，上下间距没对称，上宽下窄
- fix(TagInput): 修复 `tag-input` 示例代码上下间距不对称问题
> fix(tag-input): 修复tag-input示例代码上下间距不对称问题

- src/input-number/_example/center.vue
- src/input-number/input-number.en-US.md
- src/input-number/input-number.md
- src/input-number/props.ts
- src/input-number/type.ts
- src/input-number/useInputNumber.tsx
- feat(InputNumber): 支持 `allowInputOverLimit`，用于设置是否允许输入数字超过 `max` `min` 范围的值
- fix(InputNumber): 修复上个版本无法输入小数点问题
> feat(input-number): support allowInputOverLimit

- src/select-input/_example/multiple.vue
- chore(SelectInput): `demo` 原生滚动条样式改为内置样式
> chore(select-input): demo原生滚动条样式改为内置样式

- src/date-picker/base/Table.tsx
> fix: 修复周选择器高亮错误问题

- src/input-number/useInputNumber.tsx
- feat(InputNumber): 新增和减少按钮支持 `allowInputOverLimit`
> feat(input-number): allowInputOverLimit

- CHANGELOG.md
- package.json
> docs: release 0.24.9

- src/table/editable-cell.tsx
- fix(Table): 可编辑行，修复因没有监听数据变化，出现的校验不通过问题，[tdesign-vue#1822](https://github.com/Tencent/tdesign-vue/issues/1822)
> fix(table): editable cell

- src/dropdown/dropdown.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2044
- fix(Dropdown): 修复多次点击下拉菜单选项且开启 `hideAfterClick` 后无法弹出菜单的异常
> fix(dropdown): fix dropdown render fail after click item

- src/menu/submenu.tsx
https://github.com/Tencent/tdesign-vue-next/issues/2035
- fix(Menu):  修复 `submenu` 子菜单左右间距不一致
> fix(submenu): 子菜单左右间距不一致

- src/dialog/dialog.en-US.md
- src/dialog/dialog.md
- src/message/message.en-US.md
- src/message/message.md
- src/message/props.ts
- src/message/type.ts
- src/notification/notification.en-US.md
- src/notification/notification.md
- src/notification/props.ts
- src/notification/type.ts
- docs: 更新 Message/Notification/Dialog 等组件文档
> 更新 Message/Notification/Dialog 等组件文档

- src/auto-complete/_example/base.vue
- src/auto-complete/auto-complete.tsx
- src/auto-complete/option-list.tsx
- [] 新特性提交
- fix(AutoComplete): 支持使用 `triggerElement` 自定义 `AutoComplete` 的触发元素
> fix(auto-complete): support triggerElement

- src/collapse/_example/other.vue
- src/dialog/dialog.tsx
- src/drawer/drawer.tsx
- fix(Drawer): 修复 `drawer` 动画效果
> fix: 修复 drawer 动画效果

- CHANGELOG.md
- package.json
> docs: release 0.25.0

- src/config-provider/config-provider.tsx
- src/config-provider/useConfig.tsx
closed #2025
#2025 
修复v-loading方式使用时会发出警告问题
- fix(ConfigProvider): 修复 `v-loading` 方式使用时会发出警告问题 ([issue #2025](https://github.com/Tencent/tdesign-vue-next/issues/2025))
> fix(config-provider): 修复v-loading方式使用时会发出警告问题

- src/input-number/useInputNumber.tsx
- fix(InputNumber): 无法输入小数点后面的第一位数字 `0`，[issue#2103](https://github.com/Tencent/tdesign-vue-next/issues/2103)
> fix(InputNumber): can not input zero with point

- CHANGELOG.md
- package.json
> docs: release 0.26.0

- src/dialog/dialog.tsx
- src/drawer/drawer.tsx
- src/utils/dom.ts
> fix(dialog): 修复滚动条判断问题

- src/select/select.tsx
> fix(Select): fix virtual scroll

- src/tag-input/useTagList.tsx
https://github.com/Tencent/tdesign-vue-next/issues/2110
- fix(TagInput): 修复拼音输入时按下删除键触发标签删除问题
> fix(tag-input): 修复拼音输入时按下删除键触发标签删除问题

- src/table/hooks/useRowSelect.tsx
> fix(table): do not excute row select without selection

- CHANGELOG.md
- package.json
- src/table/_example/tree.vue
> docs: release 0.26.1

- src/form/form-model.ts
BREAKING CHANGE: fix: 修复min为0时不校验问题
在vue2.x 版本中修过此问题，发现这里未同步修复
demo: https://stackblitz.com/edit/angular-jpw8jw-rv4xrx?file=src%2Fdemo.vue,package.json
https://github.com/Tencent/tdesign-vue/pull/1772/files
- fix(Form): 修复 `min` 为 `0` 时不校验问题
> fix(form): fix: 修复min为0时不校验问题

- src/guide/guide.tsx
fix: #2155 
`skip` 和 `finish` 事件正确返回 `current`
- fix(Guide):  `skip` 和 `finish` 事件正确返回 `current`
> fix(guide): finish skip current amend

- src/form/type.ts
- [×] 代码风格优化
#2164
- fix(Form): 修复`ValidateResultContext ` 不满足类型约束
> fix: type constraint is not satisfied

- src/dropdown/dropdown-menu.tsx
- https://github.com/Tencent/tdesign-vue/issues/1831
- https://github.com/Tencent/tdesign-vue/issues/1906
- fix(dropdown): 修复多级菜单长度超长时 无法选择子菜单及位置异常的问题
> fix(dropdown): fix overflow dropdown children position

- package.json
- src/config-provider/type.ts
- src/form/form-item.tsx
- src/icon/_example/icon-select.vue
> chore: add icon global config type from icon package

- .github/CODEOWNERS
> chore: auto assign reviewer

- src/tree-select/_example/base.vue
- src/tree-select/tree-select.tsx
- https://github.com/Tencent/tdesign-vue/issues/1929
- feat(TreeSelect): `onVisibleChange`事件增加回调参数
> feat(tree-select): add visible context param when pick value

- CHANGELOG.md
- package.json
- site/docs/getting-started.md
> docs: release 1.0.0

- src/date-picker/base/Header.tsx
- fix(DatePicker): 修复年份选择器区间展示错误
> fix(date-picker): 修复年份选择器区间展示错误

- CHANGELOG.md
- package.json
- src/space/props.ts
> docs: release 1.0.1

- src/input/useInput.ts
https://github.com/Tencent/tdesign-vue/issues/1946
- fix(Input): 处理在 `clear` 事件中无法获取到最新 `value` 问题
> fix(input): value in clear event doesn't change after clear

- src/checkbox/checkbox.tsx
#2230
- fix(Checkbox): 修复 `max` 属性无效 [issue #2230](https://github.com/Tencent/tdesign-vue-next/issues/2230)
> fix(Checkbox): 修复max属性无效问题

- src/date-picker/DateRangePicker.tsx
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- fix(DatePicker): 修复 `datepicker` 输入框变化面板未响应问题 & 月份切换错误响应问题
> fix: 修复 datepicker 输入框变化面板未响应问题 & 月份切换错误响应问题

- CHANGELOG.md
- package.json
> docs: release 1.0.2

- src/locale/ar_KW.ts
- `语言包`: 新增阿拉伯语的语言包 @Ylushen ([common #1097](https://github.com/Tencent/tdesign-common/pull/1097))
> chore: 增加阿拉伯语言包

- src/tooltip/tooltip.tsx
- #2250 
- fix(Tooltip): 修改触发元素传递方式 ([issue #2250](https://github.com/Tencent/tdesign-vue-next/issues/2250))
> fix(tooltip): modify the way the triggering element is passed

- src/dialog/hooks.tsx
~ #2227
- fix(Dialog): 修复类型错误 ([issue #2227](https://github.com/Tencent/tdesign-vue-next/issues/2227))
> fix(dialog): 修复类型错误

- src/swiper/swiper.tsx
https://github.com/Tencent/tdesign-vue-next/issues/2245
- fix(Swiper): 循环播放导航指示标显示问题 ([issue #2245](https://github.com/Tencent/tdesign-vue-next/issues/2245))
> fix(Swiper): 循环播放导航指示标显示问题

- .eslintrc
- package.json
- src/utils/responsive.ts
> chore: update common

- CHANGELOG.md
- package.json
- src/config-provider/config-provider.tsx
> chore: release 1.0.3 and fix type

- .github/CODEOWNERS
- chore: allow to be merged when approved by one of reviewers
> chore: fix reviewer format

- CHANGELOG.md
- package.json
> docs: release 1.0.4

- src/transfer/_example/tree.vue
https://github.com/Tencent/tdesign-vue-next/issues/1958
https://github.com/Tencent/tdesign-vue-next/issues/2299
- docs(transfer): with tree example
> docs(transfer): with tree example

- src/input/useInput.ts
https://github.com/Tencent/tdesign-vue-next/issues/2200
- fix(input): 修复使用 `format` 属性时，光标出现跳动 ([issue #2200](https://github.com/Tencent/tdesign-vue-next/issues/2200))
> fix(input): cursor move when format

- src/hooks/useResizeObserver.ts
- src/table/editable-cell.tsx
- fix(Table): 可编辑单元格，修复无法退出编辑态问题
- fix(Table): 修复因 `useResizeObserver` 被重写导致的全部场景出现告警的问题 `[Vue warn]: Invalid watch source:  undefined A watch source can only be a getter/effect function...`
> [Table] fix editable-cell can not edit; fix vue watch undefined warn

- src/color-picker/panel/index.tsx
Before
https://user-images.githubusercontent.com/26377630/215314601-d16b1370-a22c-46f5-8a6a-b0a242cd077a.mp4
After
https://user-images.githubusercontent.com/26377630/215314608-c37c3d75-7ac3-4dbf-8fa1-c678fd701585.mp4
- feat(ColorPicker): 切换单色-渐变模式时触发色值及onChange变化
> feat(colorpicker): trigger value change when toggle color mode

- src/select-input/__tests__/index.test.jsx
#768
- test(SelectInput): 补充 `select-input` 单元测试
> test(unit): add select-input test

- src/tooltip/tooltip.tsx
- #2301  
- fix(Tooltip): 修复 `Props` 覆盖插槽问题 ([issue #2250](https://github.com/Tencent/tdesign-vue-next/issues/2250))
> fix(tooltip): fix the issue of props overriding the slot

- src/notification/plugin.ts
- fix(Notification): 修复单独引入 `NotifyPlugin` 时没有带入 `css` 样式 ([issue #2312](https://github.com/Tencent/tdesign-vue-next/issues/2312))
> fix: notification plugin

- CHANGELOG.md
- package.json
> docs: release 1.0.5

- src/image/props.ts
- fix(Image): 修复 `image` 组件 `error` ，`overlayContent ` 字段类型错误
> fix: 修复 image 字段类型检测错误

- src/steps/_example/icon.vue
> chore: steps demo bug

- src/rate/__tests__/index.test.jsx
#768 
- test(Rate): 补充 `rate` 单元测试
> test(unit): add rate unit test for Rate component

- src/affix/affix.tsx
- #2279 
- #2280
- 关联PR https://github.com/Tencent/tdesign-common/pull/1140
- fix(Affix): 修复在 `nuxt` 下运行报错的问题 ([issue #2279](https://github.com/Tencent/tdesign-vue-next/issues/2279))
- fix(Pagination): 修复在 `nuxt` 下运行报错的问题 ([issue #2279](https://github.com/Tencent/tdesign-vue-next/issues/2280))
> fix: error in nuxt

- src/form/form-item.tsx
- fix(Form): 修复 `FormItem.name` 和 `FormItem.rules` 变化时无法触发校验问题
> fix(form): form-item can not watch name and rules change

- src/input-number/useInputNumber.tsx
https://github.com/Tencent/tdesign-vue-next/issues/2304
- fix(InputNumber): 修复小数点后第二个数字若为 `0` 无法输入问题 ([issue #2304](https://github.com/Tencent/tdesign-vue-next/issues/2304))
https://user-images.githubusercontent.com/11605702/216908244-7f2505c3-6eb4-492f-8dda-5afaa67b14c5.mov
> fix(input-number): fix can not input doblue 0

- src/dropdown/dropdown-item.tsx
- src/dropdown/dropdown-menu.tsx
- src/dropdown/hooks/useDropdownOptions.ts
1. Dropdown options的content参数不支持函数定义，与文档不符
2. 将Dropdown组件的content参数按文档定义的功能实现，以支持函数类型
- fix(dropdown): 修复 `dropdown content` 支持 `function` 类型
> fix(dropdown): dropdown content支持function类型

- site/src/components/components.jsx
> chore: 修复版本号展示问题

- site/docs/getting-started.md
> docs: add editor docs

- src/dropdown/dropdown-menu.tsx
- fix(Dropdown): 修复多层超长菜单的位置异常问题
- feat(Dropdown): submenu层级结构调整，增加一层`t-dropdown__submenu-wrapper`
> fix(Dropdown): dropdown menu overflow

- src/select-input/props.ts
- src/select-input/select-input.tsx
- src/select-input/useSingle.tsx
- feat(SelectInput: 支持插槽和属性函数自定义 `tips`
- fix(SelectInput): 修复 `defaultInputValue` 无效问题，[issue#2372](https://github.com/Tencent/tdesign-vue-next/issues/2372)
> feat(select-input): support tips slot; fix default-value doesn't not work

- src/table/tr.tsx
> refactor(table): tr return element in setup

- src/tree/hooks/useDraggable.ts
- src/tree/tree-item.tsx
API 来源 https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect
- fix(Tree): 修复树拖拽时候鼠标预期行为样式([issue #1864](https://github.com/Tencent/tdesign-vue-next/issues/1864))
> fix: 修复拖拽手势问题

- helper/attributes.json
- helper/tags.json
- helper/web-types.json
- chore: 更新代码提示
```bash
npm run api:helper 'Vue(PC)' 1 finalProject
npm run api:helper 'VueNext(PC)' 1 finalProject
```
tdesign-api 里面执行上面的命令可以一次性输出所有代码提示
> chore: update helper tips

- src/avatar/group.tsx
> refactor(avatar): tidy up

- src/cascader/hooks.ts
- fix(Cascader): 修复 `options` 变化时未重新渲染 ([issue #2248](https://github.com/Tencent/tdesign-vue-next/issues/2248))([issue #2063](https://github.com/Tencent/tdesign-vue-next/issues/2063))
> fix: cascader options watch

- src/input/useInput.ts
- fix(Input): 修复值为 `null` 时，长度计算不正确问题
> fix(input): fix null limit length

- src/calendar/calendar.tsx
- src/calendar/hook/useState.ts
> fix(calendar): typo

- src/checkbox/group.tsx
> refactor(checkbox): tidy up

- package.json
> docs: release 1.0.8

- src/dialog/dialog.tsx
- src/hooks/useResizeObserver.ts
- src/input/useInputWidth.ts
- src/textarea/calcTextareaHeight.ts
- src/tree/hooks/useDraggable.ts
- src/utils/dom.ts
- src/watermark/hooks.ts
> fix: 修复在ssr环境下的报错

- src/swiper/swiper.tsx
closed #2416
#2416 
- fix(Swiper): 修复 `swiper` 组件 `v-model:current`, `current` 的值不随着轮播变化。([issue #2416](https://github.com/Tencent/tdesign-vue-next/issues/2416))
> fix(swiper): swiper component v-model:current current does no change

- src/select-input/useSingle.tsx
- fix(SelectInput): 修复 `SelectInput` 及基于 `SelectInput` 的输入类组件( `Select/Cascader/TreeSelect` ) 单选可输入模式下回删无法完全清空及其导致的一系列问题
> fix(select-input): backspace delete

- src/cascader/cascader.tsx
- src/select-input/useMultiple.tsx
- src/select/select.tsx
- src/tree-select/tree-select.tsx
- chore: 统一输入类组件多选 `onblur` 逻辑
> chore: move blur logic into select input

- src/dialog/dialog.tsx
- src/drawer/drawer.tsx
- src/table/hooks/useFixed.ts
> fix: 修复 drawer、dialog 滚动条检测问题

- CHANGELOG.md
- package.json
> docs: release 1.0.9

- src/dialog/dialog.md
- src/drawer/drawer.md
- src/guide/guide.md
- src/image-viewer/image-viewer.md
- src/loading/loading.md
- src/loading/loading.tsx
- src/popup/popup.md
- #2422 
- #2439 
- docs: 部分组件FAQ中增加关于Teleport解释说明
- fix(Loading): 修复属性透传问题
> docs: 部分组件FAQ中增加关于Teleport解释说明 & 修复Loading属性透传

- src/dialog/dialog.tsx
- https://github.com/Tencent/tdesign-vue/issues/2188
- 系1.0.9版本针对按钮颜色随主题变化的错误处理导致
- 关联PR https://github.com/Tencent/tdesign-common/pull/1164
- fix(Dialog): 修复 `config-provider` 下配置的 `confirmBtnTheme` 失效的问题
> fix: dialog global btn theme

- src/dialog/dialog.tsx
- fix(Dialog): 修复 `dialog` 打开后的焦点获取问题([issue #2466](https://github.com/Tencent/tdesign-vue-next/issues/2466))
> fix: dialog focus

- src/popup/container.tsx
- #2497 
- #2495
- fix(Popup): 修复popup的trigger为空错误
> fix(Popup):  修复popup的trigger为空错误

- CHANGELOG.md
- package.json
> docs: release 1.1.1

- src/select/_example/popup-props.vue
- src/select/hooks/usePanelVirtualScroll.ts
- fix(Select): 修复切换虚拟滚动时没有触发滚动监听导致滚动未更新数据的缺陷
- docs: 修复下拉框同宽的示例代码
> fix(Select): virtual scroll trigger event listener

- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingleValue.tsx
- fix(DatePicker): 修复月份为 `0` 时展示当前月份问题
> fix(date-picker): 修复月份为 0 时展示当前月份问题

- src/dropdown/dropdown.tsx
- fix(Dropdown): 修复使用`popupProps.on-visible-change`写法导致组件异常的问题
> fix(dropdown): visible change kebab case usage

- src/date-picker/date-picker.en-US.md
- src/date-picker/date-picker.md
- src/date-picker/date-range-picker-props.ts
- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- src/date-picker/props.ts
- src/date-picker/type.ts
- src/range-input/props.ts
- src/range-input/range-input-popup-props.ts
- src/range-input/range-input.en-US.md
- src/range-input/range-input.md
- src/range-input/type.ts
- feat(DatePicker): 支持 `size` 属性 ([issue #2192](https://github.com/Tencent/tdesign-vue-next/issues/2192))
> feat(date-picker): 支持 size 属性

- CHANGELOG.md
- package.json
> docs: release 1.2.0

- src/form/form.tsx
#2562 
- fix(Form): 修复复杂数据结构中使用 `scrollToFirstError` 属性无法提交问题([issue #2562](https://github.com/Tencent/tdesign-vue-next/issues/2562))
> fix(form): scroll to first error

- src/dropdown/dropdown.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2569
- fix(Dropdown): 修复事件回调未定义导致控制台报错的问题
> fix(dropdown): on-visible-change is undefined

- src/guide/__tests__/__snapshots__/vitest-guide.test.jsx.snap
- src/guide/guide.tsx
- src/popup/__tests__/index.test.jsx
- src/popup/popup.tsx
- src/popup/props.ts
- src/select-input/__tests__/index.test.jsx
- src/tooltip/tooltip.tsx
- refactor(popup): 优化 popup 嵌套逻辑
> refactor(popup): 优化 popup 嵌套逻辑

- src/popup/container.tsx
- src/table/hooks/useFixed.ts
- fix(Nuxt): 修复在 `tooltip` 和 `pagination` 组件在 `Nuxt3` 报错([issue #2568](https://github.com/Tencent/tdesign-vue-next/issues/2568))
> fix: 修复在 nuxt 中的报错

- CHANGELOG.md
- package.json
> chore: release 1.2.1

- src/dropdown/_example/slot.vue
- src/dropdown/hooks/useDropdownOptions.ts
- https://github.com/Tencent/tdesign-vue-next/issues/2551
- fix(Dropdown): 支持`v-for`渲染下拉选项，支持`v-for`与普通插槽混用
> feat(dropdown): support mix v-for item slot and single item slot

- src/time-picker/time-picker.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2595
- https://github.com/Tencent/tdesign-vue-next/issues/2582
- feat(TimePicker): 支持`size`属性
- fix(TreeSelect): 修复`1.2.0`版本后初始值为空时报错的问题
- 
> feat(time-picker): support size api

- helper/attributes.json
- helper/tags.json
- helper/web-types.json
- docs: 添加 `t-table` 和 `t-radio-button` 代码提示，[issues#2068](https://github.com/Tencent/tdesign-vue-next/issues/2608)
> docs: add t-table and t-radio-button helper

- src/swiper/swiper.tsx
- fix(swiper): switch begin to end issue
> fix(swiper): switch item error

- src/select/select-panel.tsx
closed #2593
- fix(Select): 修复使用 `filterable` 和自定义下拉选项时，下拉列表展示异常 ([issue #2593](https://github.com/Tencent/tdesign-vue-next/issues/2593))
> fix(select): option render key

- src/common.ts
- src/table/_example/filter-controlled.vue
- src/table/filter-controller.tsx
- src/table/hooks/useColumnResize.ts
- src/table/hooks/useFilter.tsx
- src/table/table.en-US.md
- src/table/table.md
- src/table/type.ts
- test/snap/__snapshots__/ssr.test.js.snap
- fix(Table): 修复 `SSR` 环境 `document` 报错问题
- feat(Table): 过滤功能，支持透传属性 `column.filter.props.onChange`
- feat(Table): 支持设置 `filterRow=null` 隐藏过滤结果行
- docs(Table): 更新组件实例方法文档
> [Table] fix some bugs

- src/time-picker/panel/single-panel.tsx
使用px to rem插件时，会因为精度问题，逐渐错位，此PR提高计算精度，避免实现错位问题，原始样式和其他用户不会产生任何问题。
- fix(TimePicker): 修复使用`px to rem`插件时滚动逐渐错位的问题
> fix(single-panel): fix the problem of single panel alignment failure when using px to rem plugin
