- src/loading/icon/gradient.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2604
1. 当前版本使用LoadingPlugin开启loading，不显示loading效果。
2. 经过查证发现是在获取元素实例的时候，不能够正确获取到color，使得没有设置background，造成loading展示错误。
3. 添加nextTick后让组件在下一轮训中获取即可解决。
- fix(loading): 使用loadingplugin，会没有loading效果的问题
> fix(loading): 修复执行loadingplugin未获取到color造成没有动画的问题

- src/input/input.tsx
- src/input/useInput.ts
- src/tag-input/tag-input.tsx
- src/tag-input/useTagList.tsx
https://github.com/Tencent/tdesign-vue/issues/2261
https://github.com/Tencent/tdesign-vue/issues/1041
- fix(tagInput): 修复删除事件和中文输入事件问题
> fix(Tag-Input): 修复TagInput删除事件和中文输入事件问题

- src/table/base-table.tsx
- src/table/enhanced-table.tsx
- src/table/hooks/useEditableRow.ts
- src/table/hooks/useFixed.ts
- src/table/table.en-US.md
- src/table/table.md
- src/table/type.ts
> fix(table): primaryTableInstanceFunctions ts error

- src/input-adornment/input-adornment.tsx
- fix(InputAdornment): 修复 slot 方式 class 名 缺失问题
> fix: inputAdornment slot class bug

- site/docs/getting-started.md
> chore: update getting started docs

- src/tree-select/tree-select.tsx
、### 🤔 这个 PR 的性质是？
- [ *] 日常 bug 修复
#2682 
1. 要解决的具体问题。
treeSelect data数据更新后 弹出面板的组件更新
2. 列出最终的 API 实现和用法。
修改监听方法 增加 deep
修改 treeSelect data属性的监听为深度监听
- fix(TreeSelect): 修复绑定的 `data` 数据更新后,组件不会重新渲染([issue #2682](https://github.com/Tencent/tdesign-vue-next/issues/2682))
- [√ ] 文档已补充或无须补充
- [√ ] 代码演示已提供或无须提供
- [√] TypeScript 定义已补充或无须补充
- [√ ] Changelog 已提供或无须提供
> fix: 修复TreeSelect在动态更新data时无法重新渲染的问题

- src/locale/zh_TW.ts
> feat: add zh_TW to locale

- src/select/hooks/useSelectOptions.ts
- src/select/option.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2237
- https://github.com/Tencent/tdesign-vue-next/issues/2646
- https://github.com/Tencent/tdesign-vue-next/issues/2671
- fix(Select): 修复存在重复 `value` 的 `option` 变化时没有更新label的问题
- fix(Select): 修复多选选项边缘区域点击不触发选中的缺陷
> fix(Select): fix label update and multiple option padding checkable

- CONTRIBUTING.md
- test/README.md
看文档的时候发现文档有些内容已经落后或者样式存在问题
更新contributing.md测试文档地址并移除了map props地址
更新test/README.md，针对目录使用代码块进行包裹防止出现内容错乱的问题；
- docs(contributing&test): update contributing.md and test/REASME.md
- [] 本条 PR 不需要纳入 Changelog
> docs(contributing&test): update contributing.md and test/REASME.md

- src/loading/loading.md
> chore: display v-loading demo

- CHANGELOG.md
- package.json
> docs: release 1.3.0

- src/select/_usage/props.json
docs(Select): usage  bordered废弃移除
> docs(Select): usage  bordered废弃移除

- README-zh_CN.md
> docs(readme): update contributing docs link

- site/docs/getting-started.md
> docs: nuxt3使用

- src/date-picker/date-range-picker-props.ts
#2719 
fix(DatePicker): 修复 `valueType` 参数校验错误([issue #2719](https://github.com/Tencent/tdesign-vue-next/issues/2719))
> fix(date-picker): date range picker valueType validator

- src/select/option.tsx
- fix(Select): 修复多选选项点击触发多次导致虚拟滚动切换普通模式时无法选中的问题
> fix(select): multiple option re-render

- src/image/image.tsx
https://github.com/Tencent/tdesign-vue-next/issues/2574
- fix(image): ssr loading 
> fix(image): ssr loading

- src/date-picker/DatePicker.tsx
- src/date-picker/DatePickerPanel.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/DateRangePickerPanel.tsx
- src/date-picker/base/Footer.tsx
- src/date-picker/date-picker-panel-props.ts
- src/date-picker/date-picker.en-US.md
- src/date-picker/date-picker.md
- src/date-picker/date-range-picker-panel-props.ts
- src/date-picker/date-range-picker-props.ts
- src/date-picker/props.ts
- src/date-picker/type.ts
- fix(Datepicker): 支持 `onPresetClick` 事件
> feat(date-picker): 支持 onPresetClick 事件触发

- CHANGELOG.md
- package.json
> docs: release 1.3.1

- src/date-picker/_example/disable-date.vue
> chore: 修复 demo报错

- package.json
- src/pagination/pagination.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2675
- fix(Pagination): 修复切换语言时未重新渲染内容的缺陷
> fix(Pagination): i18n switch not working

- src/input/input.tsx
- fix(Input): 修复 `input` 组件 `type = hidden` 时，组件边框依然被显示的问题 
> fix: input type hidden

- src/date-picker/DateRangePicker.tsx
- fix(DatePicker): 修复第二次点击面板关闭异常问题
> fix: 修复第二次点击面板关闭异常问题

- src/link/link.tsx
> fix(link): form disable not working

- CHANGELOG.md
- package.json
> docs: release 1.3.2

- script/generate-usage/config.js
- src/back-top/_usage/index.vue
- src/sticky-tool/_usage/index.vue
- src/sticky-tool/_usage/props.json
- docs(back-top): 使用示例代码没有放到script/generate-usage/config.js
- docs(sticky-tool ): 新增使用交互示例
> docs: back-top sticky-tool 使用示例

- src/tree/_example/expand-all.vue
https://github.com/Tencent/tdesign-vue-next/issues/2805
- docs(Tree): 修复展开操作的 demo 中无法切换数据的问题
> docs(tree): 修复展开操作的 demo 中无法切换数据的问题

- src/select/select-panel.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2794
- fix(Select): 修复 1.3.2 版本 控制台 warning 的异常
> fix(Select): size props warning

- src/select/option.tsx
closed #2825
- fix(select): 限制可选数目无效
> fix(select): 限制可选数目无效

- src/select/option.tsx
#2825 
- fix(select): 超出最大限制后选项可点击
> fix(select): option can be clicked when max limit overflow

- src/select/option.tsx
- src/select/select.tsx
- feat(Select): `onChange` 事件 `context` 新增`option`参数 用于获取选中项完整内容
> fix(Select): onChange context add option params

- src/image/image.tsx
- fix(Image):  修复 `nuxt3` 环境下 `onload` 无效
> fix(image): nuxt3 onload not working

- src/popup/popup.tsx
- https://github.com/Tencent/tdesign-vue/issues/2398
- fix(Popup): 修复`onScrollToBottom` 在部分windows环境下无法触发的问题
> fix(popup): trigger on-scroll-to-bottom on windows

- CHANGELOG.md
- package.json
> docs: release 1.3.3

- script/generate-usage/config.js
- src/image/_usage/index.vue
- src/image/_usage/props.json
> docs(image): usage example

- package.json
- chore: remove test:demo script
> chore: remove test:demo script

- src/tag-input/useTagList.tsx
- src/textarea/textarea.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2862
- https://github.com/Tencent/tdesign-vue-next/issues/2855
- fix(TagInput): 修复组件初始值异常的问题
- fix(Textarea): 修复 `autosize` 为 `null` 报错的问题
> fix(text-area): error when autosize is null

- package.json
> docs: release 1.3.4

- src/tag-input/tag-input.tsx
#2887
- feat(TagInput): 增加 `focus ` 方法的导出([issue #2887](https://github.com/Tencent/tdesign-vue-next/issues/2887))
> feat(tag-input): expose focus method

- src/table/hooks/useFilter.tsx
#2867 
- fix(Table): 修复在多级表头中使用筛选功能，显示异常问题([issue #2867](https://github.com/Tencent/tdesign-vue-next/issues/2867))
> fix(table): 修复在多级表头中使用筛选功能，显示异常问题(#2867)

- src/back-top/_example/baseListSmall.vue
- src/back-top/back-top.tsx
- src/sticky-tool/sticky-item.tsx
- src/time-picker/panel/time-picker-panel.tsx
- https://github.com/Tencent/tdesign-vue/issues/2421
- https://github.com/Tencent/tdesign-vue/issues/2432
- https://github.com/Tencent/tdesign-vue/issues/2446
- https://github.com/Tencent/tdesign-vue-next/issues/2874
- feat(TimePicker): 没有选中值时不允许点击确认按钮
- fix(Backtop): 修复 `visibleHeight` 只作用一次的问题
- fix(Tooltip): 修复 `1.3.4` 版本的箭头位置异常的样式问题
> fix: sync issues fix

- src/tree/util.ts
- fix(Tree): 修正由于 `Tree` 组件错误过滤了 `allowFoldNodeOnFilter` 而导致该参数无效的问题
> fix(Tree): 修正由于 Tree 组件错误过滤了 allowFoldNodeOnFilter 而导致该参数无效的问题

- CHANGELOG.md
- package.json
> docs: release 1.3.5

- src/radio/radio-button.tsx
- #2873 
- fix(Radio): 修复 `label` 无效问题 ([issue #2873](https://github.com/Tencent/tdesign-vue-next/issues/2873))
> fix(Radio): 修复label无效问题

- src/select/select-panel.tsx
- fix(select): 修正当 `options` 数据存在 `className` 而导致选项样式会被意外污染的问题
> fix(select): 修正当options数据存在className而导致选项样式会被意外污染的问题

- src/input-adornment/input-adornment.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2926
- fix(InputAdornment): 修复`1.3.5`中修复空字符串导致插槽没有正常渲染的问题
> fix(InputAdornment): render slot

- src/input-number/useInputNumber.tsx
> fix(InputNumber): 初始值为 undefined/null，且存在 decimalPlaces 时，不再进行小数点纠正

- src/select/__tests__/index.test.jsx
- src/select/select.tsx
> fix(Select): value is '' uncheckable

- src/dialog/dialog.tsx
- src/input/useInputEventHandler.ts
- src/menu/head-menu.tsx
- src/select/helper.ts
- src/select/hooks/useSelectOptions.ts
- src/select/select-panel.tsx
- src/select/select.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2877
- Input此前为了处理Dialog的confirmOnEnter事件冲突阻止了冒泡行为 进而影响了其他基于Input的组件的行为 如Select的回车键盘操作 调整这个处理到Dialog的confirmOnEnter内部 且判断为input元素就阻止 适用范围可以不止TD的input
- displayOptions迁移到公共hooks内 方便多个tsx进行逻辑判断使用 修复过滤选项在键盘操作中未被过滤的问题
- fix(Select): 修复无法通过键盘回车操作选中选项及忽略已过滤选项的缺陷
- feat(Input): 回车事件不再阻止事件冒泡
- chore: 暂时移除不完善的顶部菜单省略展示逻辑 待完善再加回
> fix(Select): resolve enter keyboard event and filterable options

- script/generate-usage/config.js
- src/timeline/_usage/index.vue
- src/timeline/_usage/props.json
- src/timeline/timeline.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2954
- fix(Timeline): 修复 `timeline-item` 内容不支持热更新的缺陷 ([issue #2954](https://github.com/Tencent/tdesign-vue-next/issues/2954))
- docs: 新增`Timeline` live demo展示
> fix(timeline): fix timeline item hmr issue

- src/select/select-panel.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2971
- fix(Select): 修复使用`tagName`作为key时控制台出现告警的问题
> fix(select): resolve warning when using tagName as key

- src/upload/themes/normal-file.tsx
fix type
- fix(Upload): `ts` 类型修复
> fix(upload): type

- src/textarea/textarea.tsx
https://github.com/Tencent/tdesign-vue/issues/2522
- fix(TextArea): 修复不能响应设置 `value` 值后 autosize 自适应失效的问题
> fix: textarea auto height

- src/swiper/swiper.tsx
- fix(Swiper): 修复 `navigation` 插槽失效的问题
> fix(swiper): fix navigation slot usage

- CHANGELOG.md
- package.json
> docs: release 1.3.8

- package.json
> chore: fix ci test

- src/tabs/tabs.en-US.md
- src/tabs/tabs.md
#2945 
- fix(tabs): 移除文档中onChange不存在的参数
> docs(tabs): remove onChange not exist parameter

- src/dropdown/_example/base.vue
- src/dropdown/hooks/useDropdownOptions.ts
- https://github.com/Tencent/tdesign-vue-next/issues/3012
- fix(Dropdown): 修复通过组合 `v-for` 和单个 item 渲染组件丢失节点的缺陷
- docs(Dropdown): 调整 `dropdown` 示例 增加trigger click用法
> fix(dropdown): fix render v-for and single item within a slot

- src/pagination/pagination.tsx
https://github.com/Tencent/tdesign-vue-next/issues/3020
fix(Pagination): `onchage` 获取 `props.current` 未修改([issue #3020](https://github.com/Tencent/tdesign-vue-next/issues/3020))
> fix(pagination): onchage 触发 获取current是旧值

- CHANGELOG.md
- package.json
> docs: release 1.3.9

- src/date-picker/DatePicker.tsx
- src/date-picker/DateRangePicker.tsx
- src/date-picker/date-picker-panel-props.ts
- src/date-picker/date-picker.en-US.md
- src/date-picker/date-picker.md
- src/date-picker/date-range-picker-panel-props.ts
- src/date-picker/date-range-picker-props.ts
- src/date-picker/props.ts
- src/date-picker/type.ts
feat(DatePicker):  onConfirm事件
> feat(DatePicker):  新增 onConfirm事件

- src/input-number/useInputNumber.tsx
https://github.com/Tencent/tdesign-vue/issues/2516
Corrective action would not be performed when the input value is `0`
After fix:
- fix(input-number): fix calibration invalid for `value=0`
> fix(input-number): calibration invalid for `value=0`

- src/select/option.tsx
> fix(Select): disabled value in multiple

- src/select-input/select-input.tsx
- src/select-input/useMultiple.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/3050
- fix(TagInput): 修复前置图标的样式缺陷
- fix(SelectInput): 修复失焦时未清空输入内容的缺陷
> fix(select-input): clear input value when tag input on blur

- src/menu/submenu.tsx
- fix(Submenu): 修复 `popup-props` 透传问题
> fix(submenu): 修复 popup-props 透传问题

- CHANGELOG.md
- package.json
> docs: release 1.3.10

- src/tag-input/useTagList.tsx
fix: #2939
第一次输入时，`oldInputValue`没有赋值
- fix(SelectInput): 修复使用回退键删除 `input` 中内容时，会删除 `tag` ([issue #2939](https://github.com/Tencent/tdesign-vue-next/issues/2939))
> fix: #2939

- src/textarea/textarea.tsx
#3068 
- feat(Textarea): 支持动态更改 `autosize` 属性 ([issue #3068](https://github.com/Tencent/tdesign-vue-next/issues/3068))
> feat(textarea): support dynamic change autosize prop

- src/upload/hooks/useDrag.ts
- src/upload/hooks/useUpload.ts
> feat(_common): update common

- src/dialog/plugin.tsx
closed #3076
#3076 
- feat(Dialog): dialog plugin destroy 时，销毁组件实例
> feat(dialog): dialog plugin destroy 时，销毁组件实例

- src/input/input.en-US.md
- src/input/input.md
- src/input/props.ts
- docs(Input): 输入框的值 类型移除 Number
> docs(Input): value type remove Number

- src/input/props.ts
- revert(Input): 恢复部分属性默认值数据类型定义
> [Input] revert: props default value ts type

- src/date-picker/DateRangePicker.tsx
- src/date-picker/hooks/useRange.tsx
> feat(date-picker): 优化关闭浮层后重置默认选中区域

- src/form/_example/clear-validate.vue
- src/form/_example/error-message.vue
- src/form/_example/validator.vue
> chore: form demo fix typo

- package.json
- https://github.com/Tencent/tdesign-vue-next/issues/3079
- fix(Icon): 修复 `manifest` 字段影响开发阶段请求的问题
- fix(TagInput): 修复 `tag-input` 前缀不居中且会发生抖动的问题 @xixileng 
- fix(Transfer): 修复 `t-transfer__list-item` 与 `t-checkbox` 优先级问题
- fix(Input): 修复 `prefixIcon` 的 `padding` 样式问题
> chore: update common and icons

- src/sticky-tool/sticky-item.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/3094
- fix(Stickytool): 修复 `sticky-item` 组件内部无法更新数据的问题
> fix(sticky-tool): fix item rerender

- package.json
- test/unit/test-setup.js
pnpm run test:snap-update
- fix: 解决 `pnpm` 执行 `test:snap-update` 生成的 `snap` 文件异常
> fix: resolve pnpm run test:snap-update

- src/input-number/_example/center.vue
- src/input-number/useInputNumber.tsx
Revert https://github.com/Tencent/tdesign-vue-next/pull/3098
> Revert #3098

- site/src/components/demo-page.vue
> chore: 支持jsx 文件调试

- src/input-number/useInputNumber.tsx
- fix(InputNumber): `decimalPlaces` 存在时，数值满足要求，用户未操作，就已经触发 `onChange` 事件问题，[tdesign-vue#2616](https://github.com/Tencent/tdesign-vue/issues/2616)
> fix(input-number): decimalPlaces trigger onChange event

- CHANGELOG.md
- package.json
> docs: release 1.4.0

- src/tree/useTree.tsx
Reverts Tencent/tdesign-vue-next#3134
close #3157 #3158
reopen #3110
> Revert "fix(tree): 修复Tree active事件中actived值相反(#3110)"

- CHANGELOG.md
- package.json
> docs: release 1.4.1

- package.json
- script/rollup.config.js
> chore: fix build script process in Windows env

- .github/workflows/auto-release.yml
- script/rollup.config.js
- revert: 回退为 `windows` 构建的产物的路径逻辑
- fix: 修复 `CHANGELOG` 生成缩进格式的异常
> chore: fix infra

- src/popup/popup.tsx
closed #3183
#3183
- fix(popup): overlayEl 未绑定， 第一次点开无法定位到选中项
> fix(popup): overlayEl 未绑定， 第一次点开无法定位到选中项

- src/menu/menu.tsx
fix #3186 
- fix(menu): 修复同一个MenuItem多次触发onChange的问题
> fix(menu): The same MenuItem triggers onChange multiple times

- src/slider/__tests__/behavior.test.jsx
- src/slider/slider.tsx
- fix #3161 
无
- fix(Slider): validate input value
> fix(slider): validate input value

- src/form/_example/custom-validator.vue
- fix(Demo): 修复 `form` 的 `custom-validator` 示例代码
> fix: form custom validator

- src/image-viewer/image-viewer.tsx
closed #3223
#3223 
- fix(ImageViewer): 清除图片查看状态
> fix(ImageViewer): 清除图片查看状态

- src/hooks/tnode.ts
- https://github.com/Tencent/tdesign-vue-next/issues/3191
- fix: 修复 `Chrome插件` 及 `eletron` 等场景使用new Function 触发安全策略问题的影响
> chore: fix security situation

- src/calendar/_example/value.vue
- src/date-picker/__tests__/__snapshots__/index.test.jsx.snap
- src/date-picker/__tests__/index.test.jsx
- src/form/__tests__/form.test.jsx
- src/menu/menu-item.tsx
- src/table/_example/editable-cell.vue
> test: fix form warning

- src/tree/useTree.tsx
- fix(Tree):  修复 `tree` 组件深度监听问题([issue #3227](https://github.com/Tencent/tdesign-vue-next/issues/3227))
> fix: 修复 tree 组件数据深度监听问题

- CHANGELOG.md
- package.json
- tsconfig.json
> docs: release 1.5.1

- src/switch/props.ts
- src/switch/switch.en-US.md
- src/switch/switch.md
- src/switch/switch.tsx
- src/switch/type.ts
onchange 参数添加 context: { e: MouseEvent } https://github.com/Tencent/tdesign-react/pull/2162
disabled 修改 https://github.com/TDesignOteam/tdesign-api/pull/181
- feat(Switch): `onchange` 参数添加 `context: { e: MouseEvent }`
- fix(Switch):  调整 `disabled` 禁用优先级，`Switch.disabled > Form.disabled`
> feat(switch):  api update

- src/upload/themes/image-card.tsx
无
在theme为image时，开启disabled后不显示上传按钮
修改前：
修改后：
> feat(upload): 上传组件theme='image'时，在disabled状态不显示上传按钮

- src/input/input.en-US.md
- src/input/input.md
- src/input/props.ts
- src/input/type.ts
- src/input/useInput.ts
- src/textarea/props.ts
- src/textarea/textarea.en-US.md
- src/textarea/textarea.md
- src/textarea/type.ts
#3265 
- feat(Input): 添加 `maxlength` 属性 `String` 类型 ([issue #3265](https://github.com/Tencent/tdesign-vue-next/issues/3265))
- feat(Textarea): 添加 `maxlength` 属性 `String` 类型 ([issue #3265](https://github.com/Tencent/tdesign-vue-next/issues/3265))
> feat(input & textarea): add maxlength string prop type

- src/menu/menu-item.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/3274
- fix(Menu): 修复通过 `v-for` 渲染双层菜单时部分属性失效的问题
> fix(menu): v-for menu props missing

- src/cascader/core/effect.ts
- fix(Cascader): 修复 `cascader` 清空时展开状态表现
> fix: cascader expand status

- package.json
> docs: release 1.5.3

- src/table/hooks/useDragSort.ts
- src/table/hooks/useTreeData.tsx
- src/table/hooks/useTreeDataExpand.ts
- fix(Table): 树形结构，可拖拽调整行顺序，修复最后一个节点展开的子节点位置不正确问题
- fix(Table): 树形结构，修复 v1.5.3 中 `tree.defaultExpandAll` 失效问题
> fix(table): tree defaultExpandAll

- src/table/primary-table.tsx
https://github.com/Tencent/tdesign-vue-next/issues/3299
- fix(table): 不使用columnController时也可以使用列配置
> fix(table): 不使用columnController时也可以使用列配置

- src/image-viewer/base/ImageItem.tsx
- src/image/image.tsx
- fix(Image): 修复 `fallback` 在第一次加载失败后无效问题
> fix(image-viewer): fix fallback

- src/watermark/type.ts
- src/watermark/watermark.en-US.md
- src/watermark/watermark.md
closed #3278
- https://github.com/Tencent/tdesign-vue-next/issues/3278
watermark 文字新增fontFamily属性
- feat(watermark): 文字新增`fontFamily`属性
> feat(watermark): watermarkText add fontFamily

- src/table/hooks/useAffix.ts
- src/table/hooks/useEditableRow.ts
- fix(Table): 可编辑表格，修复多个可编辑表格同时存在时，校验互相影响问题
> fix(table): multiple editable table

- src/breadcrumb/breadcrumb-item.tsx
- src/menu/head-menu.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/3274
- fix(Menu): 修复双层菜单未配置`router`时 to 属性无法基于`vue-router`默认跳转的缺陷
- fix(Breadcrumb): 修复未配置`router`时 to 属性无法基于`vue-router`默认跳转的缺陷
> fix(menu): fix default router config

- src/transfer/components/transfer-list.tsx
closed #2565
https://github.com/Tencent/tdesign-vue-next/issues/2565
修复穿梭框组件无法搜索深层级树形结构数据
- fix(transfer): 修复穿梭框组件无法搜索深层级树形结构数据
> fix(transfer): fix transfer search tree data error

- CHANGELOG.md
- package.json
- src/color-picker/color-picker.en-US.md
- src/color-picker/color-picker.md
> chore: release 1.5.4

- src/tree-select/tree-select.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/3347
- feat(TreeSelect): 支持`panelTopContent`和 `panelBottomContent` 的使用
> feat(TreeSelect): support panel content API

- src/cascader/cascader.tsx
- fix(Cascader): 修复 `borderless` 无效
> fix: 修复 borderless 无效

- src/textarea/textarea.en-US.md
- src/textarea/textarea.md
1.解决文档不一致问题
2.textarea不存在label属性
> 删除文档中textarea不存在的label属性

- CHANGELOG.md
- package.json
> docs: release 1.5.5

- src/hooks/useResizeObserver.ts
- fix(useResizeObserver): 修复缺少容器元素判空问题
> fix(select): useResizeObserver container.value could be empty

- CHANGELOG.md
- package.json
> docs: release 1.5.6

- README-zh_CN.md
- README.md
> chore: replace qrcode

- src/table/base-table.tsx
- src/table/filter-controller.tsx
- src/table/hooks/useAsyncLoading.tsx
- src/table/hooks/useColumnController.tsx
- src/table/hooks/useFilter.tsx
- src/table/hooks/useRowExpand.tsx
- src/table/hooks/useSorter.tsx
- src/table/hooks/useTreeData.tsx
- src/table/sorter-button.tsx
- src/table/tbody.tsx
- feat(Table): 支持通过属性 `ocal` 配置组件所有文本
- fix(Table): 列配置弹框，关闭时默认不销毁
> feat(table): support props.locale

- src/dialog/plugin.tsx
close #3381 
销毁Dialog未销毁wrapper，导致多个wrapper在页面
修复Dialog plugin事件销毁Dialog未销毁wrapper，导致多个wrapper在页面。
- fix(Dialog): 修复 `Dialog plugin` 事件销毁 `Dialog` 未销毁 `wrapper`，导致多个 `wrapper` 在页面([issue #3381](https://github.com/Tencent/tdesign-vue-next/issues/3381))
> fix(Dialog): fix Dialog destroy not remove wrapper

- src/checkbox/group.tsx
- fix(checkbox): 修复 `checkbox-group` 的 `innerValue.value` 为 `undefined` 导致异常
> fix: 修复checkbox-group的innerValue.value为undefined导致异常

- CHANGELOG.md
- package.json
> docs: release 1.5.7

- src/hooks/useResizeObserver.ts
> fix(hooks): useResizeObserver

- src/select/select-panel.tsx
- src/select/select.tsx
https://github.com/Tencent/tdesign-vue-next/issues/3392
- fix(select): 筛选后使用键盘上下键选择功能异常([isssue #3392](https://github.com/Tencent/tdesign-vue-next/issues/3392))
> fix(select): 筛选后使用键盘上下键选择功能异常

- src/select/select.tsx
fix #3416 
- fix(Select): 修复下拉选项闪现([issue #3416](https://github.com/Tencent/tdesign-vue-next/issues/3416))
> fix(select): display abnormal

- src/badge/__tests__/index.test.jsx
- src/badge/badge.tsx
https://github.com/Tencent/tdesign-vue-next/issues/3447
- feat(Badge): `content`,`count` 插槽支持([issue #3447](https://github.com/Tencent/tdesign-vue-next/issues/3447))
> feat(Badge): content,count 插槽支持

- src/cascader/core/effect.ts
- fix(Cascader):  `change` 事件中 `source` 异常问题([issue #2835](https://github.com/Tencent/tdesign-vue/issues/2835))
> fix: effect source abnormal

- CHANGELOG.md
- package.json
- src/tree/hooks/style/css.js
- src/tree/hooks/style/index.js
> docs: release 1.6.1

- src/badge/badge.tsx
- fix(badge): 边框圆角方形样式([common#1617](https://github.com/Tencent/tdesign-common/pull/1617))
- fix(badge): 开启`dot` 忽略形状设置
> fix(badge): dot ignore shape round

- src/table/_example/filter-controlled.vue
- src/table/filter-controller.tsx
- feat(Table): 可筛选表格，支持设置 `confirmEvents: ['onChange']` 后，单选筛选器(Radio) 选择完成后自动关闭筛选器浮层
> feat(table): radio filter controller improvement

- src/image-viewer/base/ImageViewerUtils.tsx
- src/image-viewer/hooks.ts
- #3473 
- fix(ImageViewer): 控制栏控件中部数据，在步长值不为0.5时，精度丢失的问题
> fix(ImageViewer): 控制栏控件中部数据，在步长值不为0.5时，精度丢失的问题 #3473

- src/tabs/_example/lazy-load.vue
- src/tabs/tab-panel-props.ts
- src/tabs/tab-panel.tsx
- src/tabs/tabs.en-US.md
- src/tabs/tabs.md
- src/tabs/type.ts
[vue2](https://github.com/Tencent/tdesign-vue/pull/2714) 先使用了lazy,统一属性名，lazyLoad 改 lazy
> refactor(tabs): lazyLoad rename lazy

- src/grid/type.ts
- API平台 https://github.com/TDesignOteam/tdesign-api/pull/196
- fix(Grid): 修复`Row`和`Col`子组件配置项属性均为必填的类型问题
> fix(grid): col props and gutter object is optional

- src/select-input/select-input.tsx
- fix(SelectInput): 修复下拉框内无法输入或聚焦“输入框”、“数字输入框”等可聚焦元素
> fix(select-input): do not set focus if the element which can be focused in panel is clicked

- CHANGELOG.md
- package.json
> docs: release 1.6.3

- src/select-input/select-input.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/3495
- fix(Cascader): 修复`1.6.3`版本多选模式下无法选择的缺陷 @liweijie0812 
> fix(cascader): can pick in multiple mode

- package.json
> docs: release 1.6.4

- src/select/_example/collapsed.vue
> fix(Select): 修复example错误

- src/select-input/select-input.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/3485
- https://github.com/Tencent/tdesign-vue-next/issues/3493
- https://github.com/Tencent/tdesign-vue-next/issues/3469
- fix(SelectInput): 修复`1.6.2`之后非多选场景下继续自动聚焦输入框的问题
> fix(select-input): focus status

- CHANGELOG.md
- package.json
> chore: release 1.6.5

- src/slider/hooks/useSliderTooltip.tsx
- src/slider/props.ts
- src/slider/slider-button.tsx
- src/slider/slider.en-US.md
- src/slider/slider.md
- src/slider/slider.tsx
- src/slider/type.ts
- #3470 
- feat(Slider): 增加 `label` 的函数方式参数支持 (#3470 )
> feat(Slider): label的函数参数支持

- src/color-picker/color-picker-panel.tsx
- src/color-picker/panel/index.tsx
- #3471 
- fix(Color-Picker): 修复最近使用颜色异常问题
> fix(Color-Picker): 修复最近使用颜色异常问题

- src/tabs/tab-nav.tsx
fixed #3510
- fix(TabNav): 动态修改选项卡数量导致滑动按钮不符合预期
> fix(tab-nav): arrow display is abnormal

- src/tree-select/tree-select.tsx
- #3519 
- fix(Tree-Select): 修复未使用keys别名
> fix(Tree-Select): 修复未使用keys别名

- src/tree/__tests__/api.test.jsx
- src/tree/hooks/useTreeStore.ts
- src/tree/tree.tsx
fix(tree): 解决 watch 回调时间过迟的问题
test(tree): 补充该问题对应的单元测试
> fix(tree): tree 组件，同步 tdesign-vue 代码，解决 watch 时机问题

- CHANGELOG.md
- package.json
> docs: release 1.6.6

- src/tree/hooks/useTreeStore.ts
- src/tree/tree.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/3544
- fix(Tree): 修复1.6.6版本 v-model 的异常问题
> fix(Tree): fix checkable view

- src/tree-select/style/css.js
fix #3452
- fix(TreeSelect): 处理导入的样式文件异常问题
> fix(tree-select): the imported style file is abnormal

- src/tree/__tests__/api.test.jsx
- src/tree/__tests__/event.test.jsx
- src/tree/_example/checkable.vue
- src/tree/_example/operations.vue
- src/tree/hooks/useTreeStore.ts
- src/tree/tree.en-US.md
- src/tree/tree.md
- src/tree/tree.tsx
- src/tree/type.ts
提供获取树结构数据的 api
- fix(tree): 提供获取树结构数据的 api: getTreeData
> feat(tree): add api getTreeData

- src/hooks/slot.ts
> chore: fix ci type check

- src/table/_example/editable-cell.vue
- src/table/hooks/useEditableRow.ts
- fix(Table): 修复 `v1.6.7` 引起的单元格编辑失效问题
> fix(table): editable-cell bug

- src/dialog/plugin.tsx
#3551 
- fix(Dialog): 修复以Plugin的方式调用时，更新className会报错并且会覆盖组件的原className。
> fix(Dialog): fix custom classname will get error

- CHANGELOG.md
- package.json
> chore: release 1.6.8

- src/loading/plugin.tsx
#3540 
- feat(Loading): 当使用 `Plugin` 或指令调用时，隐藏 `Loading` 将会移除 `app` 实例([issue #3540](https://github.com/Tencent/tdesign-vue-next/issues/3540))
> feat(Loading): hide loading will remove app instance when use plugin or directive call

- src/hooks/useDragSort.tsx
- fix(hooks): 修复在使用 `dragSort` 时不使用回调 `Props` 函数出现的报错
> fix(hooks): 修复在使用dragSort时不使用回调Props函数出现的报错

- src/select/hooks/useKeyboardControl.ts
[#3606](https://github.com/Tencent/tdesign-vue-next/issues/3606)
- fix(select): 修复`1.6.6`版本后，多选模式下，无法通过enter键选中选项问题
> fix(select): 修复multiple多选模式下，无法通过enter键选中选项问题

- src/cascader/hooks.ts
- fix(Cascader): 修复默认值在选项中不存在时的报错([issue #3595](https://github.com/Tencent/tdesign-vue-next/issues/3595))
> fix: 修复默认值在选项中不存在时的报错

- src/space/space.tsx
> fix(space): rename --row-gap to --td-space-row-gap

- CONTRIBUTING.md
> chore: fix docs

- CHANGELOG.md
- package.json
> docs: release 1.7.0

- src/checkbox/hooks/useKeyboardEvent.ts
- src/radio/useKeyboard.ts
https://github.com/Tencent/tdesign-vue-next/pull/3599#discussion_r1403299874
> refactor: radio/checkbox选中判断改回正则

- site/src/components/base-usage.vue
> feat: 基础示例(base-usage)部分的代码格式化

- src/auto-complete/highlight-option.tsx
等等添加测试
- fix(AutoComplete): 使用 `lodash/escapeRegExp` 转换关键字文本
> fix(auto-complete): using lodash escapeRegExp transform keyword text

- package.json
- script/rollup.config.js
- script/utils/rollup-empty-input.js
`cssConfig` 配置会产生空的 JS 文件，需要移除
- chore: 移除打包结果中的空文件
> feat(Chore): remove empty index.js

- src/breadcrumb/breadcrumb-item.tsx
breadcrumb-item-props 没有定义 onClick
> chore: 删除无效代码

- src/utils/withInstall.ts
之前
之后
- fix(loading): `ts` 类型丢失, `volar` 提示无效
> fix(loading): ts类型丢失

- src/dropdown/dropdown-item.tsx
Fix #3693 
- fix(DropdownItem): 处理禁用状态可点击的问题([issue #3693](https://github.com/Tencent/tdesign-vue-next/issues/3693))
> fix(dropdown-item): the disabled effect is unexpected

- src/popup/popup.tsx
https://github.com/Tencent/tdesign-vue-next/issues/3686
- fix(popup): 控制台报错
> fix(popup): 控制台报错

- src/pagination/pagination.tsx
- src/pagination/useMoreAction.ts
[#3703](https://github.com/Tencent/tdesign-vue-next/issues/3703)
修复后
原因
没对当前页判断位置，以及左右剩余数量针对偶数情况未处理
- fix(pagination): 分页组件foldedMaxPageBtn优化
> fix: 分页组件foldedMaxPageBtn优化

- PUBLISH.md
> docs: add PUBLISH.md

- src/image-viewer/base/ImageItem.tsx
- src/image-viewer/base/ImageViewerUtils.tsx
- fix(ImageViewer): 去除默认值设置以使用 `globalConfig` 中的默认值,避免在不同语言环境中出现异常
> fix(image-viewer): 去除默认值设置以使用globalConfig中的默认值,避免在不同语言环境中出现异常

- src/image-viewer/__tests__/__snapshots__/index.test.jsx.snap
- src/image-viewer/image-viewer.tsx
- fix(ImageViewer): 修改键盘事件绑定对象,避免影响全局键盘事件
> fix(image-viewer): 修改键盘事件绑定对象,避免影响全局键盘事件

- src/hooks/useVirtualScrollNew.ts
错误的监听器导致 fixedRowHeight 场景下初始化失败，导致虚拟滚动不生效
> fix(Table): 🐛 修正错误的监听器行为

- CONTRIBUTING.md
> docs(CONTRIBUTING): 简短初始化命令

- src/image-viewer/image-viewer.tsx
自然滚动与标准滚动之间存在操作差异，导致对缩放具有不同的操作直觉感知，现修改为更符合常规操作的直觉
- fix(ImageViewer): 滚轮缩放符合操作直觉
> fix(ImageViewer): 滚轮缩放符合操作直觉

- src/table/hooks/useAffix.ts
affix 表头情况下，增加 touch 事件的额外支持，同步内容展示
- fix(table): 虚拟滚动场景，修复吸顶（Affix）表头无法滚动同步问题
> fix(table): 🐛 虚拟滚动场景，修复吸顶（Affix）表头无法滚动同步问题

- src/table/filter-controller.tsx
- src/table/hooks/useAffix.ts
- src/table/hooks/useRowHighlight.ts
- fix(Table): 横向滚动场景，修复在 Windows 场景中，按下鼠标（不松开鼠标）横向滚动时，表头没有跟随滚动问题
- fix(Table): 可筛选表格，修复筛选值为 0 时，筛选图表没有高亮问题，[tdesign-vue#2987](https://github.com/Tencent/tdesign-vue/issues/2987)
- fix(Table): 修复 `1.7.1` 中，Shift 连续选中失效问题，[#3751](https://github.com/Tencent/tdesign-vue-next/issues/3751)
> [Table] fix windows mousedown horizontal scroll

- src/select/select.tsx
- src/tree-select/tree-select.tsx
- 相关PR https://github.com/Tencent/tdesign-vue-next/pull/3418 
需要保持关闭不闪烁 onFocus执行没有生效
- fix(Select): 修复1.6.0版本后 可过滤下 重新打开没有正常清除过滤输入内容的问题
- fix(TreeSelect): 修复可过滤下，重新打开没有清除过滤输入内容的问题
> fix(select): clear input value when panel display

- src/select/select.tsx
- src/tree-select/tree-select.tsx
- optimize https://github.com/Tencent/tdesign-vue-next/pull/3762
> feat: optimize clear value situation

- src/menu/menu-item.tsx
- https://github.com/Tencent/tdesign-vue/issues/2940
- feat(Menu): 选中后关闭菜单，与其他组件保持交互行为一致([issue #2940](https://github.com/Tencent/tdesign-vue/issues/2940))
> feat(Menu): close menu after clicking menu item

- src/card/card.en-US.md
- src/card/card.md
- src/card/card.tsx
- src/card/props.ts
- src/card/type.ts
> docs(Card): api update

- CHANGELOG.md
- package.json
> docs: release 1.7.2

- src/slider/_example/base.vue
- src/slider/props.ts
- src/slider/slider-button.tsx
- src/slider/slider.en-US.md
- src/slider/slider.md
- src/slider/slider.tsx
- src/slider/type.ts
https://github.com/Tencent/tdesign-vue-next/issues/3772
- feat(Slider): 实现 `changeEnd` 事件 ([issue #3772](https://github.com/Tencent/tdesign-vue-next/issues/3772))
> feat(slider): 实现changeEnd事件

- src/cascader/core/helper.ts
#3793 
- fix(Cascader): 修复`mutiple & show-all-levels = false` 的场景下设置`value`为`options`内不存在的值报错
> fix(Cascader): fix set a value that does not exist will get error

- src/table/hooks/useDragSort.ts
https://github.com/Tencent/tdesign-vue-next/issues/2847
- fix(Table): 拖拽排序场景，修复通过 `push` 新增 `data` 元素后，被添加的新元素出现在第一列问题
> fix(table): drag sort works not properly with data.push

- CHANGELOG.md
- package.json
> docs: release 1.8.0

- site/docs/getting-started.en-US.md
- site/docs/getting-started.md
- docs: 更新`webpack`中使用`unplugin`的说明文档
> docs: update unplugin usage desc with webpack

- src/input/input.tsx
> fix(Input): 禁用状态下focused样式未消除

- global.d.ts
> chore(volar): update global.d.ts

- src/tree-select/tree-select.tsx
- #3833
- #3852
- fix(TreeSelect): 修复可过滤开启时搜索框内容与 filter 函数不同步更新的问题
> fix(tree-select): filterByText keep pace with innerInputValue

- src/form/type.ts
fix #3874 
- fix(Form): `FormRule` 规则中 `trigger` 值类型缺失 `all` 选项
> fix(form): the 'all' option is missing for the 'trigger' value type

- src/form/form-model.ts
- src/textarea/textarea.tsx
- src/utils/helper.ts
- https://github.com/Tencent/tdesign-common/pull/1719
- https://github.com/Tencent/tdesign-common/pull/1718
- https://github.com/Tencent/tdesign-common/pull/1717
- fix(Form): 修复计算`^`字符异常的问题
- fix(Tabs): 修复层级问题影响 `action`区域操作的问题
- fix(Loading): 修复未设置 `z-index` 默认值的问题 @betavs 
- chore: `getCharacterLength` 方法统一从 common维护
> fix(Form): fix calc str length error

- src/tabs/tab-nav.tsx
- src/tabs/tabs.tsx
fix #3889 
- fix(Tabs): 逻辑容错处理
> fix(tabs): logical fault tolerance processing

- src/radio/useKeyboard.ts
https://github.com/Tencent/tdesign-vue-next-starter/issues/669
回车控制台报错
> fix(radio): 回车控制台报错

- src/form/form.en-US.md
- src/form/form.md
> docs(form): trigger api文档更新

- src/tree/_example/controlled.vue
- src/tree/_example/debug-data.vue
- src/tree/_example/expand-all.vue
- src/tree/_example/load.vue
> fix tree demo problems

- src/date-picker/hooks/useRange.tsx
- src/date-picker/hooks/useSingle.tsx
- fix(DatePicker): 修复单独配置`popupProps`的`on-visible-change`功能异常的问题
> fix(date-picker): popup visible-change callback

- src/slider/__tests__/behavior.test.jsx
- src/slider/hooks/useSliderInput.tsx
- fix(Slider): 修复`inputProps`的`onChange`事件无法正常触发的问题
> fix(Slider): fix inputProps onChange callback event

- src/table/interface.ts
- src/table/table.en-US.md
- src/table/table.md
- src/table/type.ts
- fix(Table): 完善 Table 组件 Typescript 类型定义
> fix(table): fix typescript error

- src/common.ts
- src/descriptions/descriptions-row.tsx
- src/descriptions/descriptions.tsx
- feat(Description): `layout` 类型定义调整为字符串多类型
> feat(descriptions): make layout type to be multiple type

- src/tree/_example-ts/icon.vue
- src/tree/_example/icon.vue
- src/tree/tree.en-US.md
- src/tree/tree.md
- src/tree/type.ts
fix tree ts error
- fix(Tree): 修复`Tree`TypeScript类型错误
> Fix:Tree ts error

- src/form/form-model.ts
fix #3957 
- fix(Form): 校验判断不严谨的问题
> fix(form): problems with loose verification judgments

- src/table/hooks/useFixed.ts
- src/table/hooks/useTreeDataExpand.ts
- fix(Table): 树形结构表格，修复同时异步设置 `data` 和 `expandedTreeNodes` 时，展开节点无效问题（延迟设置有效），[issue#3873](https://github.com/Tencent/tdesign-vue-next/issues/3873)
- fix(Table): 固定列表格，在 Dialog 中固定列宽度被挤压问题，[issue#3844](https://github.com/Tencent/tdesign-vue-next/issues/3844)
> fix(table): expandedTreeNodes default expand

- src/table/base-table.tsx
修正 affix 的 footer，高度可能计算 error 到时渲染异常的问题
> fix(Affix): 修正 margin 计算,避免出现 error

- src/table/base-table.tsx
修正在其余会导致footer高度更新的场景下,footer没有被正常刷新的问题
> fix: 🐛 修正在其余会导致footer高度更新的场景下,footer没有被正常刷新的问题

- src/table/_example-ts/fixed-column.vue
- src/table/_example-ts/fixed-header.vue
- src/table/_example/fixed-column.vue
- src/table/_example/fixed-header.vue
- fix(table): table demo missing some function definition.
> docs(table): update table demo

- src/hooks/tnode.ts
- src/slider/hooks/useSliderTooltip.tsx
- src/slider/slider-button.tsx
- src/utils/render-tnode.ts
- feat(Slider): 支持通过 `label=null` 或 `label=false` 隐藏滑块数字浮层
> feat(Slider): support label=null/false to hide label tip

- src/config-provider/config-provider.en-US.md
- src/config-provider/config-provider.md
- src/config-provider/type.ts
- src/table/base-table-props.ts
- src/table/base-table.tsx
- src/table/hooks/useStyle.ts
- src/table/primary-table.tsx
- src/table/table.en-US.md
- src/table/table.md
- src/table/type.ts
https://github.com/Tencent/tdesign-vue-next/issues/3978
- feat(table): 支持全局配置 size
> feat(table): 支持全局配置 size

- .vscode/settings.json
- site/docs/getting-started.en-US.md
- site/docs/getting-started.md
- feat: 新增 `@tdesign-vue-next/nuxt` 支持在 `nuxt 3` 框架中使用，详情请参考快速开始的内容
> docs: update usage for nuxt 3

- src/color-picker/panel/index.tsx
fix #4002 
- fix(ColorPicker): `color` 值未同步更新
> fix(color-picker): the color value is not updated synchronously

- CHANGELOG.md
- package.json
> docs: release 1.9.0

- global.d.ts
- helper/attributes.json
- helper/tags.json
- helper/web-types.json
fix: https://github.com/Tencent/tdesign-vue-next/issues/4013
fixed: https://github.com/TDesignOteam/tdesign-api/pull/229
> fix: 编辑器提示更新

- README-zh_CN.md
- README.md
> chore: update group code

- src/breadcrumb/breadcrumb-item-props.ts
- src/breadcrumb/breadcrumb-item.tsx
- src/breadcrumb/breadcrumb.en-US.md
- src/breadcrumb/breadcrumb.md
- src/breadcrumb/type.ts
- https://github.com/Tencent/tdesign-vue-next/issues/3905
- feat(Breadcrumb): `breadcrumb-item`新增 `click` 事件
> feat(breadcrumb): item add click event

- src/notification/plugin.ts
- src/notification/type.ts
#3995 
- fix(Notification): `NotifyPlugin` 返回错误 `NotificationInstance` 导致 `NotifyPlugin.close` 函数错误关闭组件。
> fix(Notification): `NotificationFunction` return error `NotificationInstance` (#3995)

- helper/attributes.json
- helper/tags.json
- helper/web-types.json
- https://github.com/Tencent/tdesign-vue/issues/3099
- 相关PR https://github.com/Tencent/tdesign-common/pull/1745
- fix(Descriptions): 修复编辑器对`t-descriptions-item`组件的提示缺失问题
- fix(Descriptions): 优化自适应宽度的问题
> fix(Descriptions): fix descriptions item prompt

- src/cascader/core/effect.ts
- src/cascader/core/helper.ts
fix #4021 
- fix(Cascader): 修复 `value` 数据回填异常导致样式失效问题
> fix(cascader): options update error (#4021)

- src/loading/plugin.tsx
- src/message/plugin.tsx
- src/notification/plugin.ts
导出`LoadingPlugin` `MessagePlugin`，提供给tdesign-nuxt 模块使用
https://github.com/TDesignOteam/tdesign-nuxt/pull/9
删除 `export const Notify = NotificationPlugin;`
https://github.com/Tencent/tdesign-vue-next/pull/3929 PR 引入的
> feat: export plugin

- src/tabs/props.ts
- src/tabs/tab-nav.tsx
- src/tabs/type.ts
- fix(Tabs): 修复使用 `action` 时控制台告警的问题
> fix(tabs): fix warning when using action api

- CHANGELOG.md
- package.json
> docs: release 1.9.1

- package.json
- src/form/form-item.tsx
- src/index.ts
- src/loading/directive.ts
- src/loading/index.ts
- fix(Form): 修复`1.9.1`版本的告警问题
- fix(Loading): 修复`1.9.1`版本对外暴露directive使用的告警及命名错误
> fix: fix 1.9.1 version warning

- CHANGELOG.md
- package.json
> docs: release 1.9.2

- CHANGELOG.md
- package.json
- src/date-picker/DatePicker.tsx
> chore: release/1.9.3

- src/range-input/range-input.tsx
fix: https://github.com/Tencent/tdesign-vue-next/issues/4073
- fix(range-input): separator 插槽无效
> fix(range-input): separator slot

- src/dialog/dialog.en-US.md
- src/dialog/dialog.md
https://github.com/Tencent/tdesign-vue/issues/3112
- docs(dialog): mention destroy DOM elements in dialog.md; update translations
> docs(dialog): mention destroy DOM elements in dialog.md; update translations

- src/popup/popup.tsx
- fix(Popup): 修复在 webcomponent 场景下由于shadowroot 导致document判断异常引起的展示问题
> fix(popup): disappear when mounted within webcomponent shadow root

- global.d.ts
> fix(type): update global.d.ts

- src/date-picker/DatePicker.tsx
- #4100
- fix(DatePicker): 修复`1.9.3`版本中周和季度模式选择异常的问题
> fix(DatePicker): fix week and quarter parse

- src/hooks/useDragSort.tsx
- [拖拽功能与手动新增结合使用时出现异常问题](https://github.com/Tencent/tdesign-vue-next/issues/4106)
- fix(Tabs): 修复拖拽排序后手动新增 tab 位置异常问题
> fix(Tabs): added error after dragSort

- src/skeleton/skeleton.tsx
#4118 
* fix(Skeleton): 修复设置delay延迟并且loading为true时，无法在到达delay时间前取消准备到来的loading
- [x ] 文档已补充或无须补充
- [x ] 代码演示已提供或无须提供
- [x ] TypeScript 定义已补充或无须补充
- [ x] Changelog 已提供或无须提供
> fix(Skeleton): 修复设置delay延迟并且loading为true时，无法在到达delay时间前取消准备到来的loading

- src/cascader/components/Item.tsx
#3980 
- 需求背景：自定义渲染内容支持多选
- 解决方案：增加是否是自定义并且多选状态 isOptionChildAndMultiple
- fix(Cascader): 修复自定义渲染内容不支持多选
> fix(cascader): fix custom options multiple selection

- CHANGELOG.md
- package.json
> docs: release 1.9.4

- CHANGELOG.md
> chore: remove duplicated CHANGELOG

- src/hooks/useVirtualScrollNew.ts
- fix(Table): 修正虚拟滚动下滚动到指定行的错误
> fix(table): 修正虚拟滚动下,滚动到某一行的计算错误

- src/transfer/transfer.tsx
- src/transfer/utils.ts
- #4115 
> 此问题在Vue2版本中已有修复方案,直接迁移修复方案https://github.com/Tencent/tdesign-vue/pull/2599
- fix(transfer): 修复穿梭框存在默认已选且不允许移除的值仍可移除的异常问题
> fix(transfer): fix disabled value removed from target

- src/upload/_usage/props.json
- src/upload/type.ts
- src/upload/upload.en-US.md
- src/upload/upload.md
> docs(upload): [Upload]method的包含的http请求方法描述option改为options

- package.json
- src/breadcrumb/breadcrumb-item.tsx
- src/table/ellipsis.tsx
- src/utils/dom.ts
- 需求背景：scrollWidth  clientWidth 这两个值相等的话 鼠标放上去是不显示 Tooltip
- 解决方案：修改判断条件 scrollWidth >= clientWidth 显示 Tooltip
- fix(table): 修改表格判断内容是否溢出
> fix: 修改Table表格判断内容是否溢出Fix

- src/textarea/calcTextareaHeight.ts
- fix(Textarea): 兼容组件销毁情况下，元素不存在导致报错的问题
> fix(Textarea): 修正偶发处理输入框高度时如果组件已被销毁，导致元素不存在从而报错的问题

- src/hooks/useDisabled.ts
- src/radio/props.ts
- src/radio/radio-group-props.ts
- src/radio/radio.en-US.md
- src/radio/radio.md
- src/radio/radio.tsx
- src/radio/type.ts
API 修改https://github.com/TDesignOteam/tdesign-api/pull/277
- feat(Radio): 禁用优先级Radio.disabled > RadioGroup.disabled > Form.disabled
> feat(Radio): radio disabled priority adjustment

- CHANGELOG.md
- package.json
> docs: release 1.9.5

- src/table/_example-ts/editable-cell.vue
> docs(table): table editable-cell example fix

- src/tabs/tab-nav-bar.tsx
#4204 
用 getBoundingClientRect 获取元素本身的 width 用于计算 bar 偏移量
- fix(tabs): fix inaccurate positioning of tabs slider
> fix(tabs): fix inaccurate positioning of tabs slider

- package.json
> chore: upgrade site component version

- src/button/button.en-US.md
- src/button/button.md
- src/button/button.tsx
- src/button/props.ts
- src/button/type.ts
- #4190
- feat(Button): 新增 `loadingProps` API
> feat(button): support loadingProps API

- src/table/filter-controller.tsx
- fix(Table): 修复`filter.type`的告警逻辑问题
> fix(table): fix filter type warning

- src/tree-select/tree-select.tsx
> feat(tree-select): expose treeRef

- src/select-input/interface.ts
- src/select-input/useSingle.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/4203
- fix(Cascader): 修复 `autofocus` 功能失效的问题
> fix(cascader): fix autofocus

- CHANGELOG.md
- package.json
> chore: release 1.9.6

- src/pagination/pagination.tsx
#4275
- fix(Pagination): 选择器更改时内部当前值未修改
> fix(pagination): inner current value is not modified when selector change

- src/image-viewer/base/ImageItem.tsx
- fix(image-viewer): 修复左右切换图片时未能按照 svg 显示的问题
> fix(image-viewer): 修复左右切换图片时 svg 显示没生效的问题

- src/image-viewer/base/ImageItem.tsx
- src/image-viewer/image-viewer.en-US.md
- src/image-viewer/image-viewer.md
> feat(image-viewer): optimize element selector

- .github/workflows/pr-comment-ci.yml
> ci(pr-comment-ci): fix submodules

- .github/workflows/pr-comment-ci.yml
> ci(pr-comment-ci): fix node version

- .github/workflows/pr-comment-ci.yml
> ci(pr-comment-ci): fix trigger CI

- src/date-picker/base/Header.tsx
- src/date-picker/panel/RangePanel.tsx
- src/date-picker/panel/SinglePanel.tsx
[[DatePicker] 选择器模式mode属性，动态改变值时选择器面板中 Header 组件显示错误 #4291](https://github.com/Tencent/tdesign-vue-next/issues/4291)
- 日期选择器切换 mode 时, 组件表现没有与 mode 对应
- fix(DatePicker): 修复切换 `mode`时，日期选择器切换头部显示错误的问题
- fix(DatePicker): 修复切换 `mode` 时，`format` 未匹配导致组件解析失败的问题
> fix(DatePicker): fix header reactive display error

- script/rollup.config.js
- feat: 单独导出涉及 `Plugin` 相关组件的样式，支持修改前缀的部分场景使用
> feat: export plugin css file

- CHANGELOG.md
- package.json
> docs: release 1.9.7

- src/statistic/props.ts
- src/statistic/statistic.en-US.md
- src/statistic/statistic.md
- src/statistic/type.ts
- src/watermark/props.ts
- src/watermark/type.ts
- src/watermark/watermark.en-US.md
- src/watermark/watermark.md
https://github.com/Tencent/tdesign-vue-next/issues/4367
> docs: update doc

- src/date-picker/date-picker.en-US.md
- src/date-picker/date-picker.md
- src/date-picker/date-range-picker-props.ts
https://github.com/Tencent/tdesign-vue-next/issues/4374
- fix(DateRangePicker): 修复在`Form`表单处于禁用时，禁用不生效
> fix(date-range-picker): form disabled not work

- helper/attributes.json
- helper/web-types.json
- src/table/base-table-props.ts
- src/table/table.md
- src/table/type.ts
> chore(table): fix typo

- CHANGELOG.md
- package.json
- src/breadcrumb/breadcrumb-item.tsx
- src/notification/notification.tsx
> docs: release 1.9.8

- src/progress/progress.en-US.md
- src/progress/progress.md
- src/progress/props.ts
- src/progress/type.ts
https://github.com/TDesignOteam/tdesign-api/pull/337
- docs(Progress): TS类型改名 `StatusEnum`=>`ProgressStatus`,`ThemeEnum`=>`ProgressTheme`
> docs(Progress): sync api

- src/card/__tests__/index.test.jsx
test(card): add loadingProps test case
> test(card): add loadingProps test case

- src/badge/badge.tsx
> refactor(badge): optimize code

- src/upload/themes/multiple-flow-list.tsx
- src/upload/upload.tsx
- fix(Upload): 修复部分图标不支持全局替换的问题
> fix(Upload): fix global icon replacement

- src/timeline/timeline.md
> docs(Timeline): fix typo

- src/tabs/tab-nav-bar.tsx
-  #4396
- fix(tabs): 修复 `t-tabs__bar` 在 `dialog` 中的尺寸问题
> fix(tabs): 修复 `t-tabs__bar` 在 `dialog` 中的尺寸问题

- src/tag-input/__tests__/vitest-tag-input.test.jsx
- src/tag-input/useTagList.tsx
- fix(TagInput): 修复`tagProps` 没有作用到折叠的标签上的缺陷
> fix(TagInput): tagProps should effect minCollapseNum tag 

- src/button/_usage/props.json
- chore(Button): remove `ghost` config from live demo
> chore: remove ghost config from live demo

- src/range-input/range-input.tsx
#4451
- fix(RangeInput): 清空图标不能正常显示
> fix(range-input): empty icons cannot be displayed properly

- .github/workflows/pr-comment-ci.yml
> fix(pr-comment-ci): resolve update-common

- src/tabs/tab-nav-item.tsx
- fix(Tabs): 修复`Tabs`组件在全局替换图标下，存在替换组件 `event` 事件导致移除操作异常的问题
> fix(Tabs): fix tab replace icon event bug

- src/image/image.tsx
- style(Image): 使用 `lodash/isString` 处理字符串类型判断
> refactor(image): replace typeof method with isString

- CHANGELOG.md
- package.json
> docs: update version

- src/table/_example-ts/pagination-ajax.vue
- src/table/_example/pagination-ajax.vue
- docs(Table): 修复分页文档的展示示例错误问题
> docs(table): fix pagination demo

- src/color-picker/panel/format/index.tsx
> fix(color-picker): fix colorPicker selectInputProps attribute

- src/time-picker/panel/single-panel.tsx
- https://github.com/Tencent/tdesign-vue/pull/3280
- https://github.com/Tencent/tdesign-common/pull/1906
- fix(TimePicker): 修复format 仅支持 HH:mm:ss 格式的问题
> fix(time-picker): resolve TIME_FORMAT RegExp

- src/config-provider/config-provider.en-US.md
- src/config-provider/config-provider.md
> chore: complete classprefix docs

- site/docs/getting-started.md
> docs(site): browser compatibility link error

- src/hooks/useVirtualScrollNew.ts
https://github.com/Tencent/tdesign-vue-next/issues/4511
- 追加空值判断
- fix(list): 修复使用虚拟滚动列表时使用 `v-if` 展示的场景容器未判空异常的问题
> fix(List): fix error when using virtual scroll since the container element is null

- src/list/list-item.tsx
list-item的props不生效
导入props错误，正确导入相应文件
- fix(List): 修复 `list-item`的props错误导致部分API不生效的问题
> fix(List):  fix list-item props

- src/table/ellipsis.tsx
- fix(Table): 修复拖拽调整列宽之后超出省略样式丢失的问题
> fix(table): fix ellipsis status after resizing

- CHANGELOG.md
- package.json
> docs: release 1.10.0

- site/src/app.vue
> feat(site): component Internationalization

- src/select/hooks/useSelectOptions.ts
- fix(Select): 修复当 `Form` 开启 `disabled`，`Select` 关闭 `disabled` 状态下选项仍然展示禁用的错误
> fix(select): fix option disabled status when form disabled is true and select disabled is false

- src/locale/it_IT.ts
- src/locale/ru_RU.ts
- https://github.com/Tencent/tdesign-vue-next/issues/4591
- feat(i18n): 国际化新增 意大利语`it_IT ` 俄语`ru_RU `
> fix(i18n): add it_IT ru_RU

- src/image-viewer/base/ImageItem.tsx
> feat(image-viewer): add bg color

- src/transfer/components/transfer-search.tsx
close #4578 
- fix(Transfer): `search` 事件缺少 `trigger` 参数
> fix(transfer): search event is missing trigger parameters

- src/image-viewer/base/ImageItem.tsx
- https://github.com/Tencent/tdesign-vue-next/pull/4596
> feat(image-viewer): fix container layout

- src/input-number/props.ts
1. 解决数字输入框小数位数类型定义错误问题，由 `String` 改为 `Number` 类型
- fix(InputNumber): 解决数字输入框小数位数类型定义错误问题，由 `String` 改为 `Number` 类型
> fix(input-number): type of decimalPlaces props should be number and object

- src/textarea/textarea.tsx
- #4472
- fix(textarea ): 修复设置`autosize`且切换页面时组件异常的问题 @origin-coding 
> fix(textarea ): calculate the height of textarea after leaving the page

- src/range-input/range-input.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/4607
修复 https://github.com/Tencent/tdesign-vue-next/pull/4453   值为null，引发报错
- fix(rangInput): 修复开启 `clearable ` 值为空报错
> fix(range-input): innerValue is null

- src/date-picker/_example-ts/week.vue
- src/date-picker/_example/date-range.vue
- src/date-picker/panel/RangePanel.tsx
- src/range-input/range-input.tsx
- src/time-picker/time-range-picker.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/4566
- https://github.com/Tencent/tdesign-vue-next/issues/4427
- https://github.com/Tencent/tdesign-vue-next/issues/4382
- fix(DateRangePicker): 修复日期区间选择器配置时间相关格式时，没有正确处理`defaultTime`的问题
- fix(DatePicker): 修复周选择器下，年份边界日期返回格式错误的问题
- feat(TimePicker): 支持时间区间选择器自动调整左右区间
- docs(DatePicker): 优化周选择器配合 `firstDayOfWeek` 使用的问题，详情请参考周选择器示例代码
> fix(DatePicker): fix defaultTime bug in range and fix boundary week result

- CHANGELOG.md
- package.json
> docs: release 1.10.2

- .vscode/settings.json
- site/plugin-doc/demo.js
- site/src/components/codeSandbox/content.js
- site/src/components/codeSandbox/index.vue
migrate it to `vue-cli` startup now.
- docs: 修复`Codesandbox`示例启动失败或需要打开 devbox 才可以运行的问题
> fix(site): failed to launch `codesandbox` demo

- src/select/_example-ts/scroll-bottom.vue
- src/select/_example/scroll-bottom.vue
- src/select/select-panel.tsx
- src/select/select.tsx
https://github.com/Tencent/tdesign-vue-next/issues/4528
当前问题
1. 滚动条触底会一直触发无限触发触底事件
2. 列表内容暂时被清空，高度突然变化. loading 解除时，滚动条也会自动回到头部
解决方法：
loading 改为 fixed 定位，浮动在下拉面板顶部
效果：
- fix(Select): loading 配合触底事件 onScrollToBottom 一起使用的问题
> fix(select): loading 配合触底事件 onScrollToBottom 一起使用的问题

- src/tree/__tests__/expand.test.jsx
- src/tree/hooks/useTreeAction.ts
close #4571
- fix(tree): custom icons cannot be clicked without child nodes
> fix(tree): custom icons cannot be clicked without child nodes

- src/time-picker/_usage/time-range-picker-props.json
- src/time-picker/time-picker.en-US.md
- src/time-picker/time-picker.md
- src/time-picker/time-range-picker-props.ts
- src/time-picker/time-range-picker.tsx
- src/time-picker/type.ts
- feat(TimePicker): 新增 `autoSwap` API，支持`1.10.2` 版本之后仍支持保持选定的左右侧时间大小顺序
> feat(timepicker): support autoSwap API

- src/date-picker/DateRangePickerPanel.tsx
相关: https://github.com/Tencent/tdesign-vue/issues/3368
- fix(DatePicker): panel top arrow doesn't work when using week mode
> fix(DatePicker): panel top arrow doesn't work when using week mode

- src/input/useInput.ts
[Input 组件设置属性 type="number" 时，无法完成小数位末尾的 0 输入](https://github.com/Tencent/tdesign-vue-next/issues/4658)
- fix(Input): 修复 Input type="number" 时，无法输入小数位末尾 0 的问题
> fix(Input): 修复 Input type="number" 时，无法输入小数位末尾 0 的问题

- src/table/table.md
- docs(table): 修复`table`的API文档中多余的`。`
> fix(site) Table API document content error

- src/select-input/select-input.tsx
- src/select/hooks/useKeyboardControl.ts
- src/select/option.tsx
- src/select/select-panel.tsx
- src/select/select.tsx
- https://stackblitz.com/edit/3nxrka-h5aczr?file=src%2Fdemo.vue
- fix(Select): 修复使用虚拟滚动配合过滤加自定义渲染内容时渲染异常的问题
- fix(Select): 修复可过滤场景下回车键会清空输入框的错误交互行为
- chore(Select): 部分节点事件增加容错判断
> fix(Select): fix render when using virtual scroll with custom label

- src/drawer/drawer.tsx
- https://github.com/Tencent/tdesign-vue/issues/3360
- https://github.com/Tencent/tdesign-vue/issues/3356
此前计算滚动条的方式是基于浏览器默认宽度，定制滚动条的场景会失效，修改计算滚动条的方式，相关PR如下
- https://github.com/Tencent/tdesign-common/pull/1968
Drawer中对是否存在滚动条的判断存在问题，调整判断方式，配合common调整，使 Drawer 开启正确计算scrollbar宽度
- fix(Drawer): 修复打开 `drawer` 时页面抖动的问题
- fix(Dialog): 修复打开 `dialog` 时页面抖动的问题 @RSS1102 
> fix: fix page shaking when dialog and drawer show

- CHANGELOG.md
> chore(CHANGELOG): fix typos

- src/button/_usage/props.json
- https://github.com/Tencent/tdesign-vue-next/issues/4684
- Docs(button): 修复`Button`组件`BaseUsage`中`默认的theme`不是`default`
> fix(button): button base-usage default theme isn’t `default`

- src/avatar/avatar.tsx
https://github.com/Tencent/tdesign-vue-next/issues/4723
头像链接切换后，清除上一个图片加载失败的占位符
- fix(Avatar): 头像链接切换后，清除上一张图片加载失败的占位符
> fix(Avatar): 🐛 修正头像图片链接的响应式

- package.json
- src/icon/icon.en-US.md
- src/icon/icon.md
- feat(Icon): 图标库发布 `0.3.0`版本，新增 907 个新图标；命名优化`blockchain` 重命名改为`transform-1`,`gesture-pray-1`重命名为`gesture-open`,`gesture-ranslation-1`重命名为`wave-bye`, `gesture-up-1`重命名为`gesture-typing`,`gesture-up-2`重命名为`gesture-right-slip`,`logo-wechat`重命名为`logo-wechat-stroke-filled`，移除`tree-list`、`logo-adobe-photoshop-1` 等错误图标
- docs(Icon): 优化图标检索功能，支持中英文搜索图标
> feat(Icon): new version

- site/src/components/components.jsx
> chore: replace version request

- src/input/useInputWidth.ts
https://github.com/Tencent/tdesign-vue-next/issues/4727
替换获取宽度使用的api
- fix(Input): 修正自动宽度下，宽度精度带来的错误省略问题
> fix: 🐛 修正自动宽度下获取宽度精度的问题

- src/input-number/hooks/useInputNumber.tsx
- fix(InputNumber): 修复 `largeNumber` 下 `format` 错误作用于 `value` 上的问题
> fix(input-number): fix largenumber format bug

- CHANGELOG.md
> chore(CHANGELOG): fix  format 

- src/dropdown/_example/icon.vue
JavaScript示例里 prefixIcon 字段应该调整为函数形式。
- fix(Dropdown): 示例里 `prefixIcon` 字段应该调整为函数形式
- [] 本条 PR 不需要纳入 Changelog
> docs(dropdown): revise prefixIcon

- site/site.config.mjs
- docs(chat): 增加高阶组件 `AI Chat 对话` 入口
> docs(chat): add chat component link

- src/color-picker/const.ts
- src/color-picker/panel/format/index.tsx
- src/color-picker/panel/header.tsx
- src/color-picker/panel/index.tsx
- src/color-picker/panel/linear-gradient.tsx
- src/color-picker/panel/saturation.tsx
- src/color-picker/panel/slider.tsx
common: https://github.com/Tencent/tdesign-common/pull/1986
> fix(colorPicker): fix colorMode i18n

- src/dropdown/dropdown.tsx
#4773 
- fix(Dropdown): 当 `options` 为空时，控制台报错的问题
> fix(dropdown): when options is empty, the console reports an error

- src/table/enhanced-table.tsx
https://github.com/Tencent/tdesign-vue-next/issues/4780
fix(Table): 修复 `enhanced-table` 中 `disableDataPage` 参数传递问题
> fix(table): 修复 enhanced-table disableDataPage props 传递问题

- src/transfer/hooks/useDragSort.ts
- src/transfer/utils.ts
- 树形组件选项禁用 https://github.com/Tencent/tdesign-vue-next/issues/4809
- 拖拽排序向后移动
https://github.com/user-attachments/assets/c25ca283-9c06-4dbd-807b-a7cb2911816d
- fix(Transfer): 修复树形组件选项禁用在全选下仍可选中的缺陷
- fix(Transer): 修复拖拽排序向后移动的功能异常
> fix(Transfer): fix tree disabled and drag sort bug

- CHANGELOG.md
- package.json
> docs: release 1.10.5

- src/table/hooks/useFilter.tsx
表格组件在有筛选项时如果清除筛选，会直接报错，无法进行清除操作
经查是由于useFilter.tsx中isFilterValueExist里isObjectTrue判断缺失对null值的处理
- fix(table): 修复isFilterValueExist无法正常处理null值导致无法正常清除筛选的问题
> fix(Table): handle null values in isFilterValueExist

- src/table/__tests__/base.test.jsx
- src/table/filter-controller.tsx
fix https://github.com/Tencent/tdesign-vue-next/issues/4836
- fix(Table): 修复 `filterIcon` 不生效
> fix(table): resolve props.filterIcon not work

- src/swiper/swiper.tsx
https://github.com/Tencent/tdesign-vue-next/issues/4844
vue2
- fix(Swiper): 修复 `autopaly=false`,  修改 `current` 无效 
> fix(swiper): resolve change  props.current not work

- src/slider/slider-button.tsx
- #4859 
- fix(Slider): 滑块可以正常在移动端设备中拖动
> fix(Slider): slider btn cannot drag in mobile device

- src/table/primary-table.tsx
- fix(Table): 修复 1.10 版本的`updateEditedCellValue`的功能异常问题
> fix(table): fix editable table bug

- src/table/hooks/useEditableRow.ts
- src/table/hooks/useRowspanAndColspan.ts
- https://github.com/Tencent/tdesign-vue-next/issues/3812
- https://github.com/Tencent/tdesign-vue-next/issues/3148
- fix(Table): 修复删除行操作后使用 `validateTableData` 方法进行校验仍存在删除行的问题
> fix(Table): fix validateData result when remove row from table data

- src/date-picker/DateRangePicker.tsx
#4867
- fix(DateRangePicker): 修复开始结束值同时存在的逻辑判断错误问题
> fix(date-range-picker): logical judgment error when start and end values exist at the same time

- src/tree/hooks/useTreeScroll.ts
- fix(Tree): 修复使用`keys`定义`value`无法配合 `scrollTo` 一起使用的问题
> fix(Tree): support using scrollTo together with keys

- CHANGELOG.md
- package.json
> chore: update version

- helper/attributes.json
- helper/tags.json
- helper/web-types.json
- src/descriptions/descriptions.en-US.md
https://github.com/TDesignOteam/tdesign-api/pull/504
- feat(Plugin): 更新插件提示内容
> docs: fix typo

- src/progress/progress.tsx
#4894 
- fix(progress): Fix the abnormal statusStyle in the progress
> fix(progress): Fix the abnormal statusStyle in the progress

- src/auto-complete/__tests__/index.test.jsx
- src/auto-complete/auto-complete.tsx
- src/auto-complete/option-list.tsx
- src/config-provider/type.ts
from https://github.com/Tencent/tdesign-react/issues/3292
- fix(AutoComplete): 当选项为空时显示效果异常的问题
> fix(auto-complete): the display effect is abnormal when the option is empty

- src/select/select-panel.tsx
- fix(Select): 修复使用`empty` API 定义缺失默认样式的问题
> fix(select): fix empty usage slot style missing

- site/src/components/demo-page.vue
开发环境访问 http://localhost:17000/vue-next/demos/auto-complete/base
报错
```
main.js:34 TypeError: (intermediate value).globEager is not a function
```
> chore: fix globEager is not a function

- site/src/components/demo-page.vue
Reverts Tencent/tdesign-vue-next#4924
> Revert "chore: fix globEager is not a function"

- package.json
- site/docs/getting-started.md
- site/src/app.vue
- site/src/components/components.jsx
- 站点新增支持AI搜索体验,  支持`键入式的提问`、`划词解释`以及`指定 API 示例代码生成`三种使用方式
- docs: 站点新增支持AI搜索体验,  支持`键入式的提问`、`划词解释`以及`指定 API 示例代码生成`三种使用方式
> docs: add AI search

- src/descriptions/descriptions.en-US.md
- src/descriptions/descriptions.md
close #4534 
- docs(descriptions): 添加对于 `labelStyle` 的使用说明
> docs(descriptions): add `labelStyle` usage instruction

- .eslintrc
改lodash-es 后，npm 安装 ，lodash 可能存在于幽灵依赖，会被误用使用，项目启用eslint 规则 禁止使用lodash
> chore(eslint): restricted import lodash

- packages/components/tree/hooks/useTreeStore.ts
re: https://github.com/Tencent/tdesign-vue-next/pull/4954
- fix(Tree): 修复动态切换 `expandAll` 的功能异常问题
> fix(Tree): fix expandAll dynamic change behavior

- packages/components/back-top/back-top.en-US.md
- packages/components/back-top/back-top.md
- site/src/components/demo-page.vue
- to fix format of https://tdesign.tencent.com/vue-next/components/back-top?tab=api 
- to fix https://tdesign.tencent.com/vue-next/demos/button/base
> chore: fix demos routes

- packages/components/calendar/calendar.en-US.md
- packages/components/calendar/calendar.md
> chore: fix calendar docs format

- .github/workflows/pr-comment-ci.yml
> ci: update pr-comment-ci

- .github/workflows/pr-comment-ci.yml
> ci(pr-comment-ci): add  setup pnpm

- packages/components/statistic/statistic.tsx
https://github.com/Tencent/tdesign-common/pull/1660
- fix(Statistic): 修复 decimalPlaces=0 时数值动画期间精度错误的问题
> fix(statistic): fix decimalPlaces setting 0 is invalid

- packages/tdesign-vue-next/site/vite.config.js
访问 http://localhost:17000/vue-next/demos/divider/base
> fix(site): fix vite serving allow list

- packages/tdesign-vue-next/site/package.json
> chore: update ai chat

- packages/tdesign-vue-next/site/docs/getting-started.en-US.md
- packages/tdesign-vue-next/site/docs/getting-started.md
> docs: update nuxt install  doc

- .github/workflows/auto-release.yml
- .github/workflows/pr-compressed-size.yml
> chore: fix publish ci

- packages/tdesign-vue-next/package.json
- to test publish npm package workflow based on mono repo 
> chore: release 1.11.0-beta.1

- packages/components/tag-input/hooks/style/css.js
- packages/components/tag-input/hooks/style/index.js
- packages/tdesign-vue-next/site/src/components/components.jsx
> chore: ignore beta version

- CONTRIBUTING.md
- packages/tdesign-vue-next/test/README.md
- packages/tdesign-vue-next/test/package.json
- up CONTRIBUTING.md and test README.md
- docs: up CONTRIBUTING.md and test README.md
> docs: up CONTRIBUTING.md and test README.md

- packages/components/select-input/select-input.tsx
- packages/components/select-input/useMultiple.tsx
- packages/components/select/select.tsx
#5078
- fix(Select): 多选情况下点击清除按钮重复触发 `change` 事件的问题
> refactor(select): improve tag removal logic and update context handling

- packages/components/select/select.tsx
https://github.com/Tencent/tdesign-vue-next/pull/5092
> chore(select): fix type import path

- packages/tdesign-vue-next/site/package.json
- packages/tdesign-vue-next/site/src/app.vue
- chore: optimize prompt to get better demo result
> chore: optimize ai search

- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
> chore: release 1.11.0

- .github/workflows/pkg-pr-new.yml
> ci(pkg-pr-new): add running conditions

- .github/workflows/pr-comment-ci.yml
> ci(pr-comment-ci): fix check snap conflict

- packages/components/list/list.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/5112
- fix(List): 修复`1.11.0`版本`scrollTo`实例方法异常的问题
> fix(List): fix scrollTo instance func

- packages/components/dialog/dialog-card.tsx
- packages/components/dialog/dialog.tsx
- packages/components/tree/hooks/useDragHandle.ts
- packages/components/tree/tree-types.ts
- https://github.com/Tencent/tdesign-vue-next/issues/5122
- fix(Dialog): 修复`1.11.0`版本的控制台报错问题
> fix: dialogCard Console Warn

- packages/components/auto-complete/auto-complete.tsx
- packages/components/common-components/fake-arrow.tsx
- packages/components/config-provider/config-provider.tsx
- packages/components/config-provider/hooks/index.ts
- packages/components/config-provider/hooks/useConfig.ts
- packages/components/config-provider/utils/context.ts
- packages/components/config-provider/utils/index.ts
- packages/components/hooks/useConfig.ts
- packages/components/hooks/useKeepAnimation.ts
- packages/components/image/image.tsx
- packages/components/tag-input/tag-input.tsx
- packages/components/typography/ellipsis.tsx
- packages/components/typography/text.tsx
- refactor(common-components): component optimization
> refactor(common-components): component optimization

- packages/tdesign-vue-next/CHANGELOG.md
> chore: CHANGELOG typo

- packages/components/layout/aside.tsx
- packages/components/layout/header.tsx
- packages/components/layout/layout.tsx
- packages/components/loading/icon/gradient.tsx
- packages/components/loading/loading.tsx
- refactor(loading): component optimization
> refactor(loading): component optimization

- packages/components/date-picker/DatePicker.tsx
- packages/components/date-picker/DatePickerPanel.tsx
- packages/components/date-picker/DateRangePicker.tsx
- packages/components/date-picker/DateRangePickerPanel.tsx
- packages/components/date-picker/base/style/css.js
- packages/components/date-picker/base/style/index.js
- packages/components/date-picker/components/base/Cell.tsx
- packages/components/date-picker/components/base/Footer.tsx
- packages/components/date-picker/components/base/Header.tsx
- packages/components/date-picker/components/base/Table.tsx
- packages/components/date-picker/components/base/style/css.js
- packages/components/date-picker/components/base/style/index.js
- packages/components/date-picker/components/panel/ExtraContent.tsx
- packages/components/date-picker/components/panel/PanelContent.tsx
- packages/components/date-picker/components/panel/RangePanel.tsx
- packages/components/date-picker/components/panel/SinglePanel.tsx
- packages/components/date-picker/components/panel/style/css.js
- packages/components/date-picker/components/panel/style/index.js
- packages/components/date-picker/hooks/index.ts
- packages/components/date-picker/hooks/useDisableDate.ts
- packages/components/date-picker/hooks/useRange.tsx
- packages/components/date-picker/hooks/useRangeValue.ts
- packages/components/date-picker/hooks/useSingle.tsx
- packages/components/date-picker/hooks/useSingleValue.tsx
- packages/components/date-picker/hooks/useTableData.tsx
- packages/components/date-picker/panel/style/css.js
- packages/components/date-picker/panel/style/index.js
- refactor(date-picker): component optimization
> refactor(date-picker): component optimization

- packages/components/color-picker/color-picker.tsx
- packages/components/color-picker/components/style/css.js
- packages/components/color-picker/components/style/index.js
- packages/components/color-picker/components/trigger.tsx
- refactor(color-picker): component optimization
> refactor(color-picker): component optimization

- packages/components/image-viewer/base/ImageItem.tsx
- packages/components/image-viewer/base/ImageViewerModal.tsx
- packages/components/image-viewer/base/ImageViewerUtils.tsx
- packages/components/image-viewer/image-viewer.en-US.md
- packages/components/image-viewer/image-viewer.md
- packages/components/image-viewer/image-viewer.tsx
- packages/components/image-viewer/props.ts
- packages/components/image-viewer/type.ts
- https://github.com/Tencent/tdesign-vue/issues/3504
- feat(ImageViewer): 新增`imageReferrerpolicy`API，适用于配置Referrerpolicy的场景
- feat(ImageViewer): 新增`onDownload`API，用于自定义下载回调
> feat(imageViewer): add Download Callback API

- .eslintignore
- .eslintrc
- .gitignore
- package.json
- packages/tdesign-vue-next/site/package.json
> chore(deps):  update deps

- packages/components/select/hooks/useSelectOptions.ts
https://github.com/Tencent/tdesign-vue-next/pull/5104/files#diff-a27ca496e7753d330137ae9277991a0f498109e3f1549ec73408445d8eb11b59R108
- fix(Select): 使用 `filter` 时无需设置 `filterable`
> fix(Select): unnecessary `filterable` when `filter`

- packages/components/date-picker/DatePicker.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/5160
- https://github.com/Tencent/tdesign-vue-next/issues/4992
- fix(DatePicker):  修复`prefixIcon` 插槽告警的问题
- feat(ConfigProvider): 新增支持`@tdesign-vue-next/chat`的国际化配置能力
> chore: fix warning and update common

- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
- release vue-next 1.11.3
- chore:  release vue-next 1.11.3
> chore: release tdesign-vue-next  1.11.3

- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
- chore: release tdesign-vue-next 1.11.4
> chore: release tdesign-vue-next 1.11.4

- .github/ISSUE_TEMPLATE/bug-report.zh-CN.yml
- .github/ISSUE_TEMPLATE/feature-report.zh-CN.yml
当用户每提出一个问题的时候都会自动打上对应类别标签，另会打上一个 no-confirm 的标签用来标记他还没有被审查。
>  chore: add default issue labels 

- package.json
https://github.com/Tencent/tdesign-vue-next/issues/5212
- ci: up pnpm to 9.15.9
> ci: up pnpm to 9.15.9

- packages/components/card/card.en-US.md
- packages/components/card/card.md
> docs(card): synchronize api documentation

- packages/components/tree-select/props.ts
- packages/components/tree-select/type.ts
- fix(TreeSelect): 修复 `panelTopContent` 和 `panelBottomContent` 的定义缺失问题
> fix(TreeSelect): fix panelContent props definition

- packages/components/table/hooks/useDragSort.ts
对于 https://github.com/Tencent/tdesign-vue-next/pull/5140 pr 的回归。
- fix(Table): 修复表格内容未渲染时，设置 `drag-sort` 拖动事件报错的问题
- fix(Table): 修复 Table 展开的详细内容文字无法被选中的问题
> fix(table): correct drag-and-drop in drawer and restore text selection behavior

- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
> chore: release 1.11.5

- packages/components/select/select.tsx
#5219
- fix(Select): 当 `check-all` 为空字符串时，展示效果异常的问题
> fix(select): improve check-all condition to handle empty string case

- packages/components/select/select.tsx
https://github.com/Tencent/tdesign-vue-next/issues/5249
- fix(Select):  修复 `tips` 插槽无效
> fix(select): tips slot invalid

- packages/tdesign-vue-next/site/docs/getting-started.en-US.md
- packages/tdesign-vue-next/site/docs/getting-started.md
> docs: add usage tips

- .github/CODEOWNERS
- packages/tdesign-vue-next/site/src/components/demo-page.vue
> fix: globEager is deprecated

- vitest.workspace.ts
vitest.config.js 改成 vitest.config.ts 后 vitest vscode 插件报错
> chore(vitest): fix vscode error

- packages/components/tabs/tab-nav.tsx
- packages/components/tabs/tabs.md
- https://github.com/Tencent/tdesign-vue-next/issues/4934
- chore(Tabs): `action`在`placement`为`left`或`right`时不会进行渲染
> chore(Tabs): limit action render while placement not horizontal

- packages/components/form/consts/index.ts
- packages/components/form/form-item.tsx
- packages/components/form/form.en-US.md
- packages/components/form/form.md
- packages/components/form/form.tsx
- packages/components/form/props.ts
- packages/components/form/type.ts
- https://github.com/Tencent/tdesign-vue-next/issues/4715
- feat(Form): 新增`requiredMarkPosition`，用于支持定义必填符号的位置
> feat(Form): support rightSide required mark

- packages/components/swiper/__tests__/__snapshots__/index.test.jsx.snap
- packages/components/swiper/__tests__/index.test.jsx
- packages/components/swiper/props.ts
- packages/components/swiper/swiper-item.tsx
- packages/components/swiper/swiper.en-US.md
- packages/components/swiper/swiper.md
- packages/components/swiper/type.ts
- https://github.com/Tencent/tdesign-vue-next/issues/5262
[Swiper] 卡片模式需要支持自定义缩放比例
- feat(swiper): 卡片模式支持自定义缩放比例
> feat(Swiper): support cardScale API

- packages/components/form/_usage/props.json
- packages/components/form/form-item.tsx
- https://github.com/Tencent/tdesign-vue-next/pull/5223
- usage新加操作选项
- 修复一个小问题（设置显示mark markPosition才有效）
> chore(Form): usage

- packages/components/color-picker/components/format/index.tsx
- fix #5230 
- fix(ColorPicker): 修复切换颜色无效的问题
> fix(ColorPicker): fix toggle color format invalid

- packages/components/date-picker/date-picker.en-US.md
- packages/components/date-picker/date-picker.md
- packages/components/date-picker/props.ts
- packages/components/date-picker/type.ts
- #5293
-  https://github.com/TDesignOteam/tdesign-api/pull/599
- 跟 `form readonly` 优先级有问题 ，`DatePicker readonly` 默认值需要改为 `undefined`
> feat(DatePicker): fix readonly default value

- packages/components/date-picker/hooks/useRange.tsx
- fix(DatePicker): 修复`DateRangePicker` 在 readonly 状态下 clearable 仍然生效的问题
> fix(DateRangePicker): 修复 readonly 状态下 clearable 处理逻辑，应为不可用

- packages/components/guide/__tests__/vitest-guide.test.jsx
https://github.com/Tencent/tdesign-common/actions/runs/14532388638/job/40774436551
60ms 太短 ，CI 偶尔会失败，改到200ms 降低失败概率
> test(guide): mockDelay 60 change to 200

- packages/components/hooks/useDragSort.tsx
- fix(Tabs): 处理路由切换过程中 Tabs 未初始化出现卸载错误的其他
> fix(useDragSort): prevent unmount error with missing elements on init

- packages/components/select/hooks/useKeyboardControl.ts
- packages/components/select/select.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/4768
- fix(Select): 修复多选场景下`onEnter`回调参数丢失的问题，同时保持多选单选回车交互逻辑一致
- fix(Select): 修复多选场景下无法通过键盘操作选中全选选项的问题
> fix(Select): fix onEnter inputValue param missing in multiple mode

- packages/components/table/hooks/useRowSelect.tsx
- fix(Table): 修复column的`checkProps`未配置导致的点击行选中行为异常的问题
> fix(Table): fix click row bug when col checkProps is undefined

- packages/components/menu/_usage/index.vue
> docs(menu): update usage example

- .github/workflows/pull-request.yml
> ci(pull-request): split lint job

- packages/components/date-picker/DatePicker.tsx
- fix(DatePicker):  修复`label`插槽无效的问题
> fix(date-picker): use renderTNodeJSX to render slots `label`

- packages/tdesign-vue-next/package.json
release tdesign-vue-next 1.13.0-alpha.1
> chore: release tdesign-vue-next 1.13.0-alpha.1

- .github/workflows/auto-changelog-callback.yml
- .github/workflows/auto-changelog.yml
- packages/components/button/_example/loading.vue
> ci(auto-changelog): fix fork pr

- packages/components/tag/__tests__/vitest-tag.test.jsx
- packages/components/tag/tag.tsx
- packages/tdesign-vue-next/.changelog/pr-5413.md
#5411
- fix(Tag): 未设置 `max-width` 导致无法渲染 `title` 属性的问题
> fix(tag): allow title rendering without max-width restriction

- packages/components/date-picker/date-picker.md
- packages/components/date-picker/date-range-picker-props.ts
- packages/components/date-picker/type.ts
- https://github.com/Tencent/tdesign-vue-next/issues/5366
- fix(DateRangePicker): 修复缺少`readonly`类型定义的问题
> fix(DateRangePicker): readonly type

- package.json
- packages/components/chat/_example/chat-sender-slot.vue
- packages/components/chat/_example/chat-sender.vue
- packages/tdesign-vue-next-chat/site/package.json
- packages/tdesign-vue-next-chat/site/vite.config.ts
> fix(chat): 处理attachments接入空白问题

- packages/components/radio/group.tsx
- packages/components/radio/hooks/useKeyboard.ts
- packages/tdesign-vue-next/.changelog/pr-5417.md
#5410
- fix(RadioGroup): 修复阻止默认行为时机错误导致无法正确输入空格的问题
- fix(RadioGroup): 修复键盘操作时重复触发`onChange`事件的问题
> fix(radio): improve inner value update logic and keyboard handling

- packages/tdesign-vue-next/.changelog/pr-5430.md
> chore: add pr-5430 changelog

- packages/components/drawer/type.ts
- packages/tdesign-vue-next/.changelog/pr-5444.md
- fix(Drawer): 修复 `DrawerPlugin` 返回实例类型错误的问题
> fix(Drawer): fix Instance Type

- packages/components/breadcrumb/breadcrumb.tsx
- packages/components/breadcrumb/hooks/useBreadcrumbOptions.ts
- packages/components/breadcrumb/hooks/useEllipsis.ts
- packages/tdesign-vue-next/.changelog/pr-5414.md
- https://github.com/Tencent/tdesign-vue-next/issues/5403
- fix(Breadcrumb): 修复`1.12.0`版本改动导致的响应式和控制台告警的问题
> fix(breadcrumb): fix breadcrumb items is not responsive

- packages/components/chat/chat-sender-props.ts
- packages/components/chat/chat-sender.md
- packages/components/chat/chat-sender.tsx
> fix: sender组件问题修复

- .github/workflows/auto-changelog.yml
- packages/tdesign-vue-next/.changelog/pr-5143.md
- packages/tdesign-vue-next/.changelog/pr-5319.md
- packages/tdesign-vue-next/.changelog/pr-5349.md
- packages/tdesign-vue-next/.changelog/pr-5357.md
- packages/tdesign-vue-next/.changelog/pr-5373.md
- packages/tdesign-vue-next/.changelog/pr-5374.md
- packages/tdesign-vue-next/.changelog/pr-5375.md
- packages/tdesign-vue-next/.changelog/pr-5388.md
- packages/tdesign-vue-next/.changelog/pr-5393.md
- packages/tdesign-vue-next/.changelog/pr-5413.md
- packages/tdesign-vue-next/.changelog/pr-5414.md
- packages/tdesign-vue-next/.changelog/pr-5417.md
- packages/tdesign-vue-next/.changelog/pr-5418.md
- packages/tdesign-vue-next/.changelog/pr-5424.md
- packages/tdesign-vue-next/.changelog/pr-5427.md
- packages/tdesign-vue-next/.changelog/pr-5428.md
- packages/tdesign-vue-next/.changelog/pr-5430.md
- packages/tdesign-vue-next/.changelog/pr-5444.md
- packages/tdesign-vue-next/.changelog/pr-5446.md
- packages/tdesign-vue-next/.changelog/pr-5451.md
- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
> chore: release vue-next 1.13.0

- .github/workflows/auto-publish.yml
- .github/workflows/preview-build.yml
- packages/tdesign-vue-next/CHANGELOG.md
> ci(auto-publish): fix publish tag site

- packages/tdesign-vue-next/site/vite.config.ts
> chore: add host for network visit

- packages/components/switch/switch.tsx
https://github.com/Tencent/tdesign-vue-next/issues/5458
自定义值 错误消息优化
之前
之后
> perf(switch): optimize custom value error prompts

- packages/tdesign-vue-next-chat/site/docs/getting-started.md
- https://github.com/Tencent/tdesign-vue-next/issues/5470
> docs: update chat usage docs

- packages/tdesign-vue-next/CHANGELOG.md
> docs: update CHANGELOG

- packages/components/transfer/utils/index.ts
- packages/tdesign-vue-next/.changelog/pr-5475.md
-  fix(Transfer): 优化动态加载数据场景下的组件报错问题
> fix(transfer): source & target can be undefined

- packages/pro-components/chat/_example/base.vue
- packages/pro-components/chat/_example/reasoning-drag.vue
- packages/pro-components/chat/_example/reasoning-drawer.vue
- packages/pro-components/chat/_example/reasoning.vue
> fix(chat): fix demo chat reasoning and clear history

- packages/components/config-provider/config-provider.en-US.md
- packages/components/config-provider/config-provider.md
- packages/components/config-provider/type.ts
- packages/components/form/form-item.tsx
- packages/components/form/props.ts
- packages/components/form/type.ts
- packages/tdesign-vue-next/.changelog/pr-5510.md
- #5504 
- feat(GlobalConfig): `FormConfig` 新增 `requiredMaskPosition`
> feat(FormGlobalConfig): add requiredMaskPosition

- packages/hooks/tnode/index.ts
- packages/tdesign-vue-next/.changelog/pr-5521.md
- https://github.com/Tencent/tdesign-vue-next/issues/5493
- fix: 优化插槽方法的判断兼容更多组件类型的使用
> fix: fix slot fail to load when slot is module

- .github/workflows/auto-publish.yml
> ci: fix auto-publish

- .github/workflows/pkg-pr-new.yml
- packages/tdesign-vue-next-chat/package.json
- packages/tdesign-vue-next/package.json
chat 组件包未带上repository ，暂时不使用pkg-pr-new 短链接
> ci(pkg-pr-new): add chat

- README-zh_CN.md
- README.md
> docs: update a new contributions charts 

- packages/components/table/hooks/useColumnController.tsx
- packages/tdesign-vue-next/.changelog/pr-5546.md
https://github.com/user-attachments/assets/b0cb6eec-8969-48e9-bfc4-5759c153e8c3
- fix(Table): 优化关闭列配置弹窗时，选择列数据与所展示列数据不一致的问题
> fix(useColumnController): sync columnCheckboxKeys on close

- packages/components/table/hooks/useAffix.ts
- https://github.com/Tencent/tdesign-vue-next/issues/5298
> fix(Table): fix table affix robustness

- packages/tdesign-vue-next/.changelog/pr-5522.md
- packages/tdesign-vue-next/.changelog/pr-5538.md
- packages/tdesign-vue-next/.changelog/pr-5545.md
- packages/tdesign-vue-next/.changelog/pr-5546.md
- packages/tdesign-vue-next/.changelog/pr-5553.md
- packages/tdesign-vue-next/.changelog/pr-5555.md
- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
> chore: release tdesign-vue-next 1.13.2

- packages/pro-components/chat/chat-action/_example/chat-action.vue
- packages/pro-components/chat/chat-action/chat-action-props.ts
- packages/pro-components/chat/chat-action/chat-action.md
- packages/pro-components/chat/chat-action/chat-action.tsx
- packages/pro-components/chat/type.ts
chat-action 组件新增分享按钮
- [✅] 新特性提交
- [ ✅] 文档已补充或无须补充
- [✅ ] 代码演示已提供或无须提供
- [✅ ] TypeScript 定义已补充或无须补充
- [✅ ] Changelog 已提供或无须提供
> feat: chat-action 组件新增 分享按钮

- packages/components/select/__tests__/__snapshots__/index.test.jsx.snap
- packages/components/select/select.tsx
- packages/tdesign-vue-next/.changelog/pr-5594.md
1.13.2   https://stackblitz.com/edit/ciedwl13-tylcxa8r?file=package.json,src%2Fdemo.vue
1.11.5    https://stackblitz.com/edit/ciedwl13?file=package.json,src%2Fdemo.vue
- fix(Select): 添加 `selectInputProps` 透传多选属性到 `valueDisplay`
> fix(Select): add `selectInputProps` to pass multiple selection attrs

- packages/components/cascader/hooks/index.ts
- packages/components/cascader/utils/helper.ts
- packages/tdesign-vue-next/.changelog/pr-5581.md
https://github.com/Tencent/tdesign-vue-next/issues/5579
- fix(cascader): 修复 `value-type="full"` ，value 为 undefined时组件内部报错
> fix(cascader): fix value-type="full", value is undefined error

- packages/pro-components/chat/chat-sender.tsx
- packages/tdesign-vue-next-chat/.changelog/pr-5608.md
[上个PR](https://github.com/Tencent/tdesign-vue-next/pull/5601)还有点bug，修改后重新开了此PR
- fix(chat-sender): 修复 windows 中文输入法（微软拼音）下使用 `shift +组合键` 先松开 shift 键再松开组合键之后，未同步取消 shift 功能的问题
- fix(chat-sender): 修复聚焦输入框后，按住 shift 后失焦再松开 shift 时，未同步取消 shift 功能的问题
> fix(chat-sender): 修复在中文输入法（微软）下不能同步取消 `Shift` 功能

- packages/components/select/_example-ts/remote-search.vue
- packages/components/select/_example/remote-search.vue
> docs(Select): optimization of remote-search example

- .github/workflows/auto-release.yml
- .github/workflows/pkg-pr-new.yml
- package.json
> chore(deps): remove npm-run-all2

- packages/tdesign-vue-next/CHANGELOG.md
> fix(CHANGELOG): adjust indentation 

- .github/workflows/pkg-pr-new.yml
- .github/workflows/preview-build.yml
- .github/workflows/pull-request.yml
- .gitignore
- packages/tdesign-vue-next-chat/package.json
- pnpm-lock.yaml
1. 增加pnpm 锁文件，ci 安装运行pnpm install 增加--frozen-lockfile
https://pnpm.io/zh/cli/install#--frozen-lockfile 
2. chat 组件依赖 `tdesign-vue-next`,版本改为 pnpm workspace 协议
https://pnpm.io/zh/workspaces#%E5%8F%91%E5%B8%83%E5%B7%A5%E4%BD%9C%E7%A9%BA%E9%97%B4%E5%8C%85
> chore: add pnpm lock

- .github/CODEOWNERS
- tsconfig.json
- chore: 支持 pro-components/chat 中的类型引入和检查
> chore: support type check in chat demos

- packages/components/time-picker/time-range-picker.tsx
- packages/tdesign-vue-next/.changelog/pr-5622.md
ref #5591
- fix(TimeRangePicker): 点击面板确定按钮未重置非法格式输入
> fix(time-range-picker): invalid input reset

- packages/components/select/select.tsx
- packages/components/select/utils/index.ts
- packages/tdesign-vue-next/.changelog/pr-5660.md
- https://github.com/Tencent/tdesign-vue-next/issues/5630
- https://github.com/Tencent/tdesign-vue-next/issues/5657
- fix(Select): 修复多选远程搜索场景下， 当前选中项不存在 options 内时，placeholder 展示异常的问题
- fix(Select): 修复多选远程搜索场景下，当前选中项不存在 options 内时，删除选项功能异常的问题
> fix(Select): when value not in option, value tag cannot backspace delete

- packages/tdesign-vue-next/.changelog/pr-5660.md
- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
> chore: release 1.14.1

- packages/tdesign-vue-next-chat/site/package.json
- packages/tdesign-vue-next/site/package.json
- pnpm-lock.yaml
- chore: update site components version to fix security check  
> chore: update site components version to fix check

- packages/components/button/button.tsx
- packages/tdesign-vue-next/.changelog/pr-5676.md
- fix(Button): 修复`form`属性不生效的问题
> fix(Button): fix form props of button

- packages/components/dialog/hooks/useSameTarget.ts
Related https://github.com/Tencent/tdesign-vue-next/pull/5675
> fix(dialog): ensure `handleClick` is defined before invoking in `useSameTarget`

- packages/components/config-provider/hooks/useConfig.ts
- packages/components/pagination/pagination.tsx
- packages/tdesign-vue-next/.changelog/pr-5680.md
https://github.com/Tencent/tdesign-common/issues/2119
支持多语言复数展示
- feat(locale): 支持内置多语言的英文版本的单复数场景正常展示
> feat(locale): support i18n plural for pagination.total

- packages/tdesign-vue-next-chat/.changelog/pr-5608.md
- packages/tdesign-vue-next-chat/.changelog/pr-5612.md
- packages/tdesign-vue-next-chat/.changelog/pr-5617.md
- packages/tdesign-vue-next-chat/CHANGELOG.md
- packages/tdesign-vue-next-chat/package.json
修复用户消息字体样式发版
https://github.com/Tencent/tdesign-vue-next/issues/5614
t-chat__text--user pre下的新增font字体
feat(chat): css样式修改
> release @tdesign-vue-next/chat 0.4.2

- packages/tdesign-vue-next-chat/site/package.json
- packages/tdesign-vue-next-chat/site/src/main.js
- pnpm-lock.yaml
chat 站点没有用图标预览
加入tdesign-icons-view 增大了打包体积
移除前
dist/assets/index-NyBkQx8o.js                 8,633.91 kB │ gzip: 2,560.47 kB
移除后
dist/assets/index-BDWiUZ0I.js                 5,352.11 kB │ gzip: 1,745.37 kB
> chore: optimize the size of chat website site

- packages/pro-components/chat/chatbot/_example/docs.vue
- packages/pro-components/chat/chatbot/_example/image.vue
- packages/tdesign-vue-next-chat/package.json
- pnpm-lock.yaml
> feat: 升级wc组件;修复image doc custom示例

- packages/components/date-picker/DatePicker.tsx
- packages/tdesign-vue-next/.changelog/pr-5732.md
#5729
- fix(DatePicker): 处理多选情况下周和季度模式的标签删除异常的问题
> fix(date-picker): handle tag removal for week and quarter modes

- packages/pro-components/chat/chat-thinking/_example/think-base.vue
- packages/pro-components/chat/chat-thinking/_example/think-style.vue
- packages/pro-components/chat/chat-thinking/_usage/index.vue
- packages/pro-components/chat/chatbot/_example/docs.vue
- packages/pro-components/chat/chatbot/_example/image.vue
- packages/tdesign-vue-next-chat/package.json
> feat: 升级webc为1.1.7；修正示例中chat-thinking组件使用；修改onChatSent事件为onChatAfterSend

- packages/tdesign-vue-next/test/scripts/generate-coverage.ts
> fix: format re-generate coverage report

- packages/components/dialog/dialog.md
closed #5625
https://github.com/Tencent/tdesign-vue-next/issues/5625
> docs(dialog): the nested dialogs are supplemented with parameters

- packages/components/table/hooks/useFixed.ts
- https://github.com/Tencent/tdesign-vue-next/issues/5741
> fix(table): fix calculation oldTotalWidth error

- packages/components/checkbox/group.tsx
- packages/tdesign-vue-next/.changelog/pr-5749.md
- https://stackblitz.com/edit/yeuk8cbj?file=package.json,src%2Fdemo.vue
- fix(Checkbox): 修复全选功能在只读或禁用选项，但已选中场景下的功能问题
> fix(Checkbox): fix uncheckall remove readonly and disabled value

- packages/tdesign-vue-next/.changelog/pr-5670.md
- packages/tdesign-vue-next/.changelog/pr-5678.md
- packages/tdesign-vue-next/.changelog/pr-5679.md
- packages/tdesign-vue-next/.changelog/pr-5680.md
- packages/tdesign-vue-next/.changelog/pr-5717.md
- packages/tdesign-vue-next/.changelog/pr-5719.md
- packages/tdesign-vue-next/.changelog/pr-5722.md
- packages/tdesign-vue-next/.changelog/pr-5726.md
- packages/tdesign-vue-next/.changelog/pr-5732.md
- packages/tdesign-vue-next/.changelog/pr-5748.md
- packages/tdesign-vue-next/.changelog/pr-5749.md
- packages/tdesign-vue-next/.changelog/pr-5751.md
- packages/tdesign-vue-next/.changelog/pr-5752.md
- packages/tdesign-vue-next/.changelog/pr-5754.md
- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
> chore: release 1.15.0

- packages/tdesign-vue-next/.changelog/pr-5758.md
- packages/tdesign-vue-next/global.d.ts
- packages/tdesign-vue-next/helper/attributes.json
- packages/tdesign-vue-next/helper/tags.json
- packages/tdesign-vue-next/helper/web-types.json
- feat(QRcode): 增加编辑器代码提示, 请注意该组件暂时不支持 `unplugin-auto-import` 的使用方式 ⚠️ 
> feat(qrcode): add code tips

- packages/tdesign-vue-next-chat/site/docs/getting-started.md
- https://github.com/Tencent/tdesign-vue-next/issues/5767
> docs(chat): update usage docs

- packages/auto-import-resolver/CHANGELOG.md
- packages/auto-import-resolver/package.json
> chore: release auto-import-resolver 0.1.0

- packages/auto-import-resolver/.changelog/pr-5786.md
- packages/auto-import-resolver/README.md
- packages/auto-import-resolver/src/resolver.ts
改进https://github.com/Tencent/tdesign-vue-next/pull/5786, 移除autoImport
> chore: remove autoImport

- packages/components/color-picker/components/panel/index.tsx
- packages/tdesign-vue-next/.changelog/pr-5793.md
#5792
- fix(ColorPicker): 修复设置 `swatch-colors` 值为 `null` 时功能异常的问题
> fix(color-picker): function abnormality when setting the switch-colors value to null

- packages/auto-import-resolver/.changelog/pr-5786.md
- packages/auto-import-resolver/CHANGELOG.md
- packages/auto-import-resolver/package.json
> chore: release auto-import-resolver 0.1.1

- packages/components/icon/__tests__/icon-svg.test.tsx
- packages/components/icon/__tests__/iconfont.test.tsx
> test(icon): improve icon test coverage

- packages/components/date-picker/DateRangePicker.tsx
- packages/components/date-picker/components/base/Footer.tsx
- packages/components/date-picker/components/panel/ExtraContent.tsx
- packages/components/date-picker/components/panel/RangePanel.tsx
- packages/components/date-picker/components/panel/SinglePanel.tsx
- packages/tdesign-vue-next/.changelog/pr-5795.md
- feat(DatePicker): `DateRangePicker` 支持 `needConfirm` API
> feat(DatePicker): date-range-picker support need-confirm API

- packages/tdesign-vue-next/.changelog/pr-5775.md
- packages/tdesign-vue-next/.changelog/pr-5781.md
- packages/tdesign-vue-next/.changelog/pr-5782.md
- packages/tdesign-vue-next/.changelog/pr-5790.md
- packages/tdesign-vue-next/.changelog/pr-5793.md
- packages/tdesign-vue-next/.changelog/pr-5795.md
- packages/tdesign-vue-next/.changelog/pr-5809.md
- packages/tdesign-vue-next/.changelog/pr-5812.md
- packages/tdesign-vue-next/.changelog/pr-5814.md
- packages/tdesign-vue-next/.changelog/pr-5821.md
- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
> chore: release 1.15.2

- packages/pro-components/chat/chat-action.tsx
- packages/pro-components/chat/chat-content.tsx
- packages/pro-components/chat/chat-input.tsx
- packages/pro-components/chat/chat-item.tsx
- packages/pro-components/chat/chat-sender.tsx
- packages/pro-components/chat/chat.tsx
- packages/tdesign-vue-next-chat/.changelog/pr-5828.md
- https://stackblitz.com/edit/vitejs-vite-hiwzwfkm?file=src%2FApp.vue
- fix(Chat): 修复`0.4.3` 版本后多语言功能没有正确响应切换的问题
> fix(Chat): fix i18n reactive

- packages/tdesign-vue-next/site/plugins/td-doc-to-vue/render-demo.ts
- packages/tdesign-vue-next/site/src/components/newWindow/index.vue
- packages/tdesign-vue-next/site/src/main.ts
> docs: demo of opening a new window

- packages/components/loading/__tests__/__snapshots__/loading.test.tsx.snap
- packages/components/loading/__tests__/loading.test.tsx
本 PR 关联 issue: [#5631](https://github.com/Tencent/tdesign-vue-next/issues/5631)
1. 优化Loading组件测试用例
2. 保持测试覆盖率同时简化测试逻辑
test(loading): 扩展 Loading 组件及插件测试用例，新增多场景验证
> test(loading): 扩展 Loading 组件及插件测试用例，新增多场景验证

- packages/tdesign-vue-next-chat/site/src/components/newWindow/index.vue
- packages/tdesign-vue-next/site/src/components/newWindow/index.vue
> fix(docs): new windows icon color

- packages/components/select/select.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/5835
> fix(Select): remove extraneous non-props attributes `size`

- packages/tdesign-vue-next-chat/site/src/components/stackblitz/content.js
- packages/tdesign-vue-next/site/src/components/stackblitz/content.ts
> docs(stackblitz): optimize startup speed

- packages/components/statistic/props.ts
- packages/components/statistic/statistic.en-US.md
- packages/components/statistic/statistic.md
- packages/components/statistic/type.ts
Related https://github.com/TDesignOteam/tdesign-api/pull/690
> docs(Statistic): update color docs

- packages/components/table/table.en-US.md
- packages/components/table/table.md
- packages/tdesign-vue-next/.changelog/pr-5870.md
https://github.com/Tencent/tdesign-vue-next/issues/5769
- docs(Table): 完善 `scrollToElement` 函数参数说明
> docs(Table): update docs for scrollToElement API

- packages/components/checkbox/checkbox.tsx
- packages/tdesign-vue-next/.changelog/pr-5825.md
- fix(checkbox): 修复点击之后 `onClick` 事件触发两次的问题 
> fix(checkbox): prevent `onClick` from triggering twice

- packages/components/cascader/utils/effect.ts
- packages/tdesign-vue-next/.changelog/pr-5866.md
#4794 
- fix(Cascader): 修复可过滤场景下，鼠标移入下拉面板后展现异常的缺陷
> fix(Cascader): prevent expanded nodes from updating during filtering

- internal/utils/src/catalogs.ts
- packages/tdesign-vue-next/test/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
```bash
2025-08-13T03:32:50.5346361Z [90mstderr[2m | ../../components/qrcode/__tests__/qrcode.test.tsx[2m > [22m[2mQRCode[2m > [22m[2mprops[2m > [22m[2m:bgColor[string]
2025-08-13T03:32:50.5348286Z [22m[39mError: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
2025-08-13T03:32:50.5350152Z     at module.exports (/home/runner/work/tdesign-vue-next/tdesign-vue-next/node_modules/.pnpm/jsdom@19.0.0/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
2025-08-13T03:32:50.5352627Z     at HTMLCanvasElementImpl.getContext (/home/runner/work/tdesign-vue-next/tdesign-vue-next/node_modules/.pnpm/jsdom@19.0.0/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
2025-08-13T03:32:50.5355517Z     at …
```
> test(qrcode): fix error not implemented without installing the canvas npm package

- packages/tdesign-vue-next/.changelog/pr-5825.md
- packages/tdesign-vue-next/.changelog/pr-5839.md
- packages/tdesign-vue-next/.changelog/pr-5842.md
- packages/tdesign-vue-next/.changelog/pr-5843.md
- packages/tdesign-vue-next/.changelog/pr-5862.md
- packages/tdesign-vue-next/.changelog/pr-5864.md
- packages/tdesign-vue-next/.changelog/pr-5866.md
- packages/tdesign-vue-next/.changelog/pr-5867.md
- packages/tdesign-vue-next/.changelog/pr-5868.md
- packages/tdesign-vue-next/.changelog/pr-5870.md
- packages/tdesign-vue-next/.changelog/pr-5881.md
- packages/tdesign-vue-next/.changelog/pr-5882.md
- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
- chore: release tdesign-vue-next 1.15.3
> release: tdesign-vue-next 1.15.3

- packages/components/back-top/__tests__/__snapshots__/back-top.test.tsx.snap
- packages/components/back-top/__tests__/back-top.test.tsx
#5631
添加测试条件，back-top 覆盖率增加至 100%。
Before:
```md
-----------------------|---------|----------|---------|---------|----------------------------------------
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                      
-----------------------|---------|----------|---------|---------|----------------------------------------
All files              |   78.28 |    64.28 |   69.23 |   78.28 |                                        
back-top              |   83.53 |     61.9 |   88.88 |   83.53 |                                        
back-top.tsx         |   74.28 |    64.28 |      80 |   74.28 | 29-34,42-43,45-47,52-53,55-61,66,92-97 
index.ts             |     100 |      100 |     100 |     100 |                                        
props.ts …
```
> test(back-top): add more cases for 100% coverage

- packages/pro-components/chat/chat-input.tsx
- packages/tdesign-vue-next-chat/.changelog/pr-5905.md
- https://github.com/Tencent/tdesign-vue-next/issues/5903
- fix(chat-input): 修复 `suffixIcon` 传值不是插槽，响应式无效
> fix(chat-input): fix suffixIcon type not slot, reactive invalid

- packages/components/tree/_example/draggable.vue
- packages/components/tree/hooks/useTreeItem.tsx
- packages/tdesign-vue-next/.changelog/pr-5914.md
- fix(Tree): 修复 `draggable` 在 `disabled` 状态下依旧生效的异常，此前有依赖此错误的业务请注意此变动 ⚠️
> fix(Tree): add disabled state check for draggable nodes

- packages/components/transfer/components/transfer-operations.tsx
- packages/tdesign-vue-next/.changelog/pr-5794.md
- fix(Transfer): 修复 `operation`  传递函数数组渲染错误的问题
> fix(transfer): `operation` passing method rendering error

- packages/components/date-picker/DateRangePicker.tsx
- packages/components/date-picker/_example-ts/disable-date.vue
- packages/components/date-picker/_example/disable-date.vue
- packages/components/date-picker/components/panel/PanelContent.tsx
- packages/components/date-picker/components/panel/RangePanel.tsx
- packages/components/date-picker/date-range-picker-props.ts
- packages/components/date-picker/hooks/useRangeValue.ts
- packages/components/date-picker/utils/index.ts
- packages/tdesign-vue-next/.changelog/pr-5940.md
- fix(DateRangePicker): 修复`disableTime` 功能异常的问题
- fix(DateRangePicker): 修复`disableDate` 的函数用法返回参数回调与文档不符的问题，此前有基于错误参数请注意此变更 ⚠️
> fix(DatePicker): fix date range picker callback params

- packages/components/skeleton/_example-ts/theme.vue
- packages/components/skeleton/_example/theme.vue
- packages/components/skeleton/_usage/index.vue
- to optimize https://tdesign.tencent.com/vue-next/components/skeleton#%E4%B8%8D%E5%90%8C%E4%B8%BB%E9%A2%98%E7%9A%84%E9%AA%A8%E6%9E%B6%E5%B1%8F
> chore: optimize skeleton demo

- packages/tdesign-vue-next/.changelog/pr-5794.md
- packages/tdesign-vue-next/.changelog/pr-5853.md
- packages/tdesign-vue-next/.changelog/pr-5872.md
- packages/tdesign-vue-next/.changelog/pr-5885.md
- packages/tdesign-vue-next/.changelog/pr-5910.md
- packages/tdesign-vue-next/.changelog/pr-5914.md
- packages/tdesign-vue-next/.changelog/pr-5932.md
- packages/tdesign-vue-next/.changelog/pr-5940.md
- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
- chore: release tdesign-vue-next 1.16.0
> chore: release tdesign-vue-next 1.16.0

- packages/components/tabs/tab-nav-item.tsx
- packages/tdesign-vue-next/.changelog/pr-5955.md
- https://github.com/Tencent/tdesign-vue-next/pull/5853
- fix(Tabs): 修复`1.16.0` 新增 `TabPanel` onRemove 事件后导致的移除选项时控制台报错的问题
> fix(Tabs): fix tab panel onRemove is undefined

- packages/tdesign-vue-next/.changelog/pr-5955.md
- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
> chore: release 1.16.1

- packages/components/link/__tests__/__snapshots__/link.test.tsx.snap
- packages/components/link/__tests__/link.test.tsx
> test(link): update test case

- packages/components/steps/__tests__/step-item.test.tsx
- packages/components/steps/__tests__/steps.test.tsx
- packages/tdesign-vue-next/.changelog/pr-5957.md
- https://github.com/Tencent/tdesign-vue-next/issues/5631
- test(Steps): improve the test coverage of Steps
> test(Steps): improve the test coverage of Steps

- packages/auto-import-resolver/.changelog/pr-5987.md
- packages/auto-import-resolver/CHANGELOG.md
- packages/auto-import-resolver/package.json
> chore: release auto-import-resolver 0.1.2

- packages/components/tree-select/tree-select.tsx
- packages/tdesign-vue-next/.changelog/pr-6025.md
- https://github.com/Tencent/tdesign-vue-next/issues/6017
- fix(TreeSelect): 修复过滤场景下，展开状态节点前置图标没有正常展示的问题
- fix(TreeSelect): 修复选中节点后展开状态触发不必要的更新的问题
> fix(TreeSelect): fix tree node behavior when expanded

- packages/tdesign-vue-next/.changelog/pr-5705.md
- packages/tdesign-vue-next/.changelog/pr-5935.md
- packages/tdesign-vue-next/.changelog/pr-5957.md
- packages/tdesign-vue-next/.changelog/pr-5958.md
- packages/tdesign-vue-next/.changelog/pr-5968.md
- packages/tdesign-vue-next/.changelog/pr-5971.md
- packages/tdesign-vue-next/.changelog/pr-5977.md
- packages/tdesign-vue-next/.changelog/pr-5982.md
- packages/tdesign-vue-next/.changelog/pr-5990.md
- packages/tdesign-vue-next/.changelog/pr-5991.md
- packages/tdesign-vue-next/.changelog/pr-5993.md
- packages/tdesign-vue-next/.changelog/pr-6009.md
- packages/tdesign-vue-next/.changelog/pr-6016.md
- packages/tdesign-vue-next/.changelog/pr-6019.md
- packages/tdesign-vue-next/.changelog/pr-6022.md
- packages/tdesign-vue-next/.changelog/pr-6025.md
- packages/tdesign-vue-next/CHANGELOG.md
- packages/tdesign-vue-next/package.json
- chore: release tdesign-vue-next 1.17.0
> chore: release tdesign-vue-next 1.17.0

- packages/shared/hooks/tnode/index.ts
fix ci
https://github.com/Tencent/tdesign-vue-next/pull/6045
https://github.com/Tencent/tdesign-vue-next/pull/6043
https://github.com/Tencent/tdesign-vue-next/pull/6041
> chore: fix typo from crate-ci update
